# Generated by Django 6.0.6 on 2026-06-09 10:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_branch_companysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.SlugField(max_length=80)),
                ('gateway_type', models.CharField(choices=[('MOYASAR', 'Moyasar'), ('HYPERPAY', 'HyperPay'), ('PAYTABS', 'PayTabs'), ('TAP', 'Tap'), ('GEIDEA', 'Geidea'), ('STRIPE', 'Stripe'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=30)),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('LIVE', 'Live')], default='SANDBOX', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('public_key', models.CharField(blank=True, max_length=255)),
                ('merchant_id', models.CharField(blank=True, max_length=255)),
                ('settlement_account_code', models.CharField(blank=True, help_text='Accounting account code used for gateway settlements.', max_length=50)),
                ('fee_account_code', models.CharField(blank=True, help_text='Accounting account code used for gateway fees.', max_length=50)),
                ('supports_refunds', models.BooleanField(default=False)),
                ('supports_partial_refunds', models.BooleanField(default=False)),
                ('supports_webhooks', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Payment Gateway',
                'verbose_name_plural': 'Company Payment Gateways',
                'ordering': ['company_id', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.SlugField(max_length=80)),
                ('method_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card'), ('POS_TERMINAL', 'POS Terminal'), ('ONLINE_GATEWAY', 'Online Gateway'), ('TAMARA', 'Tamara'), ('TABBY', 'Tabby'), ('WALLET', 'Wallet'), ('OTHER', 'Other')], default='CASH', max_length=30)),
                ('settlement_behavior', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('NEEDS_SETTLEMENT', 'Needs Settlement'), ('EXTERNAL_CLEARING', 'External Clearing')], default='IMMEDIATE', max_length=30)),
                ('cashbox_account_code', models.CharField(blank=True, help_text='Accounting account code for cashbox or direct cash receipt.', max_length=50)),
                ('bank_account_code', models.CharField(blank=True, help_text='Accounting account code for bank receipt.', max_length=50)),
                ('settlement_account_code', models.CharField(blank=True, help_text='Accounting account code for pending gateway/POS settlement.', max_length=50)),
                ('fee_account_code', models.CharField(blank=True, help_text='Accounting account code for payment fees.', max_length=50)),
                ('fee_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_cash', models.BooleanField(default=False)),
                ('is_bank_transfer', models.BooleanField(default=False)),
                ('is_card', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('is_pos_terminal', models.BooleanField(default=False)),
                ('requires_reference', models.BooleanField(default=False)),
                ('requires_manual_confirmation', models.BooleanField(default=False)),
                ('allow_customer_checkout', models.BooleanField(default=False)),
                ('allow_pos', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='companies.company')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='payments.companypaymentgateway')),
            ],
            options={
                'verbose_name': 'Company Payment Method',
                'verbose_name_plural': 'Company Payment Methods',
                'ordering': ['company_id', 'sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPaymentTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('terminal_code', models.SlugField(max_length=80)),
                ('terminal_id', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('provider_name', models.CharField(blank=True, max_length=120)),
                ('location_note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default_for_branch', models.BooleanField(default=False)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_terminals', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_terminals', to='companies.company')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminals', to='payments.companypaymentgateway')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminals', to='payments.companypaymentmethod')),
            ],
            options={
                'verbose_name': 'Company Payment Terminal',
                'verbose_name_plural': 'Company Payment Terminals',
                'ordering': ['company_id', 'branch_id', 'name', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='companypaymentgateway',
            index=models.Index(fields=['company', 'gateway_type'], name='payments_co_company_99408c_idx'),
        ),
        migrations.AddIndex(
            model_name='companypaymentgateway',
            index=models.Index(fields=['company', 'is_active'], name='payments_co_company_5d1966_idx'),
        ),
        migrations.AddIndex(
            model_name='companypaymentgateway',
            index=models.Index(fields=['company', 'is_default'], name='payments_co_company_bbebb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='companypaymentgateway',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_payment_gateway_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='companypaymentmethod',
            index=models.Index(fields=['company', 'method_type'], name='payments_co_company_aad34a_idx'),
        ),
        migrations.AddIndex(
            model_name='companypaymentmethod',
            index=models.Index(fields=['company', 'is_active'], name='payments_co_company_4dd816_idx'),
        ),
        migrations.AddIndex(
            model_name='companypaymentmethod',
            index=models.Index(fields=['company', 'is_default'], name='payments_co_company_a813f4_idx'),
        ),
        migrations.AddIndex(
            model_name='companypaymentmethod',
            index=models.Index(fields=['company', 'allow_pos'], name='payments_co_company_d2ee0f_idx'),
        ),
        migrations.AddIndex(
            model_name='companypaymentmethod',
            index=models.Index(fields=['company', 'allow_customer_checkout'], name='payments_co_company_34020f_idx'),
        ),
        migrations.AddConstraint(
            model_name='companypaymentmethod',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_payment_method_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='companypaymentterminal',
            index=models.Index(fields=['company', 'branch'], name='payments_co_company_a3cc33_idx'),
        ),
        migrations.AddIndex(
            model_name='companypaymentterminal',
            index=models.Index(fields=['company', 'status'], name='payments_co_company_4cb04d_idx'),
        ),
        migrations.AddIndex(
            model_name='companypaymentterminal',
            index=models.Index(fields=['company', 'is_active'], name='payments_co_company_f0a44f_idx'),
        ),
        migrations.AddIndex(
            model_name='companypaymentterminal',
            index=models.Index(fields=['company', 'is_default_for_branch'], name='payments_co_company_7f6ef6_idx'),
        ),
        migrations.AddConstraint(
            model_name='companypaymentterminal',
            constraint=models.UniqueConstraint(fields=('company', 'terminal_code'), name='unique_payment_terminal_code_per_company'),
        ),
    ]
