# Generated by Django 6.0.6 on 2026-06-19 17:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('SALES_ORDER', 'Sales Order'), ('SALES_INVOICE', 'Sales Invoice'), ('POS_ORDER', 'POS Order'), ('SUBSCRIPTION', 'Subscription'), ('OTHER', 'Other')], default='MANUAL', max_length=40)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency_code', models.CharField(default='SAR', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('external_checkout_id', models.CharField(blank=True, max_length=160)),
                ('external_payment_id', models.CharField(blank=True, max_length=160)),
                ('checkout_url', models.URLField(blank=True, max_length=1000)),
                ('idempotency_key', models.CharField(blank=True, max_length=160)),
                ('gateway_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_checkout_sessions', to='companies.company')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='payments.companypaymentgateway')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='payments.companypaymentmethod')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='payments.companypaymentterminal')),
            ],
            options={
                'verbose_name': 'Payment Checkout Session',
                'verbose_name_plural': 'Payment Checkout Sessions',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSettlementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_reference', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('currency_code', models.CharField(default='SAR', max_length=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settlement_batches', to='companies.company')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_batches', to='payments.companypaymentgateway')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_batches', to='payments.companypaymentmethod')),
            ],
            options={
                'verbose_name': 'Payment Settlement Batch',
                'verbose_name_plural': 'Payment Settlement Batches',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=120)),
                ('external_event_id', models.CharField(blank=True, max_length=180)),
                ('external_payment_id', models.CharField(blank=True, max_length=180)),
                ('idempotency_key', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('IGNORED', 'Ignored')], default='RECEIVED', max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('signature', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkout_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.paymentcheckoutsession')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_webhook_events', to='companies.company')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='payments.companypaymentgateway')),
            ],
            options={
                'verbose_name': 'Payment Webhook Event',
                'verbose_name_plural': 'Payment Webhook Events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSettlementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_payment_id', models.CharField(blank=True, max_length=180)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('INCLUDED', 'Included'), ('EXCLUDED', 'Excluded')], default='INCLUDED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.paymentsettlementbatch')),
                ('checkout_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_items', to='payments.paymentcheckoutsession')),
                ('webhook_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_items', to='payments.paymentwebhookevent')),
            ],
            options={
                'verbose_name': 'Payment Settlement Item',
                'verbose_name_plural': 'Payment Settlement Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentcheckoutsession',
            index=models.Index(fields=['company', 'status'], name='payments_pa_company_82d9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcheckoutsession',
            index=models.Index(fields=['company', 'gateway'], name='payments_pa_company_cc5736_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcheckoutsession',
            index=models.Index(fields=['company', 'payment_method'], name='payments_pa_company_6a90a9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcheckoutsession',
            index=models.Index(fields=['company', 'source_type', 'source_id'], name='payments_pa_company_25273e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcheckoutsession',
            index=models.Index(fields=['company', 'external_checkout_id'], name='payments_pa_company_b1b05d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcheckoutsession',
            index=models.Index(fields=['company', 'external_payment_id'], name='payments_pa_company_a9c241_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcheckoutsession',
            index=models.Index(fields=['company', 'idempotency_key'], name='payments_pa_company_8c9347_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsettlementbatch',
            index=models.Index(fields=['company', 'gateway'], name='payments_pa_company_01830e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsettlementbatch',
            index=models.Index(fields=['company', 'status'], name='payments_pa_company_badac8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsettlementbatch',
            index=models.Index(fields=['company', 'settlement_date'], name='payments_pa_company_934ee0_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentsettlementbatch',
            constraint=models.UniqueConstraint(fields=('company', 'settlement_reference'), name='unique_payment_settlement_reference_per_company'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['company', 'gateway'], name='payments_pa_company_6b540a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['company', 'status'], name='payments_pa_company_62c1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['company', 'event_type'], name='payments_pa_company_6e2398_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['company', 'external_event_id'], name='payments_pa_company_cd6b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['company', 'external_payment_id'], name='payments_pa_company_d7b96a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['company', 'idempotency_key'], name='payments_pa_company_612130_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsettlementitem',
            index=models.Index(fields=['batch', 'status'], name='payments_pa_batch_i_a97102_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsettlementitem',
            index=models.Index(fields=['external_payment_id'], name='payments_pa_externa_422216_idx'),
        ),
    ]
