# Generated by Django 6.0.6 on 2026-06-12 19:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('subscriptions', '0002_companysubscription_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('SUBSCRIPTION_INVOICE', 'Subscription invoice'), ('PAYMENT_RECEIPT', 'Payment receipt')], db_index=True, max_length=40, verbose_name='نوع المستند')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='السنة')),
                ('prefix', models.CharField(help_text='مثل PINV لفاتورة المنصة وPREC لإيصال الدفع.', max_length=20, verbose_name='بادئة الترقيم')),
                ('last_number', models.PositiveBigIntegerField(default=0, verbose_name='آخر رقم مستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'تسلسل مستند منصة',
                'verbose_name_plural': 'تسلسلات مستندات المنصة',
                'ordering': ['-year', 'document_type'],
                'indexes': [models.Index(fields=['document_type', 'year'], name='billing_seq_type_year_idx')],
                'constraints': [models.UniqueConstraint(fields=('document_type', 'year'), name='billing_seq_type_year_uniq'), models.CheckConstraint(condition=models.Q(('year__gte', 2000)), name='billing_seq_year_valid')],
            },
        ),
        migrations.CreateModel(
            name='PlatformBillingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('SUBSCRIPTION_INVOICE', 'Subscription invoice'), ('PAYMENT_RECEIPT', 'Payment receipt')], db_index=True, max_length=40, verbose_name='نوع المستند')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='ISSUED', max_length=20, verbose_name='حالة المستند')),
                ('document_number', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='رقم المستند')),
                ('sequence_number', models.PositiveBigIntegerField(verbose_name='الرقم التسلسلي')),
                ('sequence_year', models.PositiveSmallIntegerField(db_index=True, verbose_name='سنة التسلسل')),
                ('sequence_prefix', models.CharField(max_length=20, verbose_name='بادئة التسلسل')),
                ('currency_code', models.CharField(db_index=True, default='SAR', max_length=10, verbose_name='رمز العملة')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='المجموع قبل الخصم')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='قيمة الخصم')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='المبلغ الخاضع للضريبة')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='قيمة الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='إجمالي المستند')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='المبلغ المدفوع')),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='المبلغ المتبقي')),
                ('billing_reference', models.CharField(blank=True, db_index=True, max_length=160, verbose_name='مرجع الفوترة')),
                ('transaction_reference', models.CharField(blank=True, db_index=True, max_length=160, verbose_name='مرجع عملية الدفع')),
                ('payment_method', models.CharField(blank=True, db_index=True, help_text='وصف طريقة دفع اشتراك المنصة، ولا يرتبط بـ CompanyPaymentMethod.', max_length=80, verbose_name='طريقة الدفع')),
                ('seller_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot بيانات البائع')),
                ('buyer_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot بيانات المشتري')),
                ('subscription_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot بيانات الاشتراك')),
                ('plan_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot بيانات الباقة')),
                ('payment_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot بيانات الدفع')),
                ('printable_payload', models.JSONField(blank=True, default=dict, help_text='النسخة الثابتة التي تعتمد عليها الطباعة وتوليد PDF مستقبلًا.', verbose_name='بيانات الطباعة الثابتة')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('issue_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='تاريخ الإصدار')),
                ('issued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='وقت الإصدار')),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='وقت الدفع')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='وقت الإلغاء')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_platform_billing_documents', to=settings.AUTH_USER_MODEL, verbose_name='ألغي بواسطة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_billing_documents', to='companies.company', verbose_name='الشركة المستفيدة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platform_billing_documents', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('related_invoice', models.ForeignKey(blank=True, help_text='يستخدم في إيصال الدفع لربطه بفاتورة الاشتراك.', limit_choices_to={'document_type': 'SUBSCRIPTION_INVOICE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='billing.platformbillingdocument', verbose_name='الفاتورة المرتبطة')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_billing_documents', to='subscriptions.companysubscription', verbose_name='الاشتراك')),
            ],
            options={
                'verbose_name': 'مستند فوترة منصة',
                'verbose_name_plural': 'مستندات فوترة المنصة',
                'ordering': ['-issued_at', '-id'],
                'indexes': [models.Index(fields=['document_type', 'status'], name='billing_doc_type_status_idx'), models.Index(fields=['company', 'document_type'], name='billing_doc_company_type_idx'), models.Index(fields=['subscription', 'document_type'], name='billing_doc_sub_type_idx'), models.Index(fields=['issue_date', 'document_type'], name='billing_doc_date_type_idx'), models.Index(fields=['billing_reference'], name='billing_doc_bill_ref_idx'), models.Index(fields=['transaction_reference'], name='billing_doc_tx_ref_idx')],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'document_type'), name='billing_doc_sub_type_uniq'), models.UniqueConstraint(fields=('document_type', 'sequence_year', 'sequence_number'), name='billing_doc_seq_number_uniq'), models.CheckConstraint(condition=models.Q(('sequence_year__gte', 2000)), name='billing_doc_year_valid'), models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='billing_doc_subtotal_gte_zero'), models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='billing_doc_discount_gte_zero'), models.CheckConstraint(condition=models.Q(('taxable_amount__gte', 0)), name='billing_doc_taxable_gte_zero'), models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='billing_doc_tax_gte_zero'), models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='billing_doc_total_gte_zero'), models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='billing_doc_paid_gte_zero'), models.CheckConstraint(condition=models.Q(('balance_amount__gte', 0)), name='billing_doc_balance_gte_zero')],
            },
        ),
    ]
