# Generated by Django 6.0.6 on 2026-08-21 00:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('companies', '0005_seed_activity_profiles'),
        ('subscriptions', '0002_companysubscription_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(db_index=True, max_length=80, unique=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=160, unique=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('gateway', models.CharField(blank=True, db_index=True, max_length=60)),
                ('payment_method', models.CharField(blank=True, db_index=True, max_length=80)),
                ('gateway_payment_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('transaction_reference', models.CharField(blank=True, db_index=True, max_length=160)),
                ('billing_reference', models.CharField(blank=True, db_index=True, max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency_code', models.CharField(db_index=True, default='SAR', max_length=10)),
                ('failure_code', models.CharField(blank=True, max_length=100)),
                ('failure_message', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('provider_request_snapshot', models.JSONField(blank=True, default=dict)),
                ('provider_response_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('initiated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processing_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_platform_subscription_payments', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_subscription_payments', to='companies.company')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_platform_subscription_payments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platform_subscription_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_subscription_payments', to='billing.platformbillingdocument')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platform_subscription_payment_receipts', to='billing.platformbillingdocument')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_subscription_payments', to='subscriptions.companysubscription')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSubscriptionPaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_subscription_payment_events', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='billing.platformsubscriptionpayment')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='platformsubscriptionpayment',
            index=models.Index(fields=['company', 'status'], name='billing_pay_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsubscriptionpayment',
            index=models.Index(fields=['subscription', 'status'], name='billing_pay_sub_status_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsubscriptionpayment',
            index=models.Index(fields=['invoice', 'status'], name='billing_pay_invoice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsubscriptionpayment',
            index=models.Index(fields=['gateway', 'gateway_payment_id'], name='billing_pay_gateway_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='platformsubscriptionpayment',
            constraint=models.UniqueConstraint(fields=('subscription', 'attempt_number'), name='billing_pay_sub_attempt_uniq'),
        ),
        migrations.AddConstraint(
            model_name='platformsubscriptionpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='billing_pay_amount_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='platformsubscriptionpaymentevent',
            index=models.Index(fields=['payment', 'created_at'], name='billing_pay_event_time_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsubscriptionpaymentevent',
            index=models.Index(fields=['event_type', 'created_at'], name='billing_pay_event_type_idx'),
        ),
    ]
