# Generated by Django 6.0.6 on 2026-08-23 18:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_platform_subscription_payment'),
        ('companies', '0006_company_onboarding_lifecycle'),
        ('subscriptions', '0003_phase28_commercial_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSubscriptionRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_reference', models.CharField(db_index=True, max_length=80, unique=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=160, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('gateway', models.CharField(blank=True, db_index=True, max_length=60)),
                ('provider_refund_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency_code', models.CharField(db_index=True, default='SAR', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('failure_code', models.CharField(blank=True, max_length=100)),
                ('failure_message', models.TextField(blank=True)),
                ('provider_request_snapshot', models.JSONField(blank=True, default=dict)),
                ('provider_response_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('initiated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processing_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_subscription_refunds', to='companies.company')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_platform_subscription_refunds', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platform_subscription_refunds', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.platformsubscriptionpayment')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_subscription_refunds', to='subscriptions.companysubscription')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSubscriptionRefundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_subscription_refund_events', to=settings.AUTH_USER_MODEL)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='billing.platformsubscriptionrefund')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='platformsubscriptionrefund',
            index=models.Index(fields=['payment', 'status'], name='billing_refund_pay_status_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsubscriptionrefund',
            index=models.Index(fields=['company', 'status'], name='billing_refund_company_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsubscriptionrefund',
            index=models.Index(fields=['gateway', 'provider_refund_id'], name='billing_refund_provider_idx'),
        ),
        migrations.AddConstraint(
            model_name='platformsubscriptionrefund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='billing_refund_amount_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='platformsubscriptionrefundevent',
            index=models.Index(fields=['refund', 'created_at'], name='billing_refund_event_idx'),
        ),
    ]
