# Generated by Django 6.0.6 on 2026-08-23 22:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_phase28_commercial_refunds'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSubscriptionWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(db_index=True, max_length=30)),
                ('provider_event_id', models.CharField(blank=True, db_index=True, max_length=180)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=180)),
                ('event_fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('body_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('UNMATCHED', 'Unmatched')], db_index=True, default='RECEIVED', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='billing.platformsubscriptionpayment')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['gateway', 'status'], name='bill_wh_gw_status_idx'), models.Index(fields=['payment', 'status'], name='bill_wh_pay_status_idx'), models.Index(fields=['status', 'next_retry_at'], name='bill_wh_retry_idx'), models.Index(fields=['gateway', 'provider_payment_id'], name='bill_wh_provider_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='bill_wh_max_attempts_gte1')],
            },
        ),
    ]
