# Generated by Django 6.0.6 on 2026-08-23 22:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_phase29b_platform_webhook_reliability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(db_index=True, max_length=30)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=180)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('DISCREPANCY', 'Discrepancy'), ('ERROR', 'Error')], db_index=True, max_length=20)),
                ('local_status', models.CharField(blank=True, db_index=True, max_length=30)),
                ('provider_status', models.CharField(blank=True, db_index=True, max_length=30)),
                ('local_amount_minor', models.PositiveBigIntegerField(default=0)),
                ('provider_amount_minor', models.PositiveBigIntegerField(blank=True, null=True)),
                ('local_currency', models.CharField(blank=True, max_length=10)),
                ('provider_currency', models.CharField(blank=True, max_length=10)),
                ('local_reference', models.CharField(blank=True, max_length=180)),
                ('provider_reference', models.CharField(blank=True, max_length=180)),
                ('checks', models.JSONField(blank=True, default=dict)),
                ('discrepancies', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('provider_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('reconciled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='billing.platformsubscriptionpayment')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_payment_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reconciled_at', '-id'],
                'indexes': [models.Index(fields=['gateway', 'status'], name='bill_rec_gw_status_idx'), models.Index(fields=['payment', 'reconciled_at'], name='bill_rec_pay_time_idx'), models.Index(fields=['status', 'reconciled_at'], name='bill_rec_status_time_idx'), models.Index(fields=['gateway', 'provider_payment_id'], name='bill_rec_provider_idx')],
            },
        ),
    ]
