import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0005_phase29c_platform_payment_reconciliation",
        ),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSubscriptionAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjustment_reference",
                    models.CharField(
                        db_index=True,
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        db_index=True,
                        max_length=160,
                        unique=True,
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("CREDIT", "Credit"),
                            ("DEBIT", "Debit"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        db_index=True,
                        default="POSTED",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        db_index=True,
                        default="SAR",
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    "accounting_reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=160,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "reversed_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="platform_subscription_adjustments",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_platform_subscription_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="billing.platformsubscriptionpayment",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_platform_subscription_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="platform_subscription_adjustments",
                        to="subscriptions.companysubscription",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-posted_at",
                    "-id",
                ],
            },
        ),
        migrations.CreateModel(
            name="PlatformSubscriptionAdjustmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        max_length=60,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_subscription_adjustment_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "adjustment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="billing.platformsubscriptionadjustment",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "created_at",
                    "id",
                ],
            },
        ),
        migrations.AddIndex(
            model_name="platformsubscriptionadjustment",
            index=models.Index(
                fields=[
                    "payment",
                    "status",
                ],
                name="bill_adj_pay_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="platformsubscriptionadjustment",
            index=models.Index(
                fields=[
                    "company",
                    "status",
                ],
                name="bill_adj_company_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="platformsubscriptionadjustment",
            index=models.Index(
                fields=[
                    "subscription",
                    "status",
                ],
                name="bill_adj_sub_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformsubscriptionadjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount__gt", 0)
                ),
                name="bill_adj_amount_gt_zero",
            ),
        ),
    ]
