# Generated by Django 6.0.6 on 2026-06-06 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_branch_companysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('BOTH', 'Customer and Supplier'), ('OTHER', 'Other')], db_index=True, default='CUSTOMER', max_length=30, verbose_name='Party type')),
                ('party_kind', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZATION', 'Organization')], db_index=True, default='INDIVIDUAL', max_length=30, verbose_name='Party kind')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=30, verbose_name='Status')),
                ('code', models.CharField(blank=True, db_index=True, help_text='Unique party code inside the same company when provided.', max_length=60, verbose_name='Code')),
                ('display_name', models.CharField(db_index=True, max_length=255, verbose_name='Display name')),
                ('legal_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Legal name')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Contact person')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Mobile')),
                ('whatsapp_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='WhatsApp number')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('commercial_registration', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Commercial registration')),
                ('vat_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='VAT number')),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='National ID / Iqama')),
                ('country', models.CharField(default='Saudi Arabia', max_length=100, verbose_name='Country')),
                ('city', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='City')),
                ('district', models.CharField(blank=True, max_length=120, verbose_name='District')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Street')),
                ('building_number', models.CharField(blank=True, max_length=50, verbose_name='Building number')),
                ('additional_number', models.CharField(blank=True, max_length=50, verbose_name='Additional number')),
                ('postal_code', models.CharField(blank=True, max_length=50, verbose_name='Postal code')),
                ('short_address', models.CharField(blank=True, max_length=100, verbose_name='Saudi short address')),
                ('address_line', models.TextField(blank=True, verbose_name='Address line')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Credit limit')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Positive means party owes the company. Negative means company owes the party.', max_digits=14, verbose_name='Opening balance')),
                ('opening_balance_date', models.DateField(blank=True, null=True, verbose_name='Opening balance date')),
                ('payment_terms_days', models.PositiveIntegerField(default=0, verbose_name='Payment terms days')),
                ('tax_exempt', models.BooleanField(db_index=True, default=False, verbose_name='Tax exempt')),
                ('blocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Blocked at')),
                ('blocked_reason', models.TextField(blank=True, verbose_name='Blocked reason')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('branch', models.ForeignKey(blank=True, help_text='Optional branch. Must belong to the same company.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_parties', to='companies.branch', verbose_name='Branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_parties', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_business_parties', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_business_parties', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Business party',
                'verbose_name_plural': 'Business parties',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'party_type', 'status'], name='parties_bus_company_0bb87d_idx'), models.Index(fields=['company', 'party_kind', 'status'], name='parties_bus_company_0dd53a_idx'), models.Index(fields=['company', 'display_name'], name='parties_bus_company_a46c5c_idx'), models.Index(fields=['company', 'legal_name'], name='parties_bus_company_6995ab_idx'), models.Index(fields=['company', 'phone'], name='parties_bus_company_2e6324_idx'), models.Index(fields=['company', 'mobile'], name='parties_bus_company_f45fce_idx'), models.Index(fields=['company', 'email'], name='parties_bus_company_1caf91_idx'), models.Index(fields=['company', 'vat_number'], name='parties_bus_company_c937cf_idx'), models.Index(fields=['company', 'commercial_registration'], name='parties_bus_company_33cac3_idx'), models.Index(fields=['company', 'city'], name='parties_bus_company_21d7e2_idx'), models.Index(fields=['branch', 'status'], name='parties_bus_branch__24ad0b_idx'), models.Index(fields=['created_at'], name='parties_bus_created_c895c3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('company', 'code'), name='unique_business_party_code_per_company')],
            },
        ),
    ]
