# Generated by Django 6.0.6 on 2026-06-07 12:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('companies', '0003_branch_companysettings'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('bill_number', models.CharField(db_index=True, help_text='Unique purchase bill number inside the same company.', max_length=80, verbose_name='Bill number')),
                ('supplier_bill_number', models.CharField(blank=True, db_index=True, default='', help_text='Original supplier invoice/bill number when available.', max_length=100, verbose_name='Supplier bill number')),
                ('bill_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Bill date')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Due date')),
                ('currency_code', models.CharField(default='SAR', max_length=10, verbose_name='Currency code')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount amount')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxable amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total amount')),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Posted at')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cancelled at')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name='Cancellation reason')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('branch', models.ForeignKey(blank=True, help_text='Optional branch. Must belong to the same company.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_bills', to='companies.branch', verbose_name='Branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_purchase_bills', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_bills', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_bills', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_purchase_bills', to=settings.AUTH_USER_MODEL, verbose_name='Posted by')),
                ('supplier', models.ForeignKey(help_text='Supplier must belong to the same company and be supplier or both.', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bills', to='parties.businessparty', verbose_name='Supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_purchase_bills', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Purchase bill',
                'verbose_name_plural': 'Purchase bills',
                'ordering': ['-bill_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Line number')),
                ('item_code_snapshot', models.CharField(blank=True, default='', max_length=80, verbose_name='Item code snapshot')),
                ('item_name_snapshot', models.CharField(max_length=255, verbose_name='Item name snapshot')),
                ('item_name_ar_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Item Arabic name snapshot')),
                ('item_name_en_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Item English name snapshot')),
                ('unit_name_snapshot', models.CharField(blank=True, default='', max_length=120, verbose_name='Unit name snapshot')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit price')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount amount')),
                ('taxable', models.BooleanField(db_index=True, default=True, verbose_name='Taxable')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax rate')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal amount')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxable amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total amount')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasebill', verbose_name='Purchase bill')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_bill_items', to='companies.company', verbose_name='Company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bill_items', to='catalog.catalogitem', verbose_name='Catalog item')),
            ],
            options={
                'verbose_name': 'Purchase bill item',
                'verbose_name_plural': 'Purchase bill items',
                'ordering': ['bill_id', 'line_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['company', 'status'], name='purchases_p_company_ca0763_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['company', 'bill_date'], name='purchases_p_company_a64c60_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['company', 'due_date'], name='purchases_p_company_b97e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['company', 'supplier'], name='purchases_p_company_c48d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['company', 'branch'], name='purchases_p_company_39e03d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['company', 'created_at'], name='purchases_p_company_4af2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['supplier', 'status'], name='purchases_p_supplie_5bfeac_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['branch', 'status'], name='purchases_p_branch__de3bba_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['posted_at'], name='purchases_p_posted__12bb3e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['cancelled_at'], name='purchases_p_cancell_eb8ad6_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasebill',
            constraint=models.UniqueConstraint(fields=('company', 'bill_number'), name='unique_purchase_bill_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='purchasebill',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_bill_number', ''), _negated=True), fields=('company', 'supplier', 'supplier_bill_number'), name='unique_supplier_bill_number_per_supplier_company'),
        ),
        migrations.AddIndex(
            model_name='purchasebillitem',
            index=models.Index(fields=['company', 'item'], name='purchases_p_company_dc260e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebillitem',
            index=models.Index(fields=['company', 'created_at'], name='purchases_p_company_d274f7_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebillitem',
            index=models.Index(fields=['bill', 'line_number'], name='purchases_p_bill_id_f975e8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebillitem',
            index=models.Index(fields=['item', 'created_at'], name='purchases_p_item_id_059ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebillitem',
            index=models.Index(fields=['taxable'], name='purchases_p_taxable_244b46_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasebillitem',
            constraint=models.UniqueConstraint(fields=('bill', 'line_number'), name='unique_purchase_bill_item_line_per_bill'),
        ),
    ]
