# Generated by Django 6.0.6 on 2026-06-09 07:41

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_branch_companysettings'),
        ('parties', '0001_initial'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Balance due'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Updated by treasury supplier payment allocation services.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Paid amount'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially paid'), ('PAID', 'Paid')], db_index=True, default='UNPAID', max_length=20, verbose_name='Payment status'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['company', 'payment_status'], name='purchases_p_company_8b3036_idx'),
        ),
    ]
