# Generated by Django 6.0.6 on 2026-06-13 20:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('parties', '0001_initial'),
        ('purchases', '0002_purchasebill_balance_due_purchasebill_paid_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(db_index=True, max_length=80, verbose_name='Return number')),
                ('return_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Return date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged'), ('DEFECTIVE', 'Defective'), ('WRONG_ITEM', 'Wrong item'), ('EXCESS_QUANTITY', 'Excess quantity'), ('QUALITY_ISSUE', 'Quality issue'), ('SUPPLIER_REQUEST', 'Supplier request'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=40, verbose_name='Reason')),
                ('reason_details', models.TextField(blank=True, default='', verbose_name='Reason details')),
                ('currency_code', models.CharField(default='SAR', max_length=10, verbose_name='Currency code')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('confirmed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='purchases.purchasebill', verbose_name='Purchase bill')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns', to='companies.branch', verbose_name='Branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='companies.company', verbose_name='Company')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='parties.businessparty', verbose_name='Supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_purchase_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-return_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(db_index=True, default=1)),
                ('item_code_snapshot', models.CharField(blank=True, default='', max_length=80)),
                ('item_name_snapshot', models.CharField(max_length=255)),
                ('item_name_ar_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('item_name_en_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('unit_name_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('taxable', models.BooleanField(db_index=True, default=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('condition_notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_items', to='purchases.purchasebillitem')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_return_items', to='companies.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_items', to='catalog.catalogitem')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasereturn')),
            ],
            options={
                'ordering': ['purchase_return_id', 'line_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['company', 'status'], name='purchases_p_company_dbb2b4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['company', 'return_date'], name='purchases_p_company_469d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['company', 'supplier'], name='purchases_p_company_af6c45_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['company', 'bill'], name='purchases_p_company_01a791_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['supplier', 'status'], name='purchases_p_supplie_5fc43f_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.UniqueConstraint(fields=('company', 'return_number'), name='unique_purchase_return_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnitem',
            index=models.Index(fields=['company', 'item'], name='purchases_p_company_ac49aa_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnitem',
            index=models.Index(fields=['company', 'bill_item'], name='purchases_p_company_76579e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnitem',
            index=models.Index(fields=['purchase_return', 'line_number'], name='purchases_p_purchas_16b735_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnitem',
            constraint=models.UniqueConstraint(fields=('purchase_return', 'line_number'), name='unique_purchase_return_item_line'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnitem',
            constraint=models.UniqueConstraint(fields=('purchase_return', 'bill_item'), name='unique_purchase_return_bill_item'),
        ),
    ]
