# Generated by Django 6.0.6 on 2026-06-13 21:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('parties', '0001_initial'),
        ('purchases', '0003_purchasereturn_purchasereturnitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_note_number', models.CharField(db_index=True, max_length=80, verbose_name='Debit note number')),
                ('supplier_reference', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Supplier reference')),
                ('debit_note_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Debit note date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('currency_code', models.CharField(default='SAR', max_length=10, verbose_name='Currency code')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount amount')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxable amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total amount')),
                ('applied_to_bill_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount used to reduce the linked purchase bill balance.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Applied to bill amount')),
                ('supplier_credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining debit note amount held as supplier credit.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Supplier credit amount')),
                ('issued_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Issued at')),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Posted at')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cancelled at')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name='Cancellation reason')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_debit_notes', to='purchases.purchasebill', verbose_name='Purchase bill')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_debit_notes', to='companies.branch', verbose_name='Branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_supplier_debit_notes', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_debit_notes', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_debit_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_supplier_debit_notes', to=settings.AUTH_USER_MODEL, verbose_name='Issued by')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_supplier_debit_notes', to=settings.AUTH_USER_MODEL, verbose_name='Posted by')),
                ('purchase_return', models.OneToOneField(blank=True, help_text='Optional source purchase return. One purchase return can create one debit note.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_note', to='purchases.purchasereturn', verbose_name='Purchase return')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_debit_notes', to='parties.businessparty', verbose_name='Supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_supplier_debit_notes', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Supplier debit note',
                'verbose_name_plural': 'Supplier debit notes',
                'ordering': ['-debit_note_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDebitNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Line number')),
                ('item_code_snapshot', models.CharField(blank=True, default='', max_length=80)),
                ('item_name_snapshot', models.CharField(max_length=255)),
                ('item_name_ar_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('item_name_en_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('unit_name_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('taxable', models.BooleanField(db_index=True, default=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_debit_note_items', to='purchases.purchasebillitem', verbose_name='Purchase bill item')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_debit_note_items', to='companies.company', verbose_name='Company')),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.supplierdebitnote', verbose_name='Supplier debit note')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_debit_note_items', to='catalog.catalogitem', verbose_name='Catalog item')),
                ('purchase_return_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_note_item', to='purchases.purchasereturnitem', verbose_name='Purchase return item')),
            ],
            options={
                'verbose_name': 'Supplier debit note item',
                'verbose_name_plural': 'Supplier debit note items',
                'ordering': ['debit_note_id', 'line_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='supplierdebitnote',
            index=models.Index(fields=['company', 'status'], name='purchases_s_company_723324_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdebitnote',
            index=models.Index(fields=['company', 'debit_note_date'], name='purchases_s_company_4d09de_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdebitnote',
            index=models.Index(fields=['company', 'supplier'], name='purchases_s_company_02746a_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdebitnote',
            index=models.Index(fields=['company', 'bill'], name='purchases_s_company_6f718a_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdebitnote',
            index=models.Index(fields=['supplier', 'status'], name='purchases_s_supplie_3424e6_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdebitnote',
            index=models.Index(fields=['posted_at'], name='purchases_s_posted__981f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdebitnote',
            index=models.Index(fields=['cancelled_at'], name='purchases_s_cancell_c23947_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierdebitnote',
            constraint=models.UniqueConstraint(fields=('company', 'debit_note_number'), name='unique_supplier_debit_note_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='supplierdebitnoteitem',
            index=models.Index(fields=['company', 'item'], name='purchases_s_company_c509bc_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdebitnoteitem',
            index=models.Index(fields=['company', 'bill_item'], name='purchases_s_company_cc3ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdebitnoteitem',
            index=models.Index(fields=['debit_note', 'line_number'], name='purchases_s_debit_n_733486_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierdebitnoteitem',
            constraint=models.UniqueConstraint(fields=('debit_note', 'line_number'), name='unique_supplier_debit_note_item_line'),
        ),
        migrations.AddConstraint(
            model_name='supplierdebitnoteitem',
            constraint=models.UniqueConstraint(fields=('debit_note', 'bill_item'), name='unique_supplier_debit_note_bill_item'),
        ),
    ]
