# Generated by Django 6.0.6 on 2026-06-14 10:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('inventory', '0001_initial'),
        ('parties', '0001_initial'),
        ('purchases', '0004_supplierdebitnote_supplierdebitnoteitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='debit_note_applied_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total posted supplier debit note amount applied against this purchase bill.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Debit note applied amount'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='stock_movement',
            field=models.OneToOneField(blank=True, help_text='Posted stock issue created for this purchase return item.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_item', to='inventory.stockmovement', verbose_name='Stock movement'),
        ),
        migrations.CreateModel(
            name='SupplierCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CONSUMED', 'Consumed'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('currency_code', models.CharField(default='SAR', max_length=10)),
                ('original_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_credits', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_credits', to=settings.AUTH_USER_MODEL)),
                ('debit_note', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_credit', to='purchases.supplierdebitnote')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_credits', to='parties.businessparty')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_supplier_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', 'supplier'], name='purchases_s_company_b20f5c_idx'), models.Index(fields=['company', 'status'], name='purchases_s_company_0bb2fb_idx')],
            },
        ),
    ]
