# Generated by Django 6.0.6 on 2026-06-14 13:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('parties', '0001_initial'),
        ('purchases', '0006_purchasereceipt_purchasereceiptitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=80, verbose_name='Order number')),
                ('supplier_reference', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Supplier reference')),
                ('order_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Order date')),
                ('expected_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Expected delivery date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PARTIALLY_RECEIVED', 'Partially received'), ('RECEIVED', 'Received'), ('BILLED', 'Billed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30, verbose_name='Status')),
                ('currency_code', models.CharField(default='SAR', max_length=10, verbose_name='Currency code')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount amount')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxable amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total amount')),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Approved at')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cancelled at')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name='Cancellation reason')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='companies.branch', verbose_name='Branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='parties.businessparty', verbose_name='Supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Purchase order',
                'verbose_name_plural': 'Purchase orders',
                'ordering': ['-order_date', '-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Optional source purchase order used to create this supplier bill.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='purchases.purchaseorder', verbose_name='Purchase order'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Line number')),
                ('item_code_snapshot', models.CharField(blank=True, default='', max_length=80)),
                ('item_name_snapshot', models.CharField(max_length=255)),
                ('item_name_ar_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('item_name_en_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('unit_name_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('taxable', models.BooleanField(db_index=True, default=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='companies.company', verbose_name='Company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='catalog.catalogitem', verbose_name='Catalog item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder', verbose_name='Purchase order')),
            ],
            options={
                'ordering': ['order_id', 'line_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, help_text='Optional source purchase order line.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bill_items', to='purchases.purchaseorderitem', verbose_name='Purchase order item'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company', 'status'], name='purchases_p_company_643d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company', 'order_date'], name='purchases_p_company_46cbf4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company', 'expected_date'], name='purchases_p_company_e46ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company', 'supplier'], name='purchases_p_company_75e86f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company', 'branch'], name='purchases_p_company_4acf88_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='purchases_p_supplie_1eb951_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('company', 'order_number'), name='unique_purchase_order_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['company', 'item'], name='purchases_p_company_1ef10a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['order', 'line_number'], name='purchases_p_order_i_86c5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['company', 'created_at'], name='purchases_p_company_8898fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'line_number'), name='unique_purchase_order_item_line'),
        ),
    ]
