# Generated by Django 6.0.6 on 2026-06-15 12:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('purchases', '0007_purchaseorder_purchasebill_purchase_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(db_index=True, max_length=80, verbose_name='Request number')),
                ('request_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Request date')),
                ('required_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Required date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PARTIALLY_CONVERTED', 'Partially converted'), ('CONVERTED', 'Converted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30, verbose_name='Status')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=20, verbose_name='Priority')),
                ('purpose', models.CharField(blank=True, default='', max_length=255, verbose_name='Purpose')),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Submitted at')),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Approved at')),
                ('rejected_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Rejected at')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Rejection reason')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cancelled at')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name='Cancellation reason')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='companies.branch', verbose_name='Branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Rejected by')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Submitted by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Purchase request',
                'verbose_name_plural': 'Purchase requests',
                'ordering': ['-request_date', '-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchases.purchaserequest', verbose_name='Purchase request'),
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Line number')),
                ('item_code_snapshot', models.CharField(blank=True, default='', max_length=80)),
                ('item_name_snapshot', models.CharField(max_length=255)),
                ('item_name_ar_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('item_name_en_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('unit_name_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantity')),
                ('suggested_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Suggested unit price')),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_items', to='companies.company', verbose_name='Company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_items', to='catalog.catalogitem', verbose_name='Catalog item')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaserequest', verbose_name='Purchase request')),
            ],
            options={
                'ordering': ['request_id', 'line_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='purchases.purchaserequestitem', verbose_name='Purchase request item'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['company', 'status'], name='purchases_p_company_f4e9a0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['company', 'request_date'], name='purchases_p_company_4e0b40_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['company', 'required_date'], name='purchases_p_company_05095a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['company', 'branch'], name='purchases_p_company_fd4fee_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['company', 'priority'], name='purchases_p_company_8cc1f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.UniqueConstraint(fields=('company', 'request_number'), name='unique_purchase_request_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestitem',
            index=models.Index(fields=['company', 'item'], name='purchases_p_company_210b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestitem',
            index=models.Index(fields=['request', 'line_number'], name='purchases_p_request_48f493_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestitem',
            index=models.Index(fields=['company', 'created_at'], name='purchases_p_company_eceb4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestitem',
            constraint=models.UniqueConstraint(fields=('request', 'line_number'), name='unique_purchase_request_item_line'),
        ),
    ]
