# Generated by Django 6.0.6 on 2026-06-10 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_branch_companysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(db_index=True, help_text='Unique employee number inside the same company.', max_length=50, verbose_name='Employee number')),
                ('first_name', models.CharField(db_index=True, max_length=150, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Middle name')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Last name')),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Display name')),
                ('job_title', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Job title')),
                ('department_name', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Department name')),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERN', 'Intern')], db_index=True, default='FULL_TIME', max_length=30, verbose_name='Employment type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On leave'), ('TERMINATED', 'Terminated')], db_index=True, default='ACTIVE', max_length=30, verbose_name='Status')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('hire_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Hire date')),
                ('termination_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Termination date')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Mobile')),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='National ID / Iqama')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='companies.branch', verbose_name='Branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hr_employees', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_hr_employees', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='User account')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['company_id', 'employee_number'],
                'indexes': [models.Index(fields=['company', 'status', 'is_active'], name='hr_employee_company_aefdea_idx'), models.Index(fields=['company', 'branch', 'status'], name='hr_employee_company_a74409_idx'), models.Index(fields=['company', 'department_name'], name='hr_employee_company_8d2531_idx'), models.Index(fields=['company', 'job_title'], name='hr_employee_company_b43226_idx'), models.Index(fields=['company', 'hire_date'], name='hr_employee_company_c4107c_idx'), models.Index(fields=['employee_number'], name='hr_employee_employe_725225_idx'), models.Index(fields=['national_id'], name='hr_employee_nationa_e4f2bc_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'employee_number'), name='unique_employee_number_per_company'), models.UniqueConstraint(condition=models.Q(('national_id', ''), _negated=True), fields=('company', 'national_id'), name='unique_employee_national_id_per_company')],
            },
        ),
    ]
