# Generated by Django 6.0.6 on 2026-06-10 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_branch_companysettings'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True, help_text='Local work date based on check-in time.', verbose_name='Work date')),
                ('check_in_at', models.DateTimeField(db_index=True, verbose_name='Check-in at')),
                ('check_out_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Check-out at')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('MISSING_CHECK_OUT', 'Missing check-out'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=30, verbose_name='Status')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('WEB', 'Web'), ('MOBILE', 'Mobile'), ('DEVICE', 'Device'), ('API', 'API')], db_index=True, default='MANUAL', max_length=30, verbose_name='Source')),
                ('total_minutes', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Total minutes')),
                ('check_in_note', models.TextField(blank=True, verbose_name='Check-in note')),
                ('check_out_note', models.TextField(blank=True, verbose_name='Check-out note')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='companies.branch', verbose_name='Branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hr_attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.employee', verbose_name='Employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_hr_attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Attendance record',
                'verbose_name_plural': 'Attendance records',
                'ordering': ['company_id', '-work_date', '-check_in_at'],
                'indexes': [models.Index(fields=['company', 'work_date'], name='hr_attendan_company_705868_idx'), models.Index(fields=['company', 'employee', 'work_date'], name='hr_attendan_company_a7ed18_idx'), models.Index(fields=['company', 'branch', 'work_date'], name='hr_attendan_company_f720a6_idx'), models.Index(fields=['company', 'status'], name='hr_attendan_company_9a04d7_idx'), models.Index(fields=['employee', 'status'], name='hr_attendan_employe_9309e4_idx'), models.Index(fields=['check_in_at'], name='hr_attendan_check_i_7f93c8_idx'), models.Index(fields=['check_out_at'], name='hr_attendan_check_o_9c9f6c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('check_out_at__isnull', True), models.Q(('status', 'CANCELLED'), _negated=True)), fields=('employee',), name='unique_open_attendance_per_employee')],
            },
        ),
    ]
