# Generated by Django 6.0.6 on 2026-06-10 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_branch_companysettings'),
        ('hr', '0003_leavetype_leaverequest_leavebalance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12, verbose_name='Basic salary')),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Housing allowance')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Transport allowance')),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Other allowance')),
                ('currency', models.CharField(db_index=True, default='SAR', max_length=10, verbose_name='Currency')),
                ('bank_name', models.CharField(blank=True, max_length=150, verbose_name='Bank name')),
                ('bank_account_number', models.CharField(blank=True, max_length=100, verbose_name='Bank account number')),
                ('iban', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='IBAN')),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True, verbose_name='Effective from')),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True, verbose_name='Effective to')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_salary_profiles', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_salary_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_profiles', to='hr.employee', verbose_name='Employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_employee_salary_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Employee salary profile',
                'verbose_name_plural': 'Employee salary profiles',
                'ordering': ['company_id', 'employee__employee_number', '-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Name')),
                ('year', models.PositiveIntegerField(db_index=True, verbose_name='Year')),
                ('month', models.PositiveSmallIntegerField(db_index=True, verbose_name='Month')),
                ('start_date', models.DateField(db_index=True, verbose_name='Start date')),
                ('end_date', models.DateField(db_index=True, verbose_name='End date')),
                ('payment_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Payment date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=30, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_periods', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payroll_periods', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Payroll period',
                'verbose_name_plural': 'Payroll periods',
                'ordering': ['company_id', '-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.CharField(db_index=True, max_length=50, verbose_name='Run number')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Name')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30, verbose_name='Status')),
                ('total_employees', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Total employees')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total earnings')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total deductions')),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Net pay')),
                ('calculated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Calculated at')),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Approved at')),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Posted at')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cancelled at')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_runs', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_payroll_runs', to=settings.AUTH_USER_MODEL, verbose_name='Calculated by')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_payroll_runs', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_runs', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='hr.payrollperiod', verbose_name='Payroll period')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_payroll_runs', to=settings.AUTH_USER_MODEL, verbose_name='Posted by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payroll_runs', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Payroll run',
                'verbose_name_plural': 'Payroll runs',
                'ordering': ['company_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payslip_number', models.CharField(db_index=True, max_length=50, verbose_name='Payslip number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30, verbose_name='Status')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Basic salary')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total earnings')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total deductions')),
                ('net_pay', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=14, verbose_name='Net pay')),
                ('currency', models.CharField(db_index=True, default='SAR', max_length=10, verbose_name='Currency')),
                ('calculated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Calculated at')),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Approved at')),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Paid at')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cancelled at')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payslips', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_payslips', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payslips', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.employee', verbose_name='Employee')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_payslips', to=settings.AUTH_USER_MODEL, verbose_name='Paid by')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.payrollrun', verbose_name='Payroll run')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.payrollperiod', verbose_name='Payroll period')),
                ('salary_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='hr.employeesalaryprofile', verbose_name='Salary profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payslips', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'ordering': ['company_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Name')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Code')),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], db_index=True, default='EARNING', max_length=30, verbose_name='Component type')),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed'), ('PERCENTAGE', 'Percentage')], db_index=True, default='FIXED', max_length=30, verbose_name='Calculation type')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Fixed amount')),
                ('percentage', models.DecimalField(decimal_places=4, default=0, help_text='Percentage value used when calculation type is percentage.', max_digits=7, verbose_name='Percentage')),
                ('is_taxable', models.BooleanField(db_index=True, default=True, verbose_name='Taxable')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sort order')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_components', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_salary_components', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Salary component',
                'verbose_name_plural': 'Salary components',
                'ordering': ['company_id', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayslipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Name')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Code')),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], db_index=True, max_length=30, verbose_name='Component type')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Amount')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip_items', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payslip_items', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hr.payslip', verbose_name='Payslip')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payslip_items', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslip_items', to='hr.salarycomponent', verbose_name='Salary component')),
            ],
            options={
                'verbose_name': 'Payslip item',
                'verbose_name_plural': 'Payslip items',
                'ordering': ['company_id', 'payslip_id', 'component_type', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='employeesalaryprofile',
            index=models.Index(fields=['company', 'employee', 'is_active'], name='hr_employee_company_36cef6_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalaryprofile',
            index=models.Index(fields=['company', 'effective_from'], name='hr_employee_company_3610f6_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalaryprofile',
            index=models.Index(fields=['company', 'currency'], name='hr_employee_company_3edbbc_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalaryprofile',
            index=models.Index(fields=['iban'], name='hr_employee_iban_0bf48b_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeesalaryprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'employee'), name='unique_active_salary_profile_per_employee'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['company', 'year', 'month'], name='hr_payrollp_company_0a33e7_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['company', 'status'], name='hr_payrollp_company_d6fb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['company', 'start_date', 'end_date'], name='hr_payrollp_company_0571eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(fields=('company', 'year', 'month'), name='unique_payroll_period_per_company_month'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['company', 'status'], name='hr_payrollr_company_53f641_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['company', 'period'], name='hr_payrollr_company_380b74_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['company', 'run_number'], name='hr_payrollr_company_d19237_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['calculated_at'], name='hr_payrollr_calcula_dfd7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['approved_at'], name='hr_payrollr_approve_608414_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('company', 'run_number'), name='unique_payroll_run_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('company', 'period'), name='unique_payroll_run_per_company_period'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['company', 'status'], name='hr_payslip_company_2449fc_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['company', 'period'], name='hr_payslip_company_f085e1_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['company', 'employee'], name='hr_payslip_company_bde651_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['company', 'payroll_run'], name='hr_payslip_company_833cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['payslip_number'], name='hr_payslip_payslip_f287bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('company', 'payslip_number'), name='unique_payslip_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('company', 'payroll_run', 'employee'), name='unique_payslip_per_run_employee'),
        ),
        migrations.AddIndex(
            model_name='salarycomponent',
            index=models.Index(fields=['company', 'code'], name='hr_salaryco_company_426b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='salarycomponent',
            index=models.Index(fields=['company', 'component_type'], name='hr_salaryco_company_69affb_idx'),
        ),
        migrations.AddIndex(
            model_name='salarycomponent',
            index=models.Index(fields=['company', 'is_active'], name='hr_salaryco_company_928e5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='salarycomponent',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_salary_component_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='payslipitem',
            index=models.Index(fields=['company', 'payslip'], name='hr_payslipi_company_b17163_idx'),
        ),
        migrations.AddIndex(
            model_name='payslipitem',
            index=models.Index(fields=['company', 'component_type'], name='hr_payslipi_company_2a50b4_idx'),
        ),
        migrations.AddIndex(
            model_name='payslipitem',
            index=models.Index(fields=['company', 'code'], name='hr_payslipi_company_682ef3_idx'),
        ),
    ]
