# Generated by Django 6.0.6 on 2026-06-11 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_branch_companysettings'),
        ('hr', '0004_employeesalaryprofile_payrollperiod_payrollrun_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Name')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('max_score', models.DecimalField(decimal_places=2, default=5, max_digits=6, verbose_name='Maximum score')),
                ('weight', models.DecimalField(decimal_places=4, default=0, help_text='Weight percentage used in total performance score.', max_digits=7, verbose_name='Weight')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sort order')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_criteria', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_performance_criteria', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_performance_criteria', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Performance criterion',
                'verbose_name_plural': 'Performance criteria',
                'ordering': ['company_id', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Name')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Code')),
                ('start_date', models.DateField(db_index=True, verbose_name='Start date')),
                ('end_date', models.DateField(db_index=True, verbose_name='End date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_cycles', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_performance_cycles', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_performance_cycles', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Performance cycle',
                'verbose_name_plural': 'Performance cycles',
                'ordering': ['company_id', '-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30, verbose_name='Status')),
                ('review_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Review date')),
                ('overall_score', models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=8, verbose_name='Overall score')),
                ('final_rating', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Final rating')),
                ('employee_comments', models.TextField(blank=True, verbose_name='Employee comments')),
                ('reviewer_comments', models.TextField(blank=True, verbose_name='Reviewer comments')),
                ('manager_comments', models.TextField(blank=True, verbose_name='Manager comments')),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Submitted at')),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Approved at')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cancelled at')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_performance_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_performance_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_performance_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_reviews', to='hr.employee', verbose_name='Employee')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_performance_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_performance_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='hr.performancecycle', verbose_name='Performance cycle')),
            ],
            options={
                'verbose_name': 'Employee performance review',
                'verbose_name_plural': 'Employee performance reviews',
                'ordering': ['company_id', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('target_value', models.CharField(blank=True, max_length=150, verbose_name='Target value')),
                ('actual_value', models.CharField(blank=True, max_length=150, verbose_name='Actual value')),
                ('progress_percentage', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=6, verbose_name='Progress percentage')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=30, verbose_name='Priority')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Start date')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Due date')),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Completed at')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cancelled at')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_goals', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_goals', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_goals', to='hr.employee', verbose_name='Employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_employee_goals', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='hr.performancecycle', verbose_name='Performance cycle')),
            ],
            options={
                'verbose_name': 'Employee goal',
                'verbose_name_plural': 'Employee goals',
                'ordering': ['company_id', 'employee_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Score')),
                ('weight', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='Weight')),
                ('weighted_score', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Weighted score')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_review_scores', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_performance_review_scores', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_scores', to='hr.performancecriterion', verbose_name='Performance criterion')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='hr.employeeperformancereview', verbose_name='Performance review')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_performance_review_scores', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Performance review score',
                'verbose_name_plural': 'Performance review scores',
                'ordering': ['company_id', 'review_id', 'criterion__sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='performancecriterion',
            index=models.Index(fields=['company', 'code'], name='hr_performa_company_f26c80_idx'),
        ),
        migrations.AddIndex(
            model_name='performancecriterion',
            index=models.Index(fields=['company', 'is_active'], name='hr_performa_company_a23c10_idx'),
        ),
        migrations.AddIndex(
            model_name='performancecriterion',
            index=models.Index(fields=['company', 'sort_order'], name='hr_performa_company_13b01d_idx'),
        ),
        migrations.AddConstraint(
            model_name='performancecriterion',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_perf_criterion_code_company'),
        ),
        migrations.AddIndex(
            model_name='performancecycle',
            index=models.Index(fields=['company', 'code'], name='hr_performa_company_f38bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='performancecycle',
            index=models.Index(fields=['company', 'status'], name='hr_performa_company_4ddd50_idx'),
        ),
        migrations.AddIndex(
            model_name='performancecycle',
            index=models.Index(fields=['company', 'start_date', 'end_date'], name='hr_performa_company_815d2a_idx'),
        ),
        migrations.AddConstraint(
            model_name='performancecycle',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_perf_cycle_code_company'),
        ),
        migrations.AddIndex(
            model_name='employeeperformancereview',
            index=models.Index(fields=['company', 'cycle'], name='hr_employee_company_fb4c84_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeperformancereview',
            index=models.Index(fields=['company', 'employee'], name='hr_employee_company_bfc900_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeperformancereview',
            index=models.Index(fields=['company', 'status'], name='hr_employee_company_998c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeperformancereview',
            index=models.Index(fields=['company', 'review_date'], name='hr_employee_company_a0a14b_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeperformancereview',
            index=models.Index(fields=['overall_score'], name='hr_employee_overall_3faed0_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeperformancereview',
            constraint=models.UniqueConstraint(fields=('company', 'cycle', 'employee'), name='uniq_perf_review_company_cycle_employee'),
        ),
        migrations.AddIndex(
            model_name='employeegoal',
            index=models.Index(fields=['company', 'employee'], name='hr_employee_company_2110f6_idx'),
        ),
        migrations.AddIndex(
            model_name='employeegoal',
            index=models.Index(fields=['company', 'cycle'], name='hr_employee_company_989ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='employeegoal',
            index=models.Index(fields=['company', 'status'], name='hr_employee_company_d96be4_idx'),
        ),
        migrations.AddIndex(
            model_name='employeegoal',
            index=models.Index(fields=['company', 'priority'], name='hr_employee_company_725692_idx'),
        ),
        migrations.AddIndex(
            model_name='employeegoal',
            index=models.Index(fields=['company', 'due_date'], name='hr_employee_company_44b139_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereviewscore',
            index=models.Index(fields=['company', 'review'], name='hr_performa_company_829a34_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereviewscore',
            index=models.Index(fields=['company', 'criterion'], name='hr_performa_company_7bb09d_idx'),
        ),
        migrations.AddConstraint(
            model_name='performancereviewscore',
            constraint=models.UniqueConstraint(fields=('company', 'review', 'criterion'), name='uniq_perf_score_company_review_criterion'),
        ),
    ]
