"use client";

import * as React from "react";
import {
  Activity,
  CheckCircle2,
  Copy,
  FileText,
  Loader2,
  PlugZap,
  Power,
  Printer,
  QrCode,
  RefreshCw,
  RotateCcw,
  Save,
  SendHorizontal,
  ShieldCheck,
  TriangleAlert,
  Unplug,
  Wifi,
} from "lucide-react";
import { toast } from "sonner";

import { API_PATHS } from "@/lib/api/endpoints";
import { useAuth } from "@/components/providers/AuthProvider";
import { canManageSystemWhatsApp } from "@/lib/permissions";
import { openPrintTableReport, type PrintReportTableSection } from "@/lib/print-report";
import SystemWhatsAppModuleNav from "@/components/system/whatsapp/SystemWhatsAppModuleNav";
import { SystemMetricCard } from "@/components/ui/system-metric-card";
import { registerBrandButtonClass, registerOutlineButtonClass } from "@/components/ui/data-register";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";

type Locale="ar"|"en";
type ApiRecord=Record<string,unknown>;
type FormState={provider:string;business_name:string;phone_number:string;phone_number_id:string;business_account_id:string;app_id:string;session_name:string;api_version:string;default_language:string;default_country_code:string;webhook_callback_url:string;access_token:string;webhook_verify_token:string;is_enabled:boolean;is_active:boolean;allow_broadcasts:boolean;send_test_enabled:boolean};
const emptyForm:FormState={provider:"WEB_SESSION",business_name:"",phone_number:"",phone_number_id:"",business_account_id:"",app_id:"",session_name:"",api_version:"v22.0",default_language:"ar",default_country_code:"+966",webhook_callback_url:"",access_token:"",webhook_verify_token:"",is_enabled:false,is_active:false,allow_broadcasts:false,send_test_enabled:true};
const tr={ar:{title:"إعدادات واتساب النظام",subtitle:"إدارة الاتصال الرسمي للنظام والجلسة وWebhook وQR وPairing والاختبار.",refresh:"تحديث",save:"حفظ",reset:"إعادة ضبط",print:"طباعة",status:"حالة الاتصال",gateway:"حالة Gateway",tokens:"الرموز المحفوظة",sessionMode:"وضع الجلسة",connection:"بيانات اتصال واتساب",connectionDesc:"إعدادات الرقم الرسمي والجلسة. الرموز المحفوظة لا يتم كشف قيمها.",provider:"المزود",businessName:"اسم النشاط",phone:"رقم واتساب",phoneId:"Phone Number ID",businessId:"Business Account ID",appId:"App ID",session:"اسم الجلسة",apiVersion:"إصدار API",language:"اللغة الافتراضية",country:"رمز الدولة",enabled:"مفعّل",active:"نشط",broadcasts:"السماح بالبث",sendTestEnabled:"السماح برسالة اختبار",webhook:"إعدادات Webhook",webhookDesc:"اترك الرموز فارغة للحفاظ على القيم المحفوظة.",callback:"Webhook Callback URL",accessToken:"Access Token",verifyToken:"Webhook Verify Token",qr:"QR Code",qrDesc:"أنشئ QR ثم امسحه من الأجهزة المرتبطة في واتساب.",pairing:"Pairing Code",pairingDesc:"أنشئ رمز ربط باستخدام رقم الهاتف.",pairPhone:"رقم الهاتف للربط",test:"رسالة اختبار",testDesc:"اختبر الاتصال بعد تشغيل Gateway وربط الجلسة.",recipient:"رقم المستلم",message:"نص الرسالة",send:"إرسال اختبار",disconnect:"فصل الاتصال",copy:"نسخ",copied:"تم النسخ.",saveSuccess:"تم حفظ إعدادات واتساب.",actionDone:"تم تنفيذ العملية.",loadError:"تعذر تحميل إعدادات واتساب.",tryAgain:"إعادة المحاولة",yes:"نعم",no:"لا",connectedPhone:"الهاتف المتصل",device:"الجهاز",lastConnected:"آخر اتصال",lastHealth:"آخر فحص",lastError:"آخر رسالة",generatedAt:"تم الإنشاء في"},
en:{title:"System WhatsApp Settings",subtitle:"Manage the official system connection, session, webhook, QR, pairing, and test.",refresh:"Refresh",save:"Save",reset:"Reset",print:"Print",status:"Connection status",gateway:"Gateway status",tokens:"Saved tokens",sessionMode:"Session mode",connection:"WhatsApp connection details",connectionDesc:"Official number and session settings. Saved token values are never exposed.",provider:"Provider",businessName:"Business name",phone:"WhatsApp phone",phoneId:"Phone Number ID",businessId:"Business Account ID",appId:"App ID",session:"Session name",apiVersion:"API version",language:"Default language",country:"Country code",enabled:"Enabled",active:"Active",broadcasts:"Allow broadcasts",sendTestEnabled:"Enable test message",webhook:"Webhook settings",webhookDesc:"Leave token fields empty to keep saved values.",callback:"Webhook Callback URL",accessToken:"Access Token",verifyToken:"Webhook Verify Token",qr:"QR Code",qrDesc:"Generate a QR then scan it from WhatsApp linked devices.",pairing:"Pairing Code",pairingDesc:"Generate a pairing code using the phone number.",pairPhone:"Phone number for pairing",test:"Test message",testDesc:"Test after the Gateway is running and the session is linked.",recipient:"Recipient phone",message:"Message body",send:"Send test",disconnect:"Disconnect",copy:"Copy",copied:"Copied.",saveSuccess:"WhatsApp settings saved.",actionDone:"Action completed.",loadError:"Could not load WhatsApp settings.",tryAgain:"Try again",yes:"Yes",no:"No",connectedPhone:"Connected phone",device:"Device",lastConnected:"Last connected",lastHealth:"Last health check",lastError:"Last message",generatedAt:"Generated at"}} as const;

function asRecord(v:unknown):ApiRecord{return v&&typeof v==="object"&&!Array.isArray(v)?v as ApiRecord:{}}
function text(v:unknown,f=""){return v==null?f:String(v).trim()||f}
function bool(v:unknown){return v===true||v==="true"||v===1||v==="1"}
function localeNow():Locale{if(typeof window==="undefined")return"ar";return window.localStorage.getItem("Mhamcloud-locale")==="en"?"en":"ar"}
function base(){const raw=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/+$/,"");return raw.endsWith("/api")?raw.slice(0,-4):raw}
function url(path:string){return`${base()}${path}`}
function cookie(name:string){if(typeof document==="undefined")return"";const p=document.cookie.split("; ").find(x=>x.startsWith(`${name}=`));return p?decodeURIComponent(p.split("=").slice(1).join("=")):""}
async function csrf(){let token=cookie("csrftoken");if(token)return token;await fetch(url("/api/auth/csrf/"),{credentials:"include",cache:"no-store"}).catch(()=>null);return cookie("csrftoken")}
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const method=(init.method||"GET").toUpperCase();const headers:Record<string,string>={Accept:"application/json","X-Requested-With":"XMLHttpRequest",...(init.body?{"Content-Type":"application/json"}:{}),...(init.headers as Record<string,string>|undefined)};if(method!=="GET"&&method!=="HEAD"){const token=await csrf();if(token)headers["X-CSRFToken"]=token}const response=await fetch(url(path),{...init,method,headers,credentials:"include",cache:"no-store"});const raw=await response.text();let payload:unknown={};try{payload=raw?JSON.parse(raw):{}}catch{payload={}}const r=asRecord(payload);if(!response.ok||r.success===false)throw new Error(text(r.message)||text(r.detail)||text(r.error)||`Request failed with status ${response.status}`);return payload as T}
function formFrom(c:ApiRecord):FormState{return{provider:text(c.provider,"WEB_SESSION"),business_name:text(c.business_name),phone_number:text(c.phone_number),phone_number_id:text(c.phone_number_id),business_account_id:text(c.business_account_id),app_id:text(c.app_id),session_name:text(c.session_name),api_version:text(c.api_version,"v22.0"),default_language:text(c.default_language,"ar"),default_country_code:text(c.default_country_code,"+966"),webhook_callback_url:text(c.webhook_callback_url),access_token:"",webhook_verify_token:"",is_enabled:bool(c.is_enabled),is_active:bool(c.is_active),allow_broadcasts:bool(c.allow_broadcasts),send_test_enabled:c.send_test_enabled===undefined?true:bool(c.send_test_enabled)}}
function statusLabel(v:unknown,l:Locale){const k=text(v,"—").toLowerCase();const ar:Record<string,string>={disconnected:"غير متصل",connecting:"جارٍ الاتصال",qr_pending:"بانتظار مسح QR",pair_pending:"بانتظار الربط",connected:"متصل",reconnecting:"إعادة اتصال",failed:"فشل"};const en:Record<string,string>={disconnected:"Disconnected",connecting:"Connecting",qr_pending:"QR pending",pair_pending:"Pairing pending",connected:"Connected",reconnecting:"Reconnecting",failed:"Failed"};return(l==="ar"?ar:en)[k]||text(v,"—")}
function sessionModeLabel(v:unknown,l:Locale){const k=text(v,"—").toLowerCase();if(k==="qr")return l==="ar"?"رمز QR":"QR code";if(k==="pairing_code")return l==="ar"?"رمز ربط":"Pairing code";return text(v,"—")}


export default function SystemWhatsAppSettingsView(){
 const session=useAuth(),canManage=canManageSystemWhatsApp(session);
 const[locale,setLocale]=React.useState<Locale>("ar"),[connection,setConnection]=React.useState<ApiRecord>({}),[form,setForm]=React.useState<FormState>(emptyForm),[original,setOriginal]=React.useState<FormState>(emptyForm),[loading,setLoading]=React.useState(true),[busy,setBusy]=React.useState(""),[error,setError]=React.useState(""),[qr,setQr]=React.useState(""),[pairCode,setPairCode]=React.useState(""),[pairPhone,setPairPhone]=React.useState(""),[recipient,setRecipient]=React.useState(""),[testMessage,setTestMessage]=React.useState("");const t=tr[locale],dir=locale==="ar"?"rtl":"ltr";
 React.useEffect(()=>{const f=()=>setLocale(localeNow());f();window.addEventListener("storage",f);window.addEventListener("Mhamcloud-locale-changed",f);return()=>{window.removeEventListener("storage",f);window.removeEventListener("Mhamcloud-locale-changed",f)}},[]);
 const load=React.useCallback(async(silent=false)=>{try{if(!silent)setLoading(true);setError("");const p=await request<unknown>(API_PATHS.systemWhatsApp.connection);const root=asRecord(p),c=asRecord(root.connection||root.setting||root.data);const f=formFrom(c);setConnection(c);setForm(f);setOriginal(f);setQr(text(c.qr_code||c.session_qr_code||c.qr));setPairCode(text(c.pairing_code||c.session_pairing_code));if(silent)toast.success(t.refresh)}catch(e){const m=e instanceof Error?e.message:t.loadError;setError(m);if(silent)toast.error(m)}finally{setLoading(false)}},[t.loadError,t.refresh]);
 React.useEffect(()=>{void load()},[load]);

 async function refreshLive(){
  setBusy("refresh");
  try{
   setError("");
   const payload=await request<unknown>(API_PATHS.systemWhatsApp.connectionStatus,{method:"POST",body:JSON.stringify({})});
   const root=asRecord(payload),c=asRecord(root.connection);
   const q=text(root.qr_code||root.qr||root.qrDataUrl||c.qr_code||c.session_qr_code||c.qr);
   const pc=text(root.pairing_code||root.pairingCode||root.code||c.pairing_code||c.session_pairing_code);
   if(q)setQr(q);
   if(pc)setPairCode(pc);
   await load(true);
  }catch(e){
   toast.error(e instanceof Error?e.message:t.loadError);
  }finally{
   setBusy("");
  }
 }

 function field<K extends keyof FormState>(key:K,value:FormState[K]){setForm(v=>({...v,[key]:value}))}
 async function save(){if(!canManage)return;setBusy("save");try{const body:Record<string,unknown>={...form};if(!form.access_token)delete body.access_token;if(!form.webhook_verify_token)delete body.webhook_verify_token;await request(API_PATHS.systemWhatsApp.connection,{method:"POST",body:JSON.stringify(body)});toast.success(t.saveSuccess);await load()}catch(e){toast.error(e instanceof Error?e.message:t.loadError)}finally{setBusy("")}}
 async function action(name:string,path:string,body:ApiRecord={}){if(!canManage)return;setBusy(name);try{const p=await request<unknown>(path,{method:"POST",body:JSON.stringify(body)});const r=asRecord(p),c=asRecord(r.connection);const q=text(r.qr_code||r.qr||c.qr_code||c.session_qr_code),pc=text(r.pairing_code||r.code||c.pairing_code||c.session_pairing_code);if(q)setQr(q);if(pc)setPairCode(pc);toast.success(text(r.message)||t.actionDone);await load()}catch(e){toast.error(e instanceof Error?e.message:t.loadError)}finally{setBusy("")}}
 async function copy(v:string){if(!v)return;await navigator.clipboard.writeText(v);toast.success(t.copied)}
 function print(){const section:PrintReportTableSection={title:t.connection,columns:[{label:"Field",type:"text"},{label:"Value",type:"text"}],rows:[[t.provider,form.provider],[t.businessName,form.business_name],[t.phone,form.phone_number],[t.session,form.session_name],[t.status,text(connection.session_status||connection.status||connection.connection_status,"—")],[t.gateway,text(connection.gateway_status,"—")],[t.callback,form.webhook_callback_url]]};openPrintTableReport({locale,title:t.title,subtitle:t.subtitle,sections:[section],recordsCount:section.rows.length,recordsLabel:"fields",generatedAtLabel:t.generatedAt})}
 if(loading)return <div className="space-y-6"><Skeleton className="h-10 w-72"/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[1,2,3,4].map(x=><Skeleton key={x} className="h-28"/>)}</div><Skeleton className="h-[600px]"/></div>;
 if(error)return <Card dir={dir} className="mx-auto max-w-3xl border-destructive/30"><CardHeader className="text-center"><TriangleAlert className="mx-auto size-8 text-destructive"/><CardTitle>{t.loadError}</CardTitle><CardDescription>{error}</CardDescription></CardHeader><CardContent className="text-center"><Button onClick={()=>void load(true)}><RefreshCw className="size-4"/>{t.tryAgain}</Button></CardContent></Card>;
 const status=statusLabel(connection.session_status||connection.status||connection.connection_status,locale),gateway=statusLabel(connection.gateway_status||connection.gateway_state,locale),tokens=(bool(connection.has_access_token)?1:0)+(bool(connection.has_webhook_verify_token)?1:0),sessionMode=sessionModeLabel(connection.session_mode,locale);
 return <div dir={dir} className="space-y-6"><SystemWhatsAppModuleNav/><header className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><h1 className="text-xl font-bold tracking-tight lg:text-2xl">{t.title}</h1><p className="mt-1 hidden text-sm text-muted-foreground lg:block">{t.subtitle}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" className={registerOutlineButtonClass} onClick={()=>void refreshLive()} disabled={!!busy}>{busy==="refresh"?<Loader2 className="size-4 animate-spin"/>:<RefreshCw className="size-4"/>}{t.refresh}</Button>{canManage?<><Button variant="outline" className={registerOutlineButtonClass} onClick={()=>setForm(original)}><RotateCcw className="size-4"/>{t.reset}</Button><Button className={registerBrandButtonClass} onClick={()=>void save()} disabled={!!busy}>{busy==="save"?<Loader2 className="size-4 animate-spin"/>:<Save className="size-4"/>}{t.save}</Button></>:null}<Button className={registerBrandButtonClass} onClick={print}><Printer className="size-4"/>{t.print}</Button></div></header>
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><SystemMetricCard title={t.status} value={status} description={text(connection.connected_phone||connection.session_connected_phone,"—")} icon={Wifi}/><SystemMetricCard title={t.gateway} value={gateway} description={text(connection.last_health_at||connection.last_health_check,"—")} icon={PlugZap}/><SystemMetricCard title={t.tokens} value={tokens} description={bool(connection.webhook_verified)?`${t.webhook}: ${t.yes}`:`${t.webhook}: ${t.no}`} icon={ShieldCheck}/><SystemMetricCard title={t.sessionMode} value={sessionMode} description={form.session_name||"—"} icon={Activity}/></div>
 <Card><CardHeader><CardTitle>{t.connection}</CardTitle><CardDescription>{t.connectionDesc}</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{([["provider",t.provider],["business_name",t.businessName],["phone_number",t.phone],["phone_number_id",t.phoneId],["business_account_id",t.businessId],["app_id",t.appId],["session_name",t.session],["api_version",t.apiVersion],["default_language",t.language],["default_country_code",t.country]] as const).map(([k,label])=><label key={k} className="space-y-2 text-sm font-medium"><span>{label}</span><Input value={String(form[k])} onChange={e=>field(k,e.target.value as never)} disabled={!canManage}/></label>)}<div className="col-span-full flex flex-wrap gap-4">{([["is_enabled",t.enabled],["is_active",t.active],["allow_broadcasts",t.broadcasts],["send_test_enabled",t.sendTestEnabled]] as const).map(([k,label])=><label key={k} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><input type="checkbox" checked={Boolean(form[k])} onChange={e=>field(k,e.target.checked as never)} disabled={!canManage}/><span>{label}</span></label>)}</div></CardContent></Card>
 <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>{t.webhook}</CardTitle><CardDescription>{t.webhookDesc}</CardDescription></CardHeader><CardContent className="space-y-4"><label className="block space-y-2 text-sm font-medium"><span>{t.callback}</span><Input value={form.webhook_callback_url} onChange={e=>field("webhook_callback_url",e.target.value)} disabled={!canManage}/></label><label className="block space-y-2 text-sm font-medium"><span>{t.accessToken}</span><Input type="password" value={form.access_token} onChange={e=>field("access_token",e.target.value)} placeholder={bool(connection.has_access_token)?"••••••••":""} disabled={!canManage}/></label><label className="block space-y-2 text-sm font-medium"><span>{t.verifyToken}</span><Input type="password" value={form.webhook_verify_token} onChange={e=>field("webhook_verify_token",e.target.value)} placeholder={bool(connection.has_webhook_verify_token)?"••••••••":""} disabled={!canManage}/></label></CardContent></Card>
 <Card><CardHeader><CardTitle>{t.qr}</CardTitle><CardDescription>{t.qrDesc}</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex min-h-72 items-center justify-center overflow-hidden rounded-xl border bg-muted/20 p-4">{qr?(qr.startsWith("data:image/")||qr.startsWith("https://")||qr.startsWith("http://")?<img src={qr} alt={t.qr} className="h-auto w-full max-w-[320px] rounded-lg bg-white p-3 object-contain" loading="eager" decoding="async"/>:<div className="max-h-64 w-full overflow-auto break-all text-sm text-muted-foreground">{qr}</div>):<span className="text-sm text-muted-foreground">—</span>}</div><Button className={registerBrandButtonClass} onClick={()=>void action("qr",API_PATHS.systemWhatsApp.connectionQr)} disabled={!canManage||!!busy}>{busy==="qr"?<Loader2 className="size-4 animate-spin"/>:<QrCode className="size-4"/>}{t.qr}</Button></CardContent></Card></div>
 <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>{t.pairing}</CardTitle><CardDescription>{t.pairingDesc}</CardDescription></CardHeader><CardContent className="space-y-4"><Input value={pairPhone} onChange={e=>setPairPhone(e.target.value)} placeholder={t.pairPhone} disabled={!canManage}/><div className="flex items-center gap-2 rounded-xl border bg-muted/20 p-4"><code className="min-w-0 flex-1 break-all">{pairCode||"—"}</code><Button size="icon" variant="ghost" onClick={()=>void copy(pairCode)} disabled={!pairCode}><Copy className="size-4"/></Button></div><Button className={registerBrandButtonClass} onClick={()=>void action("pair",API_PATHS.systemWhatsApp.connectionPairing,{phone_number:pairPhone})} disabled={!canManage||!!busy||!pairPhone.trim()}>{busy==="pair"?<Loader2 className="size-4 animate-spin"/>:<Power className="size-4"/>}{t.pairing}</Button></CardContent></Card>
 <Card><CardHeader><CardTitle>{t.test}</CardTitle><CardDescription>{t.testDesc}</CardDescription></CardHeader><CardContent className="space-y-4"><Input value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder={t.recipient} disabled={!canManage}/><Input value={testMessage} onChange={e=>setTestMessage(e.target.value)} placeholder={t.message} disabled={!canManage}/><Button className={registerBrandButtonClass} onClick={()=>void action("test",API_PATHS.systemWhatsApp.connectionTest,{recipient_phone:recipient,message_body:testMessage})} disabled={!canManage||!!busy||!recipient.trim()||!testMessage.trim()}>{busy==="test"?<Loader2 className="size-4 animate-spin"/>:<SendHorizontal className="size-4"/>}{t.send}</Button></CardContent></Card></div>
 <Card><CardHeader><CardTitle>{t.status}</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div><div className="text-xs text-muted-foreground">{t.connectedPhone}</div><div className="mt-1 font-medium">{text(connection.connected_phone||connection.session_connected_phone,"—")}</div></div><div><div className="text-xs text-muted-foreground">{t.device}</div><div className="mt-1 font-medium">{text(connection.device_label||connection.session_device_label,"—")}</div></div><div><div className="text-xs text-muted-foreground">{t.lastConnected}</div><div className="mt-1 font-medium">{text(connection.last_connected_at,"—")}</div></div><div><div className="text-xs text-muted-foreground">{t.lastHealth}</div><div className="mt-1 font-medium">{text(connection.last_health_at||connection.last_health_check,"—")}</div></div><div className="md:col-span-2 xl:col-span-4 flex items-center justify-between gap-3 border-t pt-4"><div><div className="text-xs text-muted-foreground">{t.lastError}</div><div className="mt-1 text-sm">{text(connection.last_error||connection.last_message,"—")}</div></div><Button variant="destructive" onClick={()=>void action("disconnect",API_PATHS.systemWhatsApp.connectionDisconnect)} disabled={!canManage||!!busy}>{busy==="disconnect"?<Loader2 className="size-4 animate-spin"/>:<Unplug className="size-4"/>}{t.disconnect}</Button></div></CardContent></Card></div>
}
