# Generated by Django 6.0.6 on 2026-06-19 18:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelryKarat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('karat_value', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001')), django.core.validators.MaxValueValidator(Decimal('24.000'))])),
                ('purity_percent', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('100.0000'))])),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jewelry_karats', to='companies.company')),
            ],
            options={
                'ordering': ['company_id', '-karat_value', 'code'],
            },
        ),
        migrations.CreateModel(
            name='JewelryGoldRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField(default=django.utils.timezone.localdate)),
                ('buying_price_per_gram', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('selling_price_per_gram', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('currency', models.CharField(default='SAR', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('source', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jewelry_gold_rates', to='companies.company')),
                ('karat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gold_rates', to='jewelry.jewelrykarat')),
            ],
            options={
                'ordering': ['company_id', '-rate_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JewelryMetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('metal_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('gemstone', 'Gemstone'), ('other', 'Other')], default='gold', max_length=32)),
                ('purity_percent', models.DecimalField(decimal_places=4, default=Decimal('100.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('100.0000'))])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jewelry_metals', to='companies.company')),
            ],
            options={
                'ordering': ['company_id', 'metal_type', 'code'],
            },
        ),
        migrations.AddField(
            model_name='jewelrykarat',
            name='metal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='karats', to='jewelry.jewelrymetal'),
        ),
        migrations.CreateModel(
            name='JewelryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=220)),
                ('catalog_item_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('inventory_item_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('gross_weight', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('stone_weight', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('net_gold_weight', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('making_charge_type', models.CharField(choices=[('per_gram', 'Per gram'), ('fixed', 'Fixed'), ('percentage', 'Percentage')], default='per_gram', max_length=24)),
                ('making_charge_value', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('stone_value', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('other_charges', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('15.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('100.0000'))])),
                ('last_base_amount', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('last_making_amount', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('last_subtotal', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('last_vat_amount', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('last_total', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('last_priced_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued')], default='active', max_length=24)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jewelry_items', to='companies.company')),
                ('last_gold_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priced_items', to='jewelry.jewelrygoldrate')),
                ('karat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jewelry_items', to='jewelry.jewelrykarat')),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jewelry_items', to='jewelry.jewelrymetal')),
            ],
            options={
                'ordering': ['company_id', 'sku'],
            },
        ),
        migrations.AddField(
            model_name='jewelrygoldrate',
            name='metal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gold_rates', to='jewelry.jewelrymetal'),
        ),
        migrations.AddIndex(
            model_name='jewelrymetal',
            index=models.Index(fields=['company', 'metal_type'], name='jewelry_jew_company_a9d49b_idx'),
        ),
        migrations.AddIndex(
            model_name='jewelrymetal',
            index=models.Index(fields=['company', 'is_active'], name='jewelry_jew_company_e28e07_idx'),
        ),
        migrations.AddConstraint(
            model_name='jewelrymetal',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_jewelry_metal_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='jewelrykarat',
            index=models.Index(fields=['company', 'metal'], name='jewelry_jew_company_e5d055_idx'),
        ),
        migrations.AddIndex(
            model_name='jewelrykarat',
            index=models.Index(fields=['company', 'is_active'], name='jewelry_jew_company_3cca66_idx'),
        ),
        migrations.AddConstraint(
            model_name='jewelrykarat',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_jewelry_karat_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='jewelryitem',
            index=models.Index(fields=['company', 'status'], name='jewelry_jew_company_c3695c_idx'),
        ),
        migrations.AddIndex(
            model_name='jewelryitem',
            index=models.Index(fields=['company', 'metal', 'karat'], name='jewelry_jew_company_916ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='jewelryitem',
            index=models.Index(fields=['company', 'catalog_item_id'], name='jewelry_jew_company_6569f2_idx'),
        ),
        migrations.AddIndex(
            model_name='jewelryitem',
            index=models.Index(fields=['company', 'inventory_item_id'], name='jewelry_jew_company_6e7a43_idx'),
        ),
        migrations.AddConstraint(
            model_name='jewelryitem',
            constraint=models.UniqueConstraint(fields=('company', 'sku'), name='unique_jewelry_item_sku_per_company'),
        ),
        migrations.AddIndex(
            model_name='jewelrygoldrate',
            index=models.Index(fields=['company', 'rate_date'], name='jewelry_jew_company_51a1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='jewelrygoldrate',
            index=models.Index(fields=['company', 'status'], name='jewelry_jew_company_b2fe27_idx'),
        ),
        migrations.AddIndex(
            model_name='jewelrygoldrate',
            index=models.Index(fields=['company', 'metal', 'karat'], name='jewelry_jew_company_77d6a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='jewelrygoldrate',
            constraint=models.UniqueConstraint(fields=('company', 'metal', 'karat', 'rate_date', 'status'), name='unique_jewelry_gold_rate_scope'),
        ),
    ]
