# Generated by Django 6.0.6 on 2026-06-04 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_company_building_number_company_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('ACCOUNTANT', 'Accountant'), ('CASHIER', 'Cashier'), ('SALES', 'Sales'), ('INVENTORY', 'Inventory'), ('HR', 'HR'), ('EMPLOYEE', 'Employee'), ('VIEWER', 'Viewer')], db_index=True, default='EMPLOYEE', max_length=40, verbose_name='Company role')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INVITED', 'Invited'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=30, verbose_name='Status')),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text="Marks the user's preferred membership when multiple companies exist.", verbose_name='Primary membership')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='Job title')),
                ('department', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Department')),
                ('invited_at', models.DateTimeField(blank=True, null=True, verbose_name='Invited at')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='Joined at')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='Suspended at')),
                ('suspended_reason', models.TextField(blank=True, verbose_name='Suspended reason')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Company membership',
                'verbose_name_plural': 'Company memberships',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='accounts_co_company_f6fdb5_idx'), models.Index(fields=['user', 'status'], name='accounts_co_user_id_040556_idx'), models.Index(fields=['company', 'role'], name='accounts_co_company_ffca22_idx'), models.Index(fields=['is_primary', 'status'], name='accounts_co_is_prim_abeb0e_idx'), models.Index(fields=['department'], name='accounts_co_departm_e00dc7_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='unique_user_company_membership')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Display name')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Mobile')),
                ('whatsapp_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='WhatsApp number')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INVITED', 'Invited'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=30, verbose_name='Status')),
                ('default_workspace', models.CharField(choices=[('SYSTEM', 'System'), ('COMPANY', 'Company')], db_index=True, default='COMPANY', max_length=30, verbose_name='Default workspace')),
                ('system_role', models.CharField(choices=[('NONE', 'None'), ('SUPER_ADMIN', 'Super Admin'), ('SYSTEM_ADMIN', 'System Admin'), ('SUPPORT', 'Support'), ('BILLING_MANAGER', 'Billing Manager')], db_index=True, default='NONE', max_length=40, verbose_name='System role')),
                ('is_system_user', models.BooleanField(db_index=True, default=False, help_text='Allows access to /system when combined with an allowed system role.', verbose_name='System user')),
                ('language', models.CharField(default='ar', max_length=10, verbose_name='Language')),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=100, verbose_name='Timezone')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Last seen at')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='Suspended at')),
                ('suspended_reason', models.TextField(blank=True, verbose_name='Suspended reason')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('default_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='companies.company', verbose_name='Default company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primeyacc_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'default_workspace'], name='accounts_us_status_75d955_idx'), models.Index(fields=['is_system_user', 'system_role'], name='accounts_us_is_syst_647615_idx'), models.Index(fields=['phone'], name='accounts_us_phone_27e73a_idx'), models.Index(fields=['mobile'], name='accounts_us_mobile_9be6d8_idx')],
            },
        ),
    ]
