# Generated by Django 6.0.6 on 2026-06-07 19:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('companies', '0003_branch_companysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Quantity on hand')),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Reserved quantity')),
                ('minimum_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Minimum quantity')),
                ('maximum_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Maximum quantity')),
                ('average_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Average cost')),
                ('last_movement_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last movement at')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='companies.company', verbose_name='Company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='catalog.catalogitem', verbose_name='Catalog item')),
            ],
            options={
                'verbose_name': 'Stock item',
                'verbose_name_plural': 'Stock items',
                'ordering': ['company_id', 'warehouse_id', 'item__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Status')),
                ('warehouse_type', models.CharField(choices=[('MAIN', 'Main'), ('BRANCH', 'Branch'), ('RETURN', 'Return'), ('DAMAGE', 'Damage'), ('VIRTUAL', 'Virtual')], db_index=True, default='MAIN', max_length=20, verbose_name='Warehouse type')),
                ('code', models.CharField(db_index=True, help_text='Unique warehouse code inside the same company.', max_length=50, verbose_name='Warehouse code')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Warehouse name')),
                ('name_ar', models.CharField(blank=True, default='', max_length=255, verbose_name='Arabic name')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='English name')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='Default warehouse')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('manager_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Manager name')),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254, verbose_name='Email')),
                ('country', models.CharField(default='Saudi Arabia', max_length=100, verbose_name='Country')),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='City')),
                ('district', models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='District')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('branch', models.ForeignKey(blank=True, help_text='Optional branch. Must belong to the same company.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='companies.branch', verbose_name='Branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inventory_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['company_id', '-is_default', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out')], db_index=True, max_length=30, verbose_name='Movement type')),
                ('direction', models.CharField(choices=[('INCREASE', 'Increase'), ('DECREASE', 'Decrease')], db_index=True, max_length=20, verbose_name='Direction')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('movement_number', models.CharField(db_index=True, help_text='Unique movement number inside the same company.', max_length=80, verbose_name='Movement number')),
                ('movement_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Movement date')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantity')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit cost')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total cost')),
                ('quantity_before', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, verbose_name='Quantity before')),
                ('quantity_after', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, verbose_name='Quantity after')),
                ('item_code_snapshot', models.CharField(blank=True, default='', max_length=80, verbose_name='Item code snapshot')),
                ('item_name_snapshot', models.CharField(max_length=255, verbose_name='Item name snapshot')),
                ('item_name_ar_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Item Arabic name snapshot')),
                ('item_name_en_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Item English name snapshot')),
                ('unit_name_snapshot', models.CharField(blank=True, default='', max_length=120, verbose_name='Unit name snapshot')),
                ('reference_type', models.CharField(blank=True, db_index=True, default='', help_text='Optional source type such as purchase_bill, sales_invoice, manual_adjustment.', max_length=80, verbose_name='Reference type')),
                ('reference_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='Reference ID')),
                ('reference_number', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Reference number')),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Posted at')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cancelled at')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name='Cancellation reason')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.catalogitem', verbose_name='Catalog item')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Posted by')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockitem', verbose_name='Stock item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Stock movement',
                'verbose_name_plural': 'Stock movements',
                'ordering': ['-movement_date', '-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'status'], name='inventory_w_company_ad8ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'warehouse_type'], name='inventory_w_company_76d40c_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'is_default'], name='inventory_w_company_2c06fa_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'is_active'], name='inventory_w_company_ab385b_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'branch'], name='inventory_w_company_aef281_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'city'], name='inventory_w_company_96859c_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='inventory_w_code_2cdc02_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['created_at'], name='inventory_w_created_6e6d24_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_inventory_warehouse_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_inventory_warehouse_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'status'], name='inventory_s_company_b8dc88_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'movement_type'], name='inventory_s_company_339f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'direction'], name='inventory_s_company_22c3ce_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'movement_date'], name='inventory_s_company_07d153_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'warehouse'], name='inventory_s_company_c843dc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'item'], name='inventory_s_company_c1dde4_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'reference_type', 'reference_id'], name='inventory_s_company_e7ee98_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', 'item'], name='inventory_s_warehou_a6dcf9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_item', 'status'], name='inventory_s_stock_i_3cc57c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['posted_at'], name='inventory_s_posted__418d64_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['cancelled_at'], name='inventory_s_cancell_3acff0_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='inventory_s_created_05ebf5_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(fields=('company', 'movement_number'), name='unique_stock_movement_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['company', 'warehouse'], name='inventory_s_company_b2b60b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['company', 'item'], name='inventory_s_company_010efd_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['company', 'quantity_on_hand'], name='inventory_s_company_991426_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['warehouse', 'item'], name='inventory_s_warehou_c5f727_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['last_movement_at'], name='inventory_s_last_mo_8d982c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['created_at'], name='inventory_s_created_59753c_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('company', 'warehouse', 'item'), name='unique_stock_item_per_company_warehouse_item'),
        ),
    ]
