# Generated by Django 6.0.6 on 2026-06-15 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Status')),
                ('location_type', models.CharField(choices=[('ZONE', 'Zone'), ('AISLE', 'Aisle'), ('RACK', 'Rack'), ('BIN', 'Bin'), ('RECEIVING', 'Receiving'), ('SHIPPING', 'Shipping'), ('ADJUSTMENT', 'Adjustment'), ('VIRTUAL', 'Virtual')], db_index=True, default='BIN', max_length=20, verbose_name='Location type')),
                ('code', models.CharField(db_index=True, help_text='Unique location code inside the same warehouse.', max_length=80, verbose_name='Location code')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Location name')),
                ('name_ar', models.CharField(blank=True, default='', max_length=255, verbose_name='Arabic name')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='English name')),
                ('barcode', models.CharField(blank=True, db_index=True, default='', help_text='Optional unique barcode inside the same warehouse.', max_length=120, verbose_name='Barcode')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='Default location')),
                ('is_receiving', models.BooleanField(db_index=True, default=False, verbose_name='Receiving location')),
                ('is_shipping', models.BooleanField(db_index=True, default=False, verbose_name='Shipping location')),
                ('is_adjustment', models.BooleanField(db_index=True, default=False, verbose_name='Adjustment location')),
                ('is_pickable', models.BooleanField(db_index=True, default=True, verbose_name='Pickable')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('sequence', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sequence')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_locations', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_locations', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent location inside the same warehouse.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.inventorylocation', verbose_name='Parent location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inventory_locations', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Inventory location',
                'verbose_name_plural': 'Inventory locations',
                'ordering': ['company_id', 'warehouse_id', 'sequence', 'code', 'id'],
                'indexes': [models.Index(fields=['company', 'warehouse'], name='inventory_i_company_25c8ff_idx'), models.Index(fields=['company', 'status'], name='inventory_i_company_fdfc24_idx'), models.Index(fields=['company', 'location_type'], name='inventory_i_company_bef5e8_idx'), models.Index(fields=['warehouse', 'parent'], name='inventory_i_warehou_2ca3aa_idx'), models.Index(fields=['warehouse', 'status'], name='inventory_i_warehou_2f4917_idx'), models.Index(fields=['warehouse', 'location_type'], name='inventory_i_warehou_8e0d5e_idx'), models.Index(fields=['warehouse', 'is_default'], name='inventory_i_warehou_e08d2c_idx'), models.Index(fields=['warehouse', 'is_receiving'], name='inventory_i_warehou_8f21f8_idx'), models.Index(fields=['warehouse', 'is_shipping'], name='inventory_i_warehou_ecb838_idx'), models.Index(fields=['warehouse', 'is_adjustment'], name='inventory_i_warehou_5d654a_idx'), models.Index(fields=['warehouse', 'is_pickable'], name='inventory_i_warehou_e5ea9a_idx'), models.Index(fields=['warehouse', 'is_active'], name='inventory_i_warehou_2a868e_idx'), models.Index(fields=['barcode'], name='inventory_i_barcode_8a3b34_idx'), models.Index(fields=['created_at'], name='inventory_i_created_843647_idx')],
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'code'), name='unique_inventory_location_code_per_warehouse'), models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('warehouse', 'barcode'), name='unique_inventory_location_barcode_per_warehouse'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('warehouse',), name='unique_default_inventory_location_per_warehouse'), models.UniqueConstraint(condition=models.Q(('is_receiving', True)), fields=('warehouse',), name='unique_receiving_inventory_location_per_warehouse'), models.UniqueConstraint(condition=models.Q(('is_shipping', True)), fields=('warehouse',), name='unique_shipping_inventory_location_per_warehouse'), models.UniqueConstraint(condition=models.Q(('is_adjustment', True)), fields=('warehouse',), name='unique_adjustment_inventory_location_per_warehouse')],
            },
        ),
    ]
