# Generated by Django 6.0.6 on 2026-06-15 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('inventory', '0002_inventorylocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Transitional nullable location. Existing warehouse-level balances will be migrated to the default warehouse location.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_stock_items', to='inventory.inventorylocation', verbose_name='Inventory location'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Transitional nullable location. Existing movements will be linked to their warehouse default location.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_stock_movements', to='inventory.inventorylocation', verbose_name='Inventory location'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['company', 'warehouse', 'location'], name='inventory_s_company_51be85_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['company', 'location', 'item'], name='inventory_s_company_6762d1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'warehouse', 'location'], name='inventory_s_company_08a7e3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'location', 'item'], name='inventory_s_company_b859c0_idx'),
        ),
    ]
