# Generated by Django 6.0.6 on 2026-06-15 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('inventory', '0004_backfill_stock_locations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['company_id', 'warehouse_id', 'location_id', 'item__name', 'id'], 'verbose_name': 'Stock item', 'verbose_name_plural': 'Stock items'},
        ),
        migrations.RemoveConstraint(
            model_name='stockitem',
            name='unique_stock_item_per_company_warehouse_item',
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='location',
            field=models.ForeignKey(help_text='Required location that owns this independent stock balance.', on_delete=django.db.models.deletion.PROTECT, related_name='location_stock_items', to='inventory.inventorylocation', verbose_name='Inventory location'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('company', 'warehouse', 'location', 'item'), name='unique_stock_item_per_company_warehouse_location_item'),
        ),
    ]
