# Generated by Django 6.0.6 on 2026-06-17 19:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalogitem_inventory_tracking_method_and_more'),
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('inventory', '0005_alter_stockitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEPLETED', 'Depleted'), ('EXPIRED', 'Expired'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Status')),
                ('batch_number', models.CharField(db_index=True, help_text='Unique batch number for this catalog item inside the company.', max_length=120, verbose_name='Batch / lot number')),
                ('supplier_batch_number', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Supplier batch number')),
                ('manufactured_at', models.DateField(blank=True, db_index=True, null=True, verbose_name='Manufacturing date')),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Expiry date')),
                ('received_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='First received at')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_batches', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_batches', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_batches', to='catalog.catalogitem', verbose_name='Catalog item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inventory_batches', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Inventory batch',
                'verbose_name_plural': 'Inventory batches',
                'ordering': ['company_id', 'item_id', 'expiry_date', 'batch_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBatchBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Quantity on hand')),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Reserved quantity')),
                ('average_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Average cost')),
                ('last_movement_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last movement at')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.inventorybatch', verbose_name='Inventory batch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_batch_balances', to='companies.company', verbose_name='Company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_batch_balances', to='catalog.catalogitem', verbose_name='Catalog item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_balances', to='inventory.inventorylocation', verbose_name='Inventory location')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_balances', to='inventory.stockitem', verbose_name='Stock item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_balances', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Inventory batch balance',
                'verbose_name_plural': 'Inventory batch balances',
                'ordering': ['company_id', 'warehouse_id', 'location_id', 'item_id', 'batch_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventorySerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('ISSUED', 'Issued'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived')], db_index=True, default='AVAILABLE', max_length=20, verbose_name='Status')),
                ('serial_number', models.CharField(db_index=True, help_text='Unique serial number inside the company.', max_length=180, verbose_name='Serial number')),
                ('manufacturer_serial_number', models.CharField(blank=True, db_index=True, default='', max_length=180, verbose_name='Manufacturer serial number')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit cost')),
                ('received_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Received at')),
                ('issued_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Issued at')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_serial_numbers', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_serial_numbers', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_serial_numbers', to='catalog.catalogitem', verbose_name='Catalog item')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serial_numbers', to='inventory.inventorylocation', verbose_name='Current inventory location')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serial_numbers', to='inventory.stockitem', verbose_name='Current stock item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inventory_serial_numbers', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serial_numbers', to='inventory.warehouse', verbose_name='Current warehouse')),
            ],
            options={
                'verbose_name': 'Inventory serial number',
                'verbose_name_plural': 'Inventory serial numbers',
                'ordering': ['company_id', 'item_id', 'serial_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTrackingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('ISSUE', 'Issue'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('ADJUSTMENT_IN', 'Adjustment in'), ('ADJUSTMENT_OUT', 'Adjustment out'), ('RESERVATION', 'Reservation'), ('RELEASE', 'Reservation release'), ('BLOCK', 'Block'), ('UNBLOCK', 'Unblock')], db_index=True, max_length=30, verbose_name='Tracking entry type')),
                ('direction', models.CharField(choices=[('INCREASE', 'Increase'), ('DECREASE', 'Decrease')], db_index=True, max_length=20, verbose_name='Direction')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantity')),
                ('quantity_before', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, verbose_name='Quantity before')),
                ('quantity_after', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, verbose_name='Quantity after')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit cost')),
                ('reference_type', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Reference type')),
                ('reference_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='Reference ID')),
                ('reference_number', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Reference number')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Occurred at')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracking_entries', to='inventory.inventorybatch', verbose_name='Inventory batch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_tracking_entries', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_tracking_entries', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_tracking_entries', to='catalog.catalogitem', verbose_name='Catalog item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_entries', to='inventory.inventorylocation', verbose_name='Inventory location')),
                ('serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracking_entries', to='inventory.inventoryserialnumber', verbose_name='Serial number')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_entries', to='inventory.stockitem', verbose_name='Stock item')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracking_entries', to='inventory.stockmovement', verbose_name='Stock movement')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_entries', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Inventory tracking entry',
                'verbose_name_plural': 'Inventory tracking entries',
                'ordering': ['-occurred_at', '-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['company', 'status'], name='inventory_i_company_63a4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['company', 'item'], name='inventory_i_company_9741f7_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['company', 'batch_number'], name='inventory_i_company_4fffbb_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['company', 'expiry_date'], name='inventory_i_company_26863c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['company', 'item', 'expiry_date'], name='inventory_i_company_d52c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['status', 'expiry_date'], name='inventory_i_status_a706ba_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['created_at'], name='inventory_i_created_f8b4b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.UniqueConstraint(fields=('company', 'item', 'batch_number'), name='unique_inventory_batch_per_company_item'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.CheckConstraint(condition=models.Q(('manufactured_at__isnull', True), ('expiry_date__isnull', True), ('expiry_date__gte', models.F('manufactured_at')), _connector='OR'), name='inventory_batch_expiry_after_manufacture'),
        ),
        migrations.AddIndex(
            model_name='inventorybatchbalance',
            index=models.Index(fields=['company', 'warehouse'], name='inventory_i_company_649db9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatchbalance',
            index=models.Index(fields=['company', 'warehouse', 'location'], name='inventory_i_company_b3cd67_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatchbalance',
            index=models.Index(fields=['company', 'location', 'item'], name='inventory_i_company_2a8195_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatchbalance',
            index=models.Index(fields=['company', 'item', 'batch'], name='inventory_i_company_52c42a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatchbalance',
            index=models.Index(fields=['company', 'batch'], name='inventory_i_company_ac9c03_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatchbalance',
            index=models.Index(fields=['batch', 'quantity_on_hand'], name='inventory_i_batch_i_9ea999_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatchbalance',
            index=models.Index(fields=['last_movement_at'], name='inventory_i_last_mo_1d8936_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatchbalance',
            index=models.Index(fields=['created_at'], name='inventory_i_created_333c66_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatchbalance',
            constraint=models.UniqueConstraint(fields=('company', 'warehouse', 'location', 'item', 'batch'), name='unique_inventory_batch_balance_location'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatchbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', Decimal('0.0000'))), name='inventory_batch_balance_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatchbalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', Decimal('0.0000'))), name='inventory_batch_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatchbalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity_on_hand'))), name='inventory_batch_reserved_not_above_on_hand'),
        ),
        migrations.AddIndex(
            model_name='inventoryserialnumber',
            index=models.Index(fields=['company', 'status'], name='inventory_i_company_4ac13a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryserialnumber',
            index=models.Index(fields=['company', 'item'], name='inventory_i_company_a59d67_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryserialnumber',
            index=models.Index(fields=['company', 'warehouse'], name='inventory_i_company_937a61_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryserialnumber',
            index=models.Index(fields=['company', 'warehouse', 'location'], name='inventory_i_company_a59993_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryserialnumber',
            index=models.Index(fields=['company', 'location', 'item'], name='inventory_i_company_cd060e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryserialnumber',
            index=models.Index(fields=['company', 'serial_number'], name='inventory_i_company_46ca15_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryserialnumber',
            index=models.Index(fields=['item', 'status'], name='inventory_i_item_id_3985da_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryserialnumber',
            index=models.Index(fields=['received_at'], name='inventory_i_receive_5f27b6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryserialnumber',
            index=models.Index(fields=['issued_at'], name='inventory_i_issued__3a7513_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryserialnumber',
            index=models.Index(fields=['created_at'], name='inventory_i_created_1044b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryserialnumber',
            constraint=models.UniqueConstraint(fields=('company', 'serial_number'), name='unique_inventory_serial_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='inventoryserialnumber',
            constraint=models.UniqueConstraint(condition=models.Q(('manufacturer_serial_number', ''), _negated=True), fields=('company', 'manufacturer_serial_number'), name='unique_manufacturer_serial_per_company'),
        ),
        migrations.AddConstraint(
            model_name='inventoryserialnumber',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', Decimal('0.00'))), name='inventory_serial_unit_cost_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='inventorytrackingentry',
            index=models.Index(fields=['company', 'entry_type'], name='inventory_i_company_6222b5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytrackingentry',
            index=models.Index(fields=['company', 'occurred_at'], name='inventory_i_company_194b06_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytrackingentry',
            index=models.Index(fields=['company', 'item'], name='inventory_i_company_137498_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytrackingentry',
            index=models.Index(fields=['company', 'warehouse', 'location'], name='inventory_i_company_064800_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytrackingentry',
            index=models.Index(fields=['company', 'batch'], name='inventory_i_company_d66d23_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytrackingentry',
            index=models.Index(fields=['company', 'serial_number'], name='inventory_i_company_7babd9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytrackingentry',
            index=models.Index(fields=['company', 'reference_type', 'reference_id'], name='inventory_i_company_198fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytrackingentry',
            index=models.Index(fields=['stock_movement', 'entry_type'], name='inventory_i_stock_m_9de714_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytrackingentry',
            index=models.Index(fields=['occurred_at'], name='inventory_i_occurre_8f8697_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytrackingentry',
            index=models.Index(fields=['created_at'], name='inventory_i_created_6ea085_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorytrackingentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('batch__isnull', False), ('serial_number__isnull', True)), models.Q(('batch__isnull', True), ('serial_number__isnull', False)), _connector='OR'), name='inventory_tracking_batch_or_serial_only'),
        ),
        migrations.AddConstraint(
            model_name='inventorytrackingentry',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0.0000'))), name='inventory_tracking_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorytrackingentry',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', Decimal('0.00'))), name='inventory_tracking_unit_cost_nonnegative'),
        ),
    ]
