# Generated by Django 6.0.6 on 2026-06-18 12:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalogitem_inventory_tracking_method_and_more'),
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('inventory', '0006_inventorybatch_inventorybatchbalance_and_more'),
        ('sales', '0009_salescreditnote_allocated_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(db_index=True, help_text='Unique reservation number inside the same company.', max_length=80, verbose_name='Reservation number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PARTIALLY_ALLOCATED', 'Partially allocated'), ('ALLOCATED', 'Allocated'), ('PARTIALLY_FULFILLED', 'Partially fulfilled'), ('FULFILLED', 'Fulfilled'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', max_length=30, verbose_name='Status')),
                ('source', models.CharField(choices=[('SALES_ORDER', 'Sales order'), ('MANUAL', 'Manual'), ('API', 'API'), ('IMPORT', 'Import')], db_index=True, default='SALES_ORDER', max_length=20, verbose_name='Source')),
                ('requested_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Requested quantity')),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Reserved quantity')),
                ('fulfilled_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Fulfilled quantity')),
                ('released_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Released quantity')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Expires at')),
                ('allocated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Allocated at')),
                ('fulfilled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fulfilled at')),
                ('released_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Released at')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cancelled at')),
                ('expired_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Expired at')),
                ('release_reason', models.TextField(blank=True, default='', verbose_name='Release reason')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name='Cancellation reason')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_stock_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Allocated by')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_stock_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_stock_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Released by')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='sales.salesorder', verbose_name='Sales order')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_stock_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Stock reservation',
                'verbose_name_plural': 'Stock reservations',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockReservationAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RESERVED', 'Reserved'), ('PARTIALLY_FULFILLED', 'Partially fulfilled'), ('FULFILLED', 'Fulfilled'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30, verbose_name='Status')),
                ('reserved_quantity', models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Reserved quantity')),
                ('fulfilled_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Fulfilled quantity')),
                ('released_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Released quantity')),
                ('reserved_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Reserved at')),
                ('fulfilled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fulfilled at')),
                ('released_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Released at')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cancelled at')),
                ('release_reason', models.TextField(blank=True, default='', verbose_name='Release reason')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name='Cancellation reason')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_allocations', to='inventory.inventorybatch', verbose_name='Inventory batch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservation_allocations', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_reservation_allocations', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservation_allocations', to='catalog.catalogitem', verbose_name='Catalog item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_allocations', to='inventory.inventorylocation', verbose_name='Inventory location')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_stock_reservation_allocations', to=settings.AUTH_USER_MODEL, verbose_name='Released by')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='inventory.stockreservation', verbose_name='Stock reservation')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservation_allocations', to='sales.salesorderitem', verbose_name='Sales order item')),
                ('serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_allocations', to='inventory.inventoryserialnumber', verbose_name='Inventory serial number')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_allocations', to='inventory.stockitem', verbose_name='Stock item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_stock_reservation_allocations', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_allocations', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Stock reservation allocation',
                'verbose_name_plural': 'Stock reservation allocations',
                'ordering': ['reservation_id', 'sales_order_item_id', 'warehouse_id', 'location_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['company', 'status'], name='inventory_s_company_b720e3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['company', 'source'], name='inventory_s_company_c98ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['company', 'sales_order'], name='inventory_s_company_313191_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['company', 'expires_at'], name='inventory_s_company_43a2b1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['sales_order', 'status'], name='inventory_s_sales_o_cc5463_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['reservation_number'], name='inventory_s_reserva_d698ad_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['allocated_at'], name='inventory_s_allocat_2d758c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['fulfilled_at'], name='inventory_s_fulfill_454880_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['released_at'], name='inventory_s_release_b5fa8b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['cancelled_at'], name='inventory_s_cancell_42b972_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['created_at'], name='inventory_s_created_e1ee85_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.UniqueConstraint(fields=('company', 'reservation_number'), name='unique_stock_reservation_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('requested_quantity__gte', Decimal('0.0000'))), name='stock_reservation_requested_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', Decimal('0.0000'))), name='stock_reservation_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('fulfilled_quantity__gte', Decimal('0.0000'))), name='stock_reservation_fulfilled_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('released_quantity__gte', Decimal('0.0000'))), name='stock_reservation_released_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('requested_quantity'))), name='stock_reservation_reserved_not_above_requested'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('fulfilled_quantity__lte', models.F('reserved_quantity'))), name='stock_reservation_fulfilled_not_above_reserved'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('released_quantity__lte', models.F('reserved_quantity'))), name='stock_reservation_released_not_above_reserved'),
        ),
        migrations.AddIndex(
            model_name='stockreservationallocation',
            index=models.Index(fields=['company', 'status'], name='inventory_s_company_5fd227_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservationallocation',
            index=models.Index(fields=['company', 'reservation'], name='inventory_s_company_89c44f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservationallocation',
            index=models.Index(fields=['company', 'sales_order_item'], name='inventory_s_company_df8a47_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservationallocation',
            index=models.Index(fields=['company', 'warehouse', 'location'], name='inventory_s_company_01ebd1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservationallocation',
            index=models.Index(fields=['company', 'location', 'item'], name='inventory_s_company_ade9ef_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservationallocation',
            index=models.Index(fields=['company', 'item', 'batch'], name='inventory_s_company_aef26f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservationallocation',
            index=models.Index(fields=['company', 'serial_number'], name='inventory_s_company_ce4d68_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservationallocation',
            index=models.Index(fields=['reservation', 'status'], name='inventory_s_reserva_4bb3ce_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservationallocation',
            index=models.Index(fields=['sales_order_item', 'status'], name='inventory_s_sales_o_fb3180_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservationallocation',
            index=models.Index(fields=['stock_item', 'status'], name='inventory_s_stock_i_b80200_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservationallocation',
            index=models.Index(fields=['reserved_at'], name='inventory_s_reserve_dfefa5_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservationallocation',
            index=models.Index(fields=['fulfilled_at'], name='inventory_s_fulfill_3c4cef_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservationallocation',
            index=models.Index(fields=['released_at'], name='inventory_s_release_e20f63_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservationallocation',
            index=models.Index(fields=['created_at'], name='inventory_s_created_2a3ae8_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockreservationallocation',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gt', Decimal('0.0000'))), name='stock_reservation_allocation_reserved_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockreservationallocation',
            constraint=models.CheckConstraint(condition=models.Q(('fulfilled_quantity__gte', Decimal('0.0000'))), name='stock_reservation_allocation_fulfilled_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockreservationallocation',
            constraint=models.CheckConstraint(condition=models.Q(('released_quantity__gte', Decimal('0.0000'))), name='stock_reservation_allocation_released_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockreservationallocation',
            constraint=models.CheckConstraint(condition=models.Q(('fulfilled_quantity__lte', models.F('reserved_quantity'))), name='stock_reservation_allocation_fulfilled_not_above_reserved'),
        ),
        migrations.AddConstraint(
            model_name='stockreservationallocation',
            constraint=models.CheckConstraint(condition=models.Q(('released_quantity__lte', models.F('reserved_quantity'))), name='stock_reservation_allocation_released_not_above_reserved'),
        ),
        migrations.AddConstraint(
            model_name='stockreservationallocation',
            constraint=models.CheckConstraint(condition=models.Q(('batch__isnull', False), ('serial_number__isnull', False), _negated=True), name='stock_reservation_batch_and_serial_not_together'),
        ),
    ]
