# Generated by Django 6.0.6 on 2026-06-18 18:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalogitem_inventory_tracking_method_and_more'),
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('inventory', '0007_stockreservation_stockreservationallocation_and_more'),
        ('sales', '0009_salescreditnote_allocated_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(db_index=True, max_length=80, verbose_name='Issue number')),
                ('issue_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Issue date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Posted at')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cancelled at')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name='Cancellation reason')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_goods_issues', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_issues', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goods_issues', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issues', to='inventory.inventorylocation', verbose_name='Default issue location')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_goods_issues', to=settings.AUTH_USER_MODEL, verbose_name='Posted by')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_issues', to='sales.salesorder', verbose_name='Sales order')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_goods_issues', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_issues', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Goods issue',
                'verbose_name_plural': 'Goods issues',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsIssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Line number')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantity')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit cost')),
                ('item_code_snapshot', models.CharField(blank=True, default='', max_length=80)),
                ('item_name_snapshot', models.CharField(max_length=255)),
                ('item_name_ar_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('item_name_en_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('unit_name_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_items', to='inventory.inventorybatch', verbose_name='Batch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_issue_items', to='companies.company', verbose_name='Company')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.goodsissue', verbose_name='Goods issue')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_items', to='catalog.catalogitem', verbose_name='Catalog item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_items', to='inventory.inventorylocation', verbose_name='Inventory location')),
                ('reservation_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_items', to='inventory.stockreservationallocation', verbose_name='Reservation allocation')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_items', to='sales.salesorderitem', verbose_name='Sales order item')),
                ('serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_items', to='inventory.inventoryserialnumber', verbose_name='Serial number')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_items', to='inventory.stockitem', verbose_name='Stock item')),
                ('stock_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_item', to='inventory.stockmovement', verbose_name='Stock movement')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_items', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Goods issue item',
                'verbose_name_plural': 'Goods issue items',
                'ordering': ['issue_id', 'line_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='goodsissue',
            index=models.Index(fields=['company', 'status'], name='inventory_g_company_33919d_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsissue',
            index=models.Index(fields=['company', 'issue_date'], name='inventory_g_company_3bda87_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsissue',
            index=models.Index(fields=['company', 'sales_order'], name='inventory_g_company_a86b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsissue',
            index=models.Index(fields=['company', 'warehouse'], name='inventory_g_company_9c6ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsissue',
            index=models.Index(fields=['company', 'location'], name='inventory_g_company_cb4ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsissue',
            index=models.Index(fields=['posted_at'], name='inventory_g_posted__fb863a_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsissue',
            index=models.Index(fields=['cancelled_at'], name='inventory_g_cancell_faf825_idx'),
        ),
        migrations.AddConstraint(
            model_name='goodsissue',
            constraint=models.UniqueConstraint(fields=('company', 'issue_number'), name='unique_goods_issue_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='goodsissueitem',
            index=models.Index(fields=['company', 'issue'], name='inventory_g_company_3ca368_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsissueitem',
            index=models.Index(fields=['company', 'sales_order_item'], name='inventory_g_company_d02356_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsissueitem',
            index=models.Index(fields=['company', 'reservation_allocation'], name='inventory_g_company_277e33_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsissueitem',
            index=models.Index(fields=['company', 'warehouse'], name='inventory_g_company_a8764e_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsissueitem',
            index=models.Index(fields=['company', 'location'], name='inventory_g_company_0176c7_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsissueitem',
            index=models.Index(fields=['company', 'item'], name='inventory_g_company_6b5750_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsissueitem',
            index=models.Index(fields=['company', 'batch'], name='inventory_g_company_f75bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsissueitem',
            index=models.Index(fields=['company', 'serial_number'], name='inventory_g_company_963a65_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsissueitem',
            index=models.Index(fields=['company', 'created_at'], name='inventory_g_company_dbf5a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='goodsissueitem',
            constraint=models.UniqueConstraint(fields=('issue', 'line_number'), name='unique_goods_issue_item_line'),
        ),
    ]
