# Generated by Django 6.0.6 on 2026-06-18 19:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalogitem_inventory_tracking_method_and_more'),
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('inventory', '0008_goodsissue_goodsissueitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalInventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In progress'), ('COUNTED', 'Counted'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('scope', models.CharField(choices=[('FULL_WAREHOUSE', 'Full warehouse'), ('LOCATION', 'Location'), ('CYCLE_COUNT', 'Cycle count')], db_index=True, default='CYCLE_COUNT', max_length=30, verbose_name='Scope')),
                ('count_number', models.CharField(db_index=True, max_length=80, verbose_name='Count number')),
                ('count_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Count date')),
                ('total_system_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, verbose_name='Total system quantity')),
                ('total_counted_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, verbose_name='Total counted quantity')),
                ('total_variance_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, verbose_name='Total variance quantity')),
                ('total_variance_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total variance value')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Started at')),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Posted at')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cancelled at')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name='Cancellation reason')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_physical_inventory_counts', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_inventory_counts', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_physical_inventory_counts', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physical_inventory_counts', to='inventory.inventorylocation', verbose_name='Inventory location')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_physical_inventory_counts', to=settings.AUTH_USER_MODEL, verbose_name='Posted by')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_physical_inventory_counts', to=settings.AUTH_USER_MODEL, verbose_name='Started by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_physical_inventory_counts', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_inventory_counts', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Physical inventory count',
                'verbose_name_plural': 'Physical inventory counts',
                'ordering': ['-count_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalInventoryCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Line number')),
                ('system_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, verbose_name='System quantity')),
                ('counted_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Counted quantity')),
                ('variance_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16, verbose_name='Variance quantity')),
                ('system_unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='System unit cost')),
                ('variance_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Variance value')),
                ('item_code_snapshot', models.CharField(blank=True, default='', max_length=80, verbose_name='Item code snapshot')),
                ('item_name_snapshot', models.CharField(max_length=255, verbose_name='Item name snapshot')),
                ('item_name_ar_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Item Arabic name snapshot')),
                ('item_name_en_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Item English name snapshot')),
                ('unit_name_snapshot', models.CharField(blank=True, default='', max_length=120, verbose_name='Unit name snapshot')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_inventory_count_items', to='companies.company', verbose_name='Company')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.physicalinventorycount', verbose_name='Physical inventory count')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_inventory_count_items', to='catalog.catalogitem', verbose_name='Catalog item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_inventory_count_items', to='inventory.inventorylocation', verbose_name='Inventory location')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_inventory_count_items', to='inventory.stockitem', verbose_name='Stock item')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_inventory_count_items', to='inventory.stockmovement', verbose_name='Stock movement')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_inventory_count_items', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Physical inventory count item',
                'verbose_name_plural': 'Physical inventory count items',
                'ordering': ['count_id', 'line_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='physicalinventorycount',
            index=models.Index(fields=['company', 'status'], name='inventory_p_company_4a30a9_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalinventorycount',
            index=models.Index(fields=['company', 'scope'], name='inventory_p_company_a48d31_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalinventorycount',
            index=models.Index(fields=['company', 'warehouse'], name='inventory_p_company_f7b8a7_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalinventorycount',
            index=models.Index(fields=['company', 'warehouse', 'location'], name='inventory_p_company_ff7a35_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalinventorycount',
            index=models.Index(fields=['company', 'count_date'], name='inventory_p_company_1583f2_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalinventorycount',
            index=models.Index(fields=['posted_at'], name='inventory_p_posted__09e987_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalinventorycount',
            index=models.Index(fields=['cancelled_at'], name='inventory_p_cancell_94653c_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalinventorycount',
            index=models.Index(fields=['created_at'], name='inventory_p_created_8d77d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='physicalinventorycount',
            constraint=models.UniqueConstraint(fields=('company', 'count_number'), name='unique_physical_inventory_count_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='physicalinventorycountitem',
            index=models.Index(fields=['company', 'warehouse'], name='inventory_p_company_79a12a_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalinventorycountitem',
            index=models.Index(fields=['company', 'warehouse', 'location'], name='inventory_p_company_19148a_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalinventorycountitem',
            index=models.Index(fields=['company', 'item'], name='inventory_p_company_f17535_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalinventorycountitem',
            index=models.Index(fields=['stock_item', 'count'], name='inventory_p_stock_i_223f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalinventorycountitem',
            index=models.Index(fields=['stock_movement'], name='inventory_p_stock_m_f2e955_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalinventorycountitem',
            index=models.Index(fields=['created_at'], name='inventory_p_created_c5284d_idx'),
        ),
        migrations.AddConstraint(
            model_name='physicalinventorycountitem',
            constraint=models.UniqueConstraint(fields=('count', 'stock_item'), name='unique_physical_count_line_per_stock_item'),
        ),
    ]
