# Generated by Django 6.0.6 on 2026-06-19 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('source_app', models.CharField(blank=True, max_length=80)),
                ('source_model', models.CharField(blank=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('object_reference', models.CharField(blank=True, max_length=120)),
                ('action', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, max_length=120)),
                ('idempotency_key', models.CharField(blank=True, max_length=160)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_audit_events', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_audit_events', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', 'created_at'], name='business_co_company_dd4ac1_idx'), models.Index(fields=['company', 'event_type'], name='business_co_company_a9cbc9_idx'), models.Index(fields=['company', 'source_app', 'source_model'], name='business_co_company_583eaf_idx'), models.Index(fields=['company', 'object_reference'], name='business_co_company_f87ae7_idx'), models.Index(fields=['company', 'idempotency_key'], name='business_co_company_d2937f_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160)),
                ('scope', models.CharField(max_length=120)),
                ('operation', models.CharField(max_length=120)),
                ('request_hash', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='started', max_length=20)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_idempotency_keys', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', 'scope', 'key'], name='business_co_company_b016dc_idx'), models.Index(fields=['company', 'operation'], name='business_co_company_6250a0_idx'), models.Index(fields=['company', 'status'], name='business_co_company_2955ed_idx'), models.Index(fields=['company', 'expires_at'], name='business_co_company_818d17_idx')],
                'unique_together': {('company', 'scope', 'key')},
            },
        ),
        migrations.CreateModel(
            name='BusinessReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=120)),
                ('prefix', models.CharField(max_length=40)),
                ('current_number', models.PositiveBigIntegerField(default=0)),
                ('padding', models.PositiveSmallIntegerField(default=6)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_reference_sequences', to='companies.company')),
            ],
            options={
                'ordering': ['scope', 'prefix'],
                'indexes': [models.Index(fields=['company', 'scope'], name='business_co_company_3c72b2_idx'), models.Index(fields=['company', 'prefix'], name='business_co_company_b17e58_idx'), models.Index(fields=['company', 'is_active'], name='business_co_company_17f49c_idx')],
                'unique_together': {('company', 'scope', 'prefix')},
            },
        ),
    ]
