# Generated by Django 6.0.6 on 2026-08-19 10:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_controls', '0001_initial'),
        ('companies', '0005_seed_activity_profiles'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(db_index=True, max_length=80)),
                ('migration_name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('dry_run', 'Dry Run'), ('validated', 'Validated'), ('applied', 'Applied'), ('failed', 'Failed')], default='dry_run', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_count', models.PositiveBigIntegerField(default=0)),
                ('processed_count', models.PositiveBigIntegerField(default=0)),
                ('created_count', models.PositiveBigIntegerField(default=0)),
                ('updated_count', models.PositiveBigIntegerField(default=0)),
                ('skipped_count', models.PositiveBigIntegerField(default=0)),
                ('failed_count', models.PositiveBigIntegerField(default=0)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('reconciliation', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_migration_runs', to='companies.company')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LegacyObjectMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(max_length=80)),
                ('source_table', models.CharField(max_length=120)),
                ('legacy_id', models.CharField(max_length=160)),
                ('legacy_company_id', models.CharField(blank=True, max_length=160)),
                ('target_object_id', models.CharField(blank=True, max_length=160)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('migrated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_object_maps', to='companies.company')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='object_maps', to='business_controls.migrationrun')),
            ],
            options={
                'ordering': ['source_system', 'source_table', 'legacy_id'],
            },
        ),
        migrations.AddIndex(
            model_name='migrationrun',
            index=models.Index(fields=['source_system', 'status'], name='bc_mrun_source_status_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationrun',
            index=models.Index(fields=['company', 'status'], name='bc_mrun_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationrun',
            index=models.Index(fields=['migration_name', 'started_at'], name='bc_mrun_name_start_idx'),
        ),
        migrations.AddIndex(
            model_name='legacyobjectmap',
            index=models.Index(fields=['source_system', 'source_table', 'legacy_id'], name='bc_legacy_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='legacyobjectmap',
            index=models.Index(fields=['source_system', 'legacy_company_id'], name='bc_legacy_company_idx'),
        ),
        migrations.AddIndex(
            model_name='legacyobjectmap',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='bc_legacy_target_idx'),
        ),
        migrations.AddIndex(
            model_name='legacyobjectmap',
            index=models.Index(fields=['company', 'source_table'], name='bc_legacy_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='legacyobjectmap',
            index=models.Index(fields=['run', 'source_table'], name='bc_legacy_run_table_idx'),
        ),
        migrations.AddConstraint(
            model_name='legacyobjectmap',
            constraint=models.UniqueConstraint(fields=('source_system', 'source_table', 'legacy_id'), name='bc_legacy_source_object_uniq'),
        ),
    ]
