# Generated by Django 6.0.6 on 2026-06-11 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_branch_companysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Template name')),
                ('document_type', models.CharField(choices=[('SALES_INVOICE', 'Sales invoice'), ('PURCHASE_BILL', 'Purchase bill'), ('CUSTOMER_RECEIPT', 'Customer receipt'), ('SUPPLIER_PAYMENT', 'Supplier payment'), ('JOURNAL_ENTRY', 'Journal entry'), ('POS_RECEIPT', 'POS receipt')], db_index=True, max_length=40, verbose_name='Document type')),
                ('layout_style', models.CharField(choices=[('STANDARD', 'Standard'), ('COMPACT', 'Compact'), ('MODERN', 'Modern'), ('THERMAL', 'Thermal')], db_index=True, default='STANDARD', max_length=30, verbose_name='Layout style')),
                ('primary_color', models.CharField(default='#111827', max_length=20, verbose_name='Primary color')),
                ('secondary_color', models.CharField(default='#6B7280', max_length=20, verbose_name='Secondary color')),
                ('show_logo', models.BooleanField(default=True, verbose_name='Show company logo')),
                ('show_qr', models.BooleanField(default=True, verbose_name='Show QR code')),
                ('show_vat_number', models.BooleanField(default=True, verbose_name='Show VAT number')),
                ('show_commercial_registration', models.BooleanField(default=True, verbose_name='Show commercial registration')),
                ('header_text', models.CharField(blank=True, max_length=255, verbose_name='Header text')),
                ('footer_text', models.CharField(blank=True, max_length=255, verbose_name='Footer text')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='Terms and conditions')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='Default template')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_document_templates', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Document template',
                'verbose_name_plural': 'Document templates',
                'ordering': ['document_type', '-is_default', 'name'],
                'indexes': [models.Index(fields=['company', 'document_type'], name='documents_d_company_b5641f_idx'), models.Index(fields=['company', 'is_active'], name='documents_d_company_9ef136_idx'), models.Index(fields=['company', 'document_type', 'is_default'], name='documents_d_company_d97033_idx'), models.Index(fields=['layout_style'], name='documents_d_layout__97a41a_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'document_type', 'name'), name='unique_company_document_template_name'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('company', 'document_type'), name='unique_default_document_template_per_type')],
            },
        ),
    ]
