# Generated by Django 6.0.6 on 2026-09-19 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_onboarding_lifecycle'),
        ('documents', '0001_initial'),
        ('pos', '0002_posreturn_posreturnitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=80)),
                ('scope', models.CharField(choices=[('COMPANY', 'Company'), ('BRANCH', 'Branch'), ('REGISTER', 'POS register')], db_index=True, default='COMPANY', max_length=20)),
                ('scope_key', models.CharField(db_index=True, max_length=80)),
                ('prefix', models.CharField(blank=True, default='', max_length=60)),
                ('suffix', models.CharField(blank=True, default='', max_length=60)),
                ('padding', models.PositiveSmallIntegerField(default=6)),
                ('next_value', models.PositiveBigIntegerField(default=1)),
                ('reset_yearly', models.BooleanField(default=False)),
                ('current_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_sequences', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='companies.company')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_sequences', to='pos.posregister')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'key', 'is_active'], name='documents_d_company_a2eb5e_idx'), models.Index(fields=['company', 'branch', 'key'], name='documents_d_company_08e209_idx'), models.Index(fields=['company', 'register', 'key'], name='documents_d_company_b942a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'key', 'scope_key'), name='unique_document_sequence_scope_key')],
            },
        ),
        migrations.CreateModel(
            name='PrintProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('document_type', models.CharField(choices=[('SALES_INVOICE', 'Sales invoice'), ('PURCHASE_BILL', 'Purchase bill'), ('CUSTOMER_RECEIPT', 'Customer receipt'), ('SUPPLIER_PAYMENT', 'Supplier payment'), ('JOURNAL_ENTRY', 'Journal entry'), ('POS_RECEIPT', 'POS receipt')], db_index=True, max_length=40)),
                ('output_format', models.CharField(default='WEB_PRINT', max_length=20)),
                ('paper_size', models.CharField(default='A4', max_length=20)),
                ('thermal_width', models.CharField(default='80MM', max_length=10)),
                ('language', models.CharField(default='ar', max_length=10)),
                ('copies', models.PositiveSmallIntegerField(default=1)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('settings_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_profiles', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_profiles', to='companies.company')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_profiles', to='pos.posregister')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_profiles', to='documents.documenttemplate')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'document_type', 'is_active'], name='documents_p_company_65917c_idx'), models.Index(fields=['company', 'branch', 'document_type'], name='documents_p_company_1e8001_idx'), models.Index(fields=['company', 'register', 'document_type'], name='documents_p_company_0281fd_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'document_type', 'name'), name='unique_company_print_profile_name')],
            },
        ),
    ]
