# Generated by Django 6.0.6 on 2026-06-09 19:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('companies', '0003_branch_companysettings'),
        ('inventory', '0001_initial'),
        ('parties', '0001_initial'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(db_index=True, help_text='Unique inside the same company.', max_length=50, verbose_name='Return number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30, verbose_name='Status')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Discount amount')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Taxable amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Tax amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total amount')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount expected to be refunded to the customer.', max_digits=14, verbose_name='Refund amount')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled at')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Cancellation reason')),
                ('reason', models.TextField(blank=True, verbose_name='Return reason')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_returns', to='companies.branch', verbose_name='Branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_pos_returns', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_returns', to='companies.company', verbose_name='Company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_pos_returns', to=settings.AUTH_USER_MODEL, verbose_name='Completed by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos_returns', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_returns', to='parties.businessparty', verbose_name='Customer')),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='pos.posorder', verbose_name='Original POS order')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='pos.posregister', verbose_name='Register')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='pos.possession', verbose_name='POS session')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pos_returns', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_returns', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'POS return',
                'verbose_name_plural': 'POS returns',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='POSReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Item code')),
                ('item_sku', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Item SKU')),
                ('item_barcode', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Item barcode')),
                ('item_name', models.CharField(max_length=255, verbose_name='Item name')),
                ('unit_name', models.CharField(blank=True, max_length=100, verbose_name='Unit name')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Returned quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Unit price')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Discount amount')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Taxable amount')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7, verbose_name='Tax rate')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Tax amount')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Line total')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_return_items', to='catalog.catalogitem', verbose_name='Catalog item')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_return_items', to='companies.company', verbose_name='Company')),
                ('original_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='pos.posorderitem', verbose_name='Original POS order item')),
                ('pos_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.posreturn', verbose_name='POS return')),
            ],
            options={
                'verbose_name': 'POS return item',
                'verbose_name_plural': 'POS return items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='posreturn',
            index=models.Index(fields=['company', 'status'], name='pos_posretu_company_cc0854_idx'),
        ),
        migrations.AddIndex(
            model_name='posreturn',
            index=models.Index(fields=['company', 'original_order'], name='pos_posretu_company_0f99f0_idx'),
        ),
        migrations.AddIndex(
            model_name='posreturn',
            index=models.Index(fields=['company', 'session'], name='pos_posretu_company_433579_idx'),
        ),
        migrations.AddIndex(
            model_name='posreturn',
            index=models.Index(fields=['company', 'register'], name='pos_posretu_company_b7152b_idx'),
        ),
        migrations.AddIndex(
            model_name='posreturn',
            index=models.Index(fields=['company', 'branch'], name='pos_posretu_company_72141e_idx'),
        ),
        migrations.AddIndex(
            model_name='posreturn',
            index=models.Index(fields=['company', 'created_at'], name='pos_posretu_company_f72ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='posreturn',
            index=models.Index(fields=['return_number'], name='pos_posretu_return__73ad0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='posreturn',
            constraint=models.UniqueConstraint(fields=('company', 'return_number'), name='unique_pos_return_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='posreturnitem',
            index=models.Index(fields=['company', 'pos_return'], name='pos_posretu_company_c55020_idx'),
        ),
        migrations.AddIndex(
            model_name='posreturnitem',
            index=models.Index(fields=['company', 'original_order_item'], name='pos_posretu_company_e2691a_idx'),
        ),
        migrations.AddIndex(
            model_name='posreturnitem',
            index=models.Index(fields=['company', 'catalog_item'], name='pos_posretu_company_f57b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='posreturnitem',
            index=models.Index(fields=['item_code'], name='pos_posretu_item_co_a569f9_idx'),
        ),
        migrations.AddIndex(
            model_name='posreturnitem',
            index=models.Index(fields=['item_sku'], name='pos_posretu_item_sk_8a2a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='posreturnitem',
            index=models.Index(fields=['item_barcode'], name='pos_posretu_item_ba_abab2d_idx'),
        ),
    ]
