# Generated by Django 6.0.6 on 2026-06-04 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Company name')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Arabic name')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='English name')),
                ('company_code', models.CharField(db_index=True, help_text='Unique internal code used by Mhamcloud.', max_length=50, unique=True, verbose_name='Company code')),
                ('activity_profile', models.CharField(choices=[('GENERAL', 'General'), ('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale'), ('JEWELRY', 'Jewelry / Gold'), ('PETROL_STATION', 'Petrol Station')], db_index=True, default='GENERAL', max_length=40, verbose_name='Activity profile')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Trial'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='TRIAL', max_length=30, verbose_name='Status')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('commercial_registration', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Commercial registration')),
                ('tax_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Tax number')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Mobile')),
                ('whatsapp_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='WhatsApp number')),
                ('country', models.CharField(default='Saudi Arabia', max_length=100, verbose_name='Country')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='City')),
                ('region', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Region')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/%Y/%m/', verbose_name='Logo')),
                ('currency_code', models.CharField(default='SAR', max_length=10, verbose_name='Currency code')),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='VAT percentage')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Trial ends at')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='Suspended at')),
                ('suspended_reason', models.TextField(blank=True, verbose_name='Suspended reason')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Company settings')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_Mhamcloud_companies', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_Mhamcloud_companies', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_Mhamcloud_companies', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'is_active'], name='companies_c_status_1b6f0b_idx'), models.Index(fields=['activity_profile', 'status'], name='companies_c_activit_c14df0_idx'), models.Index(fields=['city', 'status'], name='companies_c_city_eda1ed_idx'), models.Index(fields=['commercial_registration'], name='companies_c_commerc_42258a_idx'), models.Index(fields=['tax_number'], name='companies_c_tax_num_a6c49e_idx')],
            },
        ),
    ]
