# Generated by Django 6.0.6 on 2026-06-04 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='building_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Building number'),
        ),
        migrations.AddField(
            model_name='company',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='company',
            name='short_address',
            field=models.CharField(blank=True, db_index=True, help_text='Saudi short national address if available.', max_length=50, verbose_name='Short address'),
        ),
        migrations.AddField(
            model_name='company',
            name='street_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Street name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, help_text='Optional extra address notes. National address fields are the main address source.', verbose_name='Additional address'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['district', 'city'], name='companies_c_distric_8f4a31_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['postal_code'], name='companies_c_postal__1b6dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['short_address'], name='companies_c_short_a_7d2a2b_idx'),
        ),
    ]
