# Generated by Django 6.0.6 on 2026-06-06 10:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_building_number_company_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Branch name')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Arabic name')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='English name')),
                ('branch_code', models.CharField(db_index=True, help_text='Unique inside the same company.', max_length=50, verbose_name='Branch code')),
                ('branch_type', models.CharField(choices=[('HEAD_OFFICE', 'Head office'), ('BRANCH', 'Branch'), ('WAREHOUSE', 'Warehouse'), ('POS', 'POS'), ('SERVICE_CENTER', 'Service center')], db_index=True, default='BRANCH', max_length=40, verbose_name='Branch type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=30, verbose_name='Status')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='Only one default branch should exist per company.', verbose_name='Default branch')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Manager name')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Mobile')),
                ('whatsapp_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='WhatsApp number')),
                ('country', models.CharField(default='Saudi Arabia', max_length=100, verbose_name='Country')),
                ('building_number', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Building number')),
                ('street_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Street name')),
                ('district', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='District')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='City')),
                ('region', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Region')),
                ('postal_code', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Postal code')),
                ('short_address', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Short address')),
                ('address', models.TextField(blank=True, verbose_name='Additional address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Opening time')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Closing time')),
                ('settings_data', models.JSONField(blank=True, default=dict, verbose_name='Branch settings data')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_branches', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_company_branches', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['company_id', '-is_default', 'name'],
                'indexes': [models.Index(fields=['company', 'status', 'is_active'], name='companies_b_company_f59226_idx'), models.Index(fields=['company', 'branch_type'], name='companies_b_company_6978b0_idx'), models.Index(fields=['company', 'is_default'], name='companies_b_company_d82d5b_idx'), models.Index(fields=['company', 'city'], name='companies_b_company_560283_idx'), models.Index(fields=['company', 'district', 'city'], name='companies_b_company_62d664_idx'), models.Index(fields=['branch_code'], name='companies_b_branch__9b85ae_idx'), models.Index(fields=['short_address'], name='companies_b_short_a_e33f1f_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'branch_code'), name='unique_branch_code_per_company')],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=10, verbose_name='Default language')),
                ('timezone_name', models.CharField(default='Asia/Riyadh', max_length=100, verbose_name='Timezone')),
                ('date_format', models.CharField(default='yyyy-MM-dd', max_length=50, verbose_name='Date format')),
                ('time_format', models.CharField(default='24h', max_length=20, verbose_name='Time format')),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1, help_text='1 = January, 12 = December.', verbose_name='Fiscal year start month')),
                ('fiscal_year_start_day', models.PositiveSmallIntegerField(default=1, verbose_name='Fiscal year start day')),
                ('invoice_prefix', models.CharField(default='INV', max_length=20, verbose_name='Invoice prefix')),
                ('quotation_prefix', models.CharField(default='QUO', max_length=20, verbose_name='Quotation prefix')),
                ('purchase_prefix', models.CharField(default='PUR', max_length=20, verbose_name='Purchase prefix')),
                ('receipt_prefix', models.CharField(default='REC', max_length=20, verbose_name='Receipt prefix')),
                ('payment_prefix', models.CharField(default='PAY', max_length=20, verbose_name='Payment prefix')),
                ('allow_negative_stock', models.BooleanField(default=False, verbose_name='Allow negative stock')),
                ('enable_inventory_tracking', models.BooleanField(default=True, verbose_name='Enable inventory tracking')),
                ('enable_pos', models.BooleanField(default=True, verbose_name='Enable POS')),
                ('enable_purchases', models.BooleanField(default=True, verbose_name='Enable purchases')),
                ('enable_hr', models.BooleanField(default=False, verbose_name='Enable HR')),
                ('enable_vat', models.BooleanField(default=True, verbose_name='Enable VAT')),
                ('default_vat_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='Default VAT percentage')),
                ('require_customer_for_sales', models.BooleanField(default=False, verbose_name='Require customer for sales')),
                ('require_supplier_for_purchases', models.BooleanField(default=True, verbose_name='Require supplier for purchases')),
                ('settings_data', models.JSONField(blank=True, default=dict, verbose_name='Additional settings data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operational_settings', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_operational_settings', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_company_operational_settings', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Company settings',
                'verbose_name_plural': 'Company settings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['default_language'], name='companies_c_default_006d79_idx'), models.Index(fields=['enable_pos', 'enable_inventory_tracking'], name='companies_c_enable__4a1274_idx'), models.Index(fields=['enable_vat'], name='companies_c_enable__fd1864_idx')],
            },
        ),
    ]
