# Generated by Django 6.0.6 on 2026-06-11 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_branch_companysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=60, verbose_name='Activity code')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Activity name')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Arabic name')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='English name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_system', models.BooleanField(db_index=True, default=True, verbose_name='System profile')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('default_settings', models.JSONField(blank=True, default=dict, help_text='Future-ready defaults for accounting, POS, inventory, documents, and reports.', verbose_name='Default settings')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(blank=True, help_text='Null means system-level profile. Set for company-specific custom profiles.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_activity_profiles', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activity_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_activity_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Activity profile',
                'verbose_name_plural': 'Activity profiles',
                'ordering': ['-is_system', 'name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='activity_profile_ref',
            field=models.ForeignKey(blank=True, help_text='Expandable activity profile reference. Keeps legacy activity_profile field untouched.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.activityprofile', verbose_name='Activity profile reference'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['activity_profile_ref', 'status'], name='companies_c_activit_a40df4_idx'),
        ),
        migrations.AddIndex(
            model_name='activityprofile',
            index=models.Index(fields=['company', 'is_active'], name='companies_a_company_788c30_idx'),
        ),
        migrations.AddIndex(
            model_name='activityprofile',
            index=models.Index(fields=['is_system', 'is_active'], name='companies_a_is_syst_7ccea1_idx'),
        ),
        migrations.AddIndex(
            model_name='activityprofile',
            index=models.Index(fields=['code'], name='companies_a_code_c057cc_idx'),
        ),
        migrations.AddIndex(
            model_name='activityprofile',
            index=models.Index(fields=['name'], name='companies_a_name_4ca48a_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityprofile',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_activity_profile_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='activityprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('code',), name='unique_system_activity_profile_code'),
        ),
    ]
