# Generated by Django 6.0.6 on 2026-08-23 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_seed_activity_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUIRED', 'Required'), ('IN_PROGRESS', 'In progress'), ('READY', 'Ready')], db_index=True, default='REQUIRED', max_length=30, verbose_name='Onboarding status')),
                ('current_step', models.CharField(blank=True, default='', max_length=80, verbose_name='Current onboarding step')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Onboarding extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='companies.company', verbose_name='Company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_company_onboardings', to=settings.AUTH_USER_MODEL, verbose_name='Completed by')),
            ],
            options={
                'verbose_name': 'Company onboarding',
                'verbose_name_plural': 'Company onboardings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='companies_c_status_3e1183_idx'), models.Index(fields=['company', 'status'], name='companies_c_company_486b54_idx')],
            },
        ),
    ]
