# Generated by Django 6.0.6 on 2026-09-19 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_onboarding_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='activity_profile',
            field=models.ForeignKey(blank=True, help_text='Optional branch activity override. Null inherits company activity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='companies.activityprofile', verbose_name='Branch activity profile'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['company', 'activity_profile'], name='companies_b_company_727505_idx'),
        ),
    ]
