# Generated by Django 6.0.6 on 2026-06-28 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Key name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('environment', models.CharField(choices=[('TEST', 'Test'), ('LIVE', 'Live')], db_index=True, default='TEST', max_length=20, verbose_name='Environment')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Status')),
                ('key_prefix', models.CharField(db_index=True, help_text='Safe display prefix. The full key is never stored.', max_length=80, unique=True, verbose_name='Key prefix')),
                ('key_hash', models.CharField(max_length=255, unique=True, verbose_name='Key hash')),
                ('scopes', models.JSONField(blank=True, default=list, help_text='Allowed integration permissions for this key.', verbose_name='Scopes')),
                ('ip_allowlist', models.JSONField(blank=True, default=list, help_text='Optional list of IPs or CIDR ranges allowed to use this key.', verbose_name='IP allowlist')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60, verbose_name='Rate limit per minute')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Expires at')),
                ('last_used_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last used at')),
                ('usage_count', models.PositiveBigIntegerField(default=0, verbose_name='Usage count')),
                ('disabled_at', models.DateTimeField(blank=True, null=True, verbose_name='Disabled at')),
                ('disabled_reason', models.TextField(blank=True, verbose_name='Disabled reason')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked at')),
                ('revoked_reason', models.TextField(blank=True, verbose_name='Revoked reason')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_api_keys', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integration_api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disabled_integration_api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Disabled by')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_integration_api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Revoked by')),
                ('rotated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotated_keys', to='integrations.integrationapikey', verbose_name='Rotated from')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_integration_api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Integration API key',
                'verbose_name_plural': 'Integration API keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationApiKeyUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(db_index=True, max_length=12, verbose_name='HTTP method')),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name='Request path')),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Status code')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Request ID')),
                ('scope', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Scope')),
                ('success', models.BooleanField(db_index=True, default=False, verbose_name='Success')),
                ('error_message', models.TextField(blank=True, verbose_name='Error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='integrations.integrationapikey', verbose_name='API key')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_api_key_usage_logs', to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Integration API key usage log',
                'verbose_name_plural': 'Integration API key usage logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='integrationapikey',
            index=models.Index(fields=['company', 'status'], name='integration_company_b40ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationapikey',
            index=models.Index(fields=['company', 'environment'], name='integration_company_d5ba19_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationapikey',
            index=models.Index(fields=['status', 'environment'], name='integration_status_84af8a_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationapikey',
            index=models.Index(fields=['expires_at'], name='integration_expires_162a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationapikey',
            index=models.Index(fields=['last_used_at'], name='integration_last_us_691e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationapikey',
            index=models.Index(fields=['created_at'], name='integration_created_3f038c_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationapikeyusagelog',
            index=models.Index(fields=['api_key', 'created_at'], name='integration_api_key_280b07_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationapikeyusagelog',
            index=models.Index(fields=['company', 'created_at'], name='integration_company_3f1baa_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationapikeyusagelog',
            index=models.Index(fields=['success', 'created_at'], name='integration_success_bee4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationapikeyusagelog',
            index=models.Index(fields=['method', 'status_code'], name='integration_method_b7333c_idx'),
        ),
    ]
