# Generated by Django 6.0.6 on 2026-06-08 20:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('companies', '0003_branch_companysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('WALLET', 'Wallet')], db_index=True, default='CASH', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('bank_name', models.CharField(blank=True, max_length=180)),
                ('bank_account_number', models.CharField(blank=True, max_length=80)),
                ('iban', models.CharField(blank=True, max_length=40)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_accounts', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treasury_accounts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_treasury_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Treasury Account',
                'verbose_name_plural': 'Treasury Accounts',
                'ordering': ['company_id', 'account_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, max_length=80)),
                ('transaction_type', models.CharField(choices=[('INFLOW', 'Inflow'), ('OUTFLOW', 'Outflow'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('SALES_INVOICE', 'Sales Invoice'), ('PURCHASE_BILL', 'Purchase Bill'), ('CUSTOMER_PAYMENT', 'Customer Payment'), ('SUPPLIER_PAYMENT', 'Supplier Payment'), ('INVENTORY', 'Inventory'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer')], db_index=True, default='MANUAL', max_length=40)),
                ('source_app', models.CharField(blank=True, max_length=80)),
                ('source_model', models.CharField(blank=True, max_length=120)),
                ('source_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_accounting_posted', models.BooleanField(db_index=True, default=False)),
                ('accounting_posted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='treasury.treasuryaccount')),
                ('accounting_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_transactions', to='accounting.journalentry')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_treasury_transactions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_transactions', to='companies.company')),
                ('counterparty_account', models.ForeignKey(blank=True, help_text='Used for internal transfers between treasury accounts.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_transactions', to='treasury.treasuryaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treasury_transactions', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_treasury_transactions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_treasury_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Treasury Transaction',
                'verbose_name_plural': 'Treasury Transactions',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='treasuryaccount',
            index=models.Index(fields=['company', 'account_type'], name='treasury_tr_company_407e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='treasuryaccount',
            index=models.Index(fields=['company', 'status'], name='treasury_tr_company_ddd35c_idx'),
        ),
        migrations.AddIndex(
            model_name='treasuryaccount',
            index=models.Index(fields=['company', 'is_default'], name='treasury_tr_company_4d40cf_idx'),
        ),
        migrations.AddIndex(
            model_name='treasuryaccount',
            index=models.Index(fields=['company', 'code'], name='treasury_tr_company_84ac30_idx'),
        ),
        migrations.AddConstraint(
            model_name='treasuryaccount',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_treasury_account_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='treasuryaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('company', 'code'), name='unique_treasury_account_code_per_company_when_present'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['company', 'transaction_type'], name='treasury_tr_company_33f3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['company', 'status'], name='treasury_tr_company_533372_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['company', 'source_type'], name='treasury_tr_company_3db4fa_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['company', 'transaction_date'], name='treasury_tr_company_9daf0c_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['company', 'transaction_number'], name='treasury_tr_company_801493_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['company', 'reference'], name='treasury_tr_company_28b53c_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransaction',
            index=models.Index(fields=['source_app', 'source_model', 'source_object_id'], name='treasury_tr_source__c1d0ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='treasurytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_number', ''), _negated=True), fields=('company', 'transaction_number'), name='unique_treasury_transaction_number_per_company_when_present'),
        ),
        migrations.AddConstraint(
            model_name='treasurytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('source_object_id__isnull', False)), fields=('company', 'source_type', 'source_app', 'source_model', 'source_object_id'), name='unique_treasury_transaction_source_per_company_when_present'),
        ),
    ]
