# Generated by Django 6.0.6 on 2026-06-08 21:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('companies', '0003_branch_companysettings'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        ('treasury', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(blank=True, max_length=80)),
                ('customer_id', models.PositiveBigIntegerField(blank=True, db_index=True, help_text='Flexible party/customer id until parties model is finalized for direct FK.', null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card'), ('WALLET', 'Wallet'), ('CHECK', 'Check'), ('OTHER', 'Other')], db_index=True, default='CASH', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('is_accounting_posted', models.BooleanField(db_index=True, default=False)),
                ('accounting_posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payments', to='accounting.journalentry')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_customer_payments', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to='companies.company')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_customer_payments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_payments', to=settings.AUTH_USER_MODEL)),
                ('sales_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to='sales.salesinvoice')),
                ('treasury_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to='treasury.treasuryaccount')),
                ('treasury_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payment', to='treasury.treasurytransaction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_customer_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Payment',
                'verbose_name_plural': 'Customer Payments',
                'ordering': ['-payment_date', '-id'],
                'indexes': [models.Index(fields=['company', 'status'], name='treasury_cu_company_45f025_idx'), models.Index(fields=['company', 'payment_method'], name='treasury_cu_company_6a47c8_idx'), models.Index(fields=['company', 'payment_date'], name='treasury_cu_company_a7f98f_idx'), models.Index(fields=['company', 'payment_number'], name='treasury_cu_company_473a3c_idx'), models.Index(fields=['company', 'reference'], name='treasury_cu_company_f5f52d_idx'), models.Index(fields=['company', 'customer_id'], name='treasury_cu_company_243264_idx'), models.Index(fields=['company', 'sales_invoice'], name='treasury_cu_company_44eba4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('payment_number', ''), _negated=True), fields=('company', 'payment_number'), name='unique_customer_payment_number_per_company_when_present')],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(blank=True, max_length=80)),
                ('supplier_id', models.PositiveBigIntegerField(blank=True, db_index=True, help_text='Flexible party/supplier id until parties model is finalized for direct FK.', null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('supplier_phone', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card'), ('WALLET', 'Wallet'), ('CHECK', 'Check'), ('OTHER', 'Other')], db_index=True, default='CASH', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('is_accounting_posted', models.BooleanField(db_index=True, default=False)),
                ('accounting_posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='accounting.journalentry')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_supplier_payments', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='companies.company')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_supplier_payments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_payments', to=settings.AUTH_USER_MODEL)),
                ('purchase_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='purchases.purchasebill')),
                ('treasury_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='treasury.treasuryaccount')),
                ('treasury_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payment', to='treasury.treasurytransaction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_supplier_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Payment',
                'verbose_name_plural': 'Supplier Payments',
                'ordering': ['-payment_date', '-id'],
                'indexes': [models.Index(fields=['company', 'status'], name='treasury_su_company_d37fe3_idx'), models.Index(fields=['company', 'payment_method'], name='treasury_su_company_700e09_idx'), models.Index(fields=['company', 'payment_date'], name='treasury_su_company_874ef7_idx'), models.Index(fields=['company', 'payment_number'], name='treasury_su_company_f39197_idx'), models.Index(fields=['company', 'reference'], name='treasury_su_company_94f8db_idx'), models.Index(fields=['company', 'supplier_id'], name='treasury_su_company_b26837_idx'), models.Index(fields=['company', 'purchase_bill'], name='treasury_su_company_863efb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('payment_number', ''), _negated=True), fields=('company', 'payment_number'), name='unique_supplier_payment_number_per_company_when_present')],
            },
        ),
    ]
