# Generated by Django 6.0.6 on 2026-07-07 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_taxrate_calculation_base_taxrate_is_system_and_more'),
        ('companies', '0005_seed_activity_profiles'),
        ('treasury', '0002_customerpayment_supplierpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryaccount',
            name='accounting_account',
            field=models.ForeignKey(blank=True, help_text='Linked posting account in the company chart of accounts.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_accounts', to='accounting.account'),
        ),
        migrations.AddIndex(
            model_name='treasuryaccount',
            index=models.Index(fields=['company', 'accounting_account'], name='treasury_tr_company_4ff58c_idx'),
        ),
    ]
