# Generated by Django 6.0.6 on 2026-07-07 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_taxrate_calculation_base_taxrate_is_system_and_more'),
        ('companies', '0005_seed_activity_profiles'),
        ('treasury', '0003_link_treasury_account_to_accounting_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryaccount',
            name='opening_accounting_entry',
            field=models.ForeignKey(blank=True, help_text='Auto-posted opening balance journal entry for this treasury account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_opening_accounts', to='accounting.journalentry'),
        ),
        migrations.AddIndex(
            model_name='treasuryaccount',
            index=models.Index(fields=['company', 'opening_accounting_entry'], name='treasury_tr_company_fe6af8_idx'),
        ),
    ]
