# Generated by Django 6.0.6 on 2026-07-08 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_taxrate_calculation_base_taxrate_is_system_and_more'),
        ('treasury', '0004_add_treasury_opening_accounting_entry_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='counterparty_account',
            field=models.ForeignKey(blank=True, help_text='Receipt voucher accounting account for employee/other counterparty posting.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments_as_counterparty', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='counterparty_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='Receipt voucher flexible counterparty id.', null=True),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='counterparty_name',
            field=models.CharField(blank=True, help_text='Receipt voucher counterparty display name snapshot.', max_length=255),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='counterparty_phone',
            field=models.CharField(blank=True, help_text='Receipt voucher counterparty phone snapshot.', max_length=40),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='counterparty_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('EMPLOYEE', 'Employee'), ('OTHER', 'Other')], db_index=True, default='CUSTOMER', help_text='Receipt voucher counterparty type.', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='counterparty_account',
            field=models.ForeignKey(blank=True, help_text='Payment voucher accounting account for employee/other counterparty posting.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments_as_counterparty', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='counterparty_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='Payment voucher flexible counterparty id.', null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='counterparty_name',
            field=models.CharField(blank=True, help_text='Payment voucher counterparty display name snapshot.', max_length=255),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='counterparty_phone',
            field=models.CharField(blank=True, help_text='Payment voucher counterparty phone snapshot.', max_length=40),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='counterparty_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('EMPLOYEE', 'Employee'), ('OTHER', 'Other')], db_index=True, default='SUPPLIER', help_text='Payment voucher counterparty type.', max_length=20),
        ),
    ]
