# Generated by Django 6.0.6 on 2026-09-19 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_onboarding_lifecycle'),
        ('treasury', '0005_add_payment_counterparty_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to='companies.branch'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='companies.branch'),
        ),
    ]
