# Generated by Django 6.0.6 on 2026-06-06 07:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_company_building_number_company_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الباقة')),
                ('code', models.CharField(choices=[('STARTER', 'Starter'), ('BASIC', 'Basic'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise'), ('CUSTOM', 'Custom')], db_index=True, default='BASIC', max_length=50, verbose_name='كود الباقة')),
                ('slug', models.SlugField(help_text='يستخدم داخليًا وفي روابط الواجهة مثل basic أو professional.', max_length=160, unique=True, verbose_name='معرّف الباقة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الباقة')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='السعر الشهري')),
                ('yearly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='السعر السنوي')),
                ('max_users', models.PositiveIntegerField(default=1, verbose_name='الحد الأقصى للمستخدمين')),
                ('max_branches', models.PositiveIntegerField(default=1, verbose_name='الحد الأقصى للفروع')),
                ('max_warehouses', models.PositiveIntegerField(default=0, verbose_name='الحد الأقصى للمستودعات')),
                ('max_pos', models.PositiveIntegerField(default=0, verbose_name='الحد الأقصى لنقاط البيع')),
                ('features', models.JSONField(blank=True, default=list, help_text='قائمة مميزات الباقة بصيغة JSON.', verbose_name='مميزات الباقة')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشطة')),
                ('is_public', models.BooleanField(db_index=True, default=True, help_text='إذا كانت غير ظاهرة، يمكن استخدامها داخليًا فقط من النظام.', verbose_name='ظاهرة للاشتراك')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتيب الظهور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'باقة اشتراك',
                'verbose_name_plural': 'باقات الاشتراك',
                'ordering': ['sort_order', 'monthly_price', 'id'],
                'indexes': [models.Index(fields=['is_active', 'is_public'], name='subscriptio_is_acti_95f0ec_idx'), models.Index(fields=['code'], name='subscriptio_code_d07513_idx'), models.Index(fields=['slug'], name='subscriptio_slug_3cc181_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('SUSPENDED', 'Suspended')], db_index=True, default='TRIAL', max_length=20, verbose_name='حالة الاشتراك')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], db_index=True, default='MONTHLY', max_length=20, verbose_name='دورة الفوترة')),
                ('start_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(db_index=True, verbose_name='تاريخ النهاية')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='قيمة الاشتراك')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='قيمة الخصم')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='قيمة الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الإجمالي')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='تجديد تلقائي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإيقاف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_subscriptions', to='subscriptions.subscriptionplan', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'اشتراك شركة',
                'verbose_name_plural': 'اشتراكات الشركات',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', 'status'], name='subscriptio_company_1109ee_idx'), models.Index(fields=['start_date', 'end_date'], name='subscriptio_start_d_1e437d_idx'), models.Index(fields=['billing_cycle'], name='subscriptio_billing_575772_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['TRIAL', 'ACTIVE'])), fields=('company',), name='unique_current_subscription_per_company')],
            },
        ),
    ]
