# Generated by Django 6.0.6 on 2026-06-11 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscription',
            name='action',
            field=models.CharField(choices=[('NEW', 'New'), ('RENEWAL', 'Renewal'), ('UPGRADE', 'Upgrade'), ('DOWNGRADE', 'Downgrade'), ('MANUAL', 'Manual')], db_index=True, default='NEW', max_length=20, verbose_name='نوع العملية'),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التفعيل'),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='billing_reference',
            field=models.CharField(blank=True, db_index=True, help_text='مرجع داخلي يربط الاشتراك بعملية فوترة أو فاتورة بدون ربط مباشر بمنطق الدفع.', max_length=120, verbose_name='مرجع الفوترة'),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع'),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='previous_subscription',
            field=models.ForeignKey(blank=True, help_text='يستخدم في التجديد أو تغيير الباقة بدون تعديل سجل الاشتراك القديم.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_subscriptions', to='subscriptions.companysubscription', verbose_name='الاشتراك السابق'),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('SUSPENDED', 'Suspended')], db_index=True, default='TRIAL', max_length=30, verbose_name='حالة الاشتراك'),
        ),
        migrations.AddIndex(
            model_name='companysubscription',
            index=models.Index(fields=['company', 'action'], name='subscriptio_company_d25529_idx'),
        ),
        migrations.AddIndex(
            model_name='companysubscription',
            index=models.Index(fields=['billing_reference'], name='subscriptio_billing_21f4b1_idx'),
        ),
    ]
