# Generated by Django 6.0.6 on 2026-08-23 18:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_onboarding_lifecycle'),
        ('subscriptions', '0002_companysubscription_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscription',
            name='commercial_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Commercial pricing snapshot'),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='manual_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Manual discount'),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='promotion_code',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Promotion code'),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='promotion_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Promotion discount'),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='proration_charge_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Proration charge'),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='proration_credit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Proration credit'),
        ),
        migrations.CreateModel(
            name='SubscriptionPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(db_index=True, max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed amount')], db_index=True, default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('maximum_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('billing_cycle', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], db_index=True, help_text='Blank means all billing cycles.', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, null=True)),
                ('max_redemptions_per_company', models.PositiveIntegerField(default=1)),
                ('redemption_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscription_promotions', to=settings.AUTH_USER_MODEL)),
                ('plans', models.ManyToManyField(blank=True, help_text='Empty means all eligible plans.', related_name='subscription_promotions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-is_active', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPromotionRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('redeemed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_promotion_redemptions', to='companies.company')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='subscriptions.subscriptionpromotion')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_promotion_redemptions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_redemption', to='subscriptions.companysubscription')),
            ],
            options={
                'ordering': ['-redeemed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='subscriptionpromotion',
            index=models.Index(fields=['is_active', 'code'], name='sub_promo_active_code_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpromotion',
            index=models.Index(fields=['starts_at', 'ends_at'], name='sub_promo_window_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpromotionredemption',
            index=models.Index(fields=['promotion', 'company'], name='sub_promo_red_company_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpromotionredemption',
            index=models.Index(fields=['company', 'redeemed_at'], name='sub_promo_red_time_idx'),
        ),
    ]
