# Generated by Django 6.0.6 on 2026-06-06 20:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_branch_companysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20)),
                ('code', models.CharField(blank=True, db_index=True, default='', help_text='Optional category code unique per company when provided.', max_length=50)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_ar', models.CharField(blank=True, default='', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_categories', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_catalog_categories', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.catalogcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_catalog_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catalog Category',
                'verbose_name_plural': 'Catalog Categories',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20)),
                ('code', models.CharField(blank=True, db_index=True, default='', help_text='Optional unit code unique per company when provided.', max_length=50)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('name_ar', models.CharField(blank=True, default='', max_length=120)),
                ('name_en', models.CharField(blank=True, default='', max_length=120)),
                ('symbol', models.CharField(blank=True, default='', help_text='Short unit symbol such as pcs, kg, h.', max_length=30)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, help_text='Allowed decimal places for quantities using this unit.')),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_units', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_catalog_units', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_catalog_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catalog Unit',
                'verbose_name_plural': 'Catalog Units',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service')], db_index=True, default='PRODUCT', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20)),
                ('code', models.CharField(blank=True, db_index=True, default='', help_text='Optional internal item code unique per company when provided.', max_length=50)),
                ('sku', models.CharField(blank=True, db_index=True, default='', help_text='Optional SKU unique per company when provided.', max_length=80)),
                ('barcode', models.CharField(blank=True, db_index=True, default='', help_text='Optional barcode unique per company when provided.', max_length=120)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_ar', models.CharField(blank=True, default='', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_sellable', models.BooleanField(db_index=True, default=True)),
                ('is_purchasable', models.BooleanField(db_index=True, default=True)),
                ('track_inventory', models.BooleanField(db_index=True, default=False, help_text='Inventory tracking will be handled in later phases.')),
                ('taxable', models.BooleanField(db_index=True, default=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='VAT/tax percentage for this item.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/items/')),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='catalog.catalogcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_catalog_items', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_catalog_items', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='catalog.catalogunit')),
            ],
            options={
                'verbose_name': 'Catalog Item',
                'verbose_name_plural': 'Catalog Items',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='catalogcategory',
            index=models.Index(fields=['company', 'status'], name='catalog_cat_company_ebcc23_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogcategory',
            index=models.Index(fields=['company', 'name'], name='catalog_cat_company_92891c_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogcategory',
            index=models.Index(fields=['company', 'parent'], name='catalog_cat_company_c71458_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogcategory',
            index=models.Index(fields=['company', 'sort_order'], name='catalog_cat_company_f4dc1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('company', 'code'), name='unique_catalog_category_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='catalogcategory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_catalog_category_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='catalogunit',
            index=models.Index(fields=['company', 'status'], name='catalog_cat_company_0ce903_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogunit',
            index=models.Index(fields=['company', 'name'], name='catalog_cat_company_74be87_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogunit',
            index=models.Index(fields=['company', 'is_default'], name='catalog_cat_company_beceb4_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogunit',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('company', 'code'), name='unique_catalog_unit_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='catalogunit',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_catalog_unit_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['company', 'status'], name='catalog_cat_company_6c9955_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['company', 'item_type'], name='catalog_cat_company_054785_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['company', 'category'], name='catalog_cat_company_c91058_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['company', 'unit'], name='catalog_cat_company_9097a6_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['company', 'is_sellable'], name='catalog_cat_company_fc4ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['company', 'is_purchasable'], name='catalog_cat_company_6c7280_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['company', 'track_inventory'], name='catalog_cat_company_7b4901_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['company', 'taxable'], name='catalog_cat_company_c84c67_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['company', 'name'], name='catalog_cat_company_f42cab_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['company', 'created_at'], name='catalog_cat_company_068d60_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('company', 'code'), name='unique_catalog_item_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('company', 'sku'), name='unique_catalog_item_sku_per_company'),
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('company', 'barcode'), name='unique_catalog_item_barcode_per_company'),
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_catalog_item_name_per_company'),
        ),
    ]
