# Generated by Django 6.0.6 on 2026-06-17 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='inventory_tracking_method',
            field=models.CharField(choices=[('NONE', 'No batch or serial tracking'), ('BATCH', 'Batch / Lot tracking'), ('SERIAL', 'Serial number tracking')], db_index=True, default='NONE', help_text='Defines whether inventory is tracked without details, by batch/lot, or by individual serial number.', max_length=20),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='track_expiry_dates',
            field=models.BooleanField(db_index=True, default=False, help_text='Enable manufacturing and expiry date tracking. Available only for batch-tracked products.'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='track_inventory',
            field=models.BooleanField(db_index=True, default=False, help_text='Enable stock quantity tracking for this product.'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['company', 'inventory_tracking_method'], name='catalog_cat_company_dc8f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['company', 'track_expiry_dates'], name='catalog_cat_company_8f3024_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['company', 'track_inventory', 'inventory_tracking_method'], name='catalog_cat_company_95dc8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.CheckConstraint(condition=models.Q(('item_type', 'PRODUCT'), models.Q(('track_inventory', False), ('inventory_tracking_method', 'NONE'), ('track_expiry_dates', False)), _connector='OR'), name='catalog_service_inventory_tracking_disabled'),
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.CheckConstraint(condition=models.Q(('track_inventory', True), models.Q(('inventory_tracking_method', 'NONE'), ('track_expiry_dates', False)), _connector='OR'), name='catalog_tracking_requires_inventory'),
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.CheckConstraint(condition=models.Q(('track_expiry_dates', False), ('inventory_tracking_method', 'BATCH'), _connector='OR'), name='catalog_expiry_requires_batch_tracking'),
        ),
    ]
