# Generated by Django 6.0.6 on 2026-06-24 05:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_index=True, max_length=80)),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('label_ar', models.CharField(max_length=180)),
                ('label_en', models.CharField(max_length=180)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('json', 'JSON'), ('url', 'URL'), ('email', 'Email')], default='string', max_length=20)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('default_value_json', models.JSONField(blank=True, default=dict)),
                ('validation_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_system_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group', 'sort_order', 'key'],
                'indexes': [models.Index(fields=['group', 'key'], name='settings_ce_group_b1f02e_idx'), models.Index(fields=['is_active', 'is_public'], name='settings_ce_is_acti_80c3f1_idx')],
                'constraints': [models.UniqueConstraint(fields=('group', 'key'), name='unique_system_setting_group_key')],
            },
        ),
    ]
