# Generated by Django 6.0.6 on 2026-06-10 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_branch_companysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Template name')),
                ('code', models.CharField(db_index=True, help_text='Unique per company.', max_length=100, verbose_name='Template code')),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('SALES', 'Sales'), ('PURCHASES', 'Purchases'), ('TREASURY', 'Treasury'), ('POS', 'POS'), ('ACCOUNTING', 'Accounting'), ('INVENTORY', 'Inventory'), ('CUSTOMER_SERVICE', 'Customer Service')], db_index=True, default='GENERAL', max_length=50, verbose_name='Category')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=30, verbose_name='Status')),
                ('language', models.CharField(db_index=True, default='ar', max_length=20, verbose_name='Language')),
                ('body', models.TextField(help_text='Supports placeholders such as {{customer_name}} and {{invoice_number}}.', verbose_name='Template body')),
                ('footer', models.CharField(blank=True, max_length=255, verbose_name='Footer')),
                ('external_template_name', models.CharField(blank=True, help_text='Used later if approved provider templates are required.', max_length=150, verbose_name='External template name')),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of placeholders expected by this template.', verbose_name='Variables')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_whatsapp_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_whatsapp_templates', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'WhatsApp template',
                'verbose_name_plural': 'WhatsApp templates',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('INBOUND', 'Inbound')], db_index=True, default='OUTBOUND', max_length=30, verbose_name='Direction')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30, verbose_name='Status')),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('SALES_INVOICE', 'Sales Invoice'), ('PURCHASE_BILL', 'Purchase Bill'), ('CUSTOMER_PAYMENT', 'Customer Payment'), ('SUPPLIER_PAYMENT', 'Supplier Payment'), ('POS_ORDER', 'POS Order'), ('POS_RETURN', 'POS Return'), ('INVENTORY_MOVEMENT', 'Inventory Movement'), ('SYSTEM', 'System')], db_index=True, default='MANUAL', max_length=50, verbose_name='Source type')),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Source ID')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='Recipient name')),
                ('recipient_phone', models.CharField(db_index=True, max_length=50, verbose_name='Recipient phone')),
                ('message_body', models.TextField(verbose_name='Message body')),
                ('rendered_variables', models.JSONField(blank=True, default=dict, verbose_name='Rendered variables')),
                ('provider', models.CharField(choices=[('MOCK', 'Mock'), ('WHATSAPP_CLOUD', 'WhatsApp Cloud API'), ('CUSTOM', 'Custom Provider')], db_index=True, default='MOCK', max_length=50, verbose_name='Provider')),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Provider message ID')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='Provider response')),
                ('error_message', models.TextField(blank=True, verbose_name='Error message')),
                ('queued_at', models.DateTimeField(blank=True, null=True, verbose_name='Queued at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read at')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Failed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_message_logs', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_whatsapp_message_logs', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='whatsapp.whatsapptemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'WhatsApp message log',
                'verbose_name_plural': 'WhatsApp message logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyWhatsAppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(db_index=True, default=False, verbose_name='Enabled')),
                ('provider', models.CharField(choices=[('MOCK', 'Mock'), ('WHATSAPP_CLOUD', 'WhatsApp Cloud API'), ('CUSTOM', 'Custom Provider')], db_index=True, default='MOCK', max_length=50, verbose_name='Provider')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='WhatsApp phone number')),
                ('phone_number_id', models.CharField(blank=True, help_text='Used by WhatsApp Cloud API when enabled later.', max_length=150, verbose_name='Phone number ID')),
                ('business_account_id', models.CharField(blank=True, max_length=150, verbose_name='Business account ID')),
                ('access_token', models.TextField(blank=True, help_text='Foundation only. Encrypt or move to secrets manager before production use.', verbose_name='Access token')),
                ('webhook_verify_token', models.CharField(blank=True, max_length=255, verbose_name='Webhook verify token')),
                ('default_country_code', models.CharField(default='+966', max_length=10, verbose_name='Default country code')),
                ('send_invoice_notifications', models.BooleanField(default=True, verbose_name='Send invoice notifications')),
                ('send_payment_notifications', models.BooleanField(default=True, verbose_name='Send payment notifications')),
                ('send_pos_notifications', models.BooleanField(default=True, verbose_name='Send POS notifications')),
                ('send_system_notifications', models.BooleanField(default=True, verbose_name='Send system notifications')),
                ('provider_config', models.JSONField(blank=True, default=dict, verbose_name='Provider config')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Last verified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_setting', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_whatsapp_settings', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_whatsapp_settings', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Company WhatsApp setting',
                'verbose_name_plural': 'Company WhatsApp settings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_enabled', 'provider'], name='whatsapp_co_is_enab_5450ef_idx'), models.Index(fields=['phone_number'], name='whatsapp_co_phone_n_0457ab_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='whatsapptemplate',
            index=models.Index(fields=['company', 'status'], name='whatsapp_wh_company_5734cb_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapptemplate',
            index=models.Index(fields=['company', 'category'], name='whatsapp_wh_company_6144e7_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapptemplate',
            index=models.Index(fields=['company', 'language'], name='whatsapp_wh_company_bd7b91_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapptemplate',
            index=models.Index(fields=['company', 'code'], name='whatsapp_wh_company_72fa35_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsapptemplate',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_whatsapp_template_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['company', 'status', 'created_at'], name='whatsapp_wh_company_e92360_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['company', 'direction', 'created_at'], name='whatsapp_wh_company_0a1c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['company', 'source_type', 'source_id'], name='whatsapp_wh_company_8e49ad_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['company', 'recipient_phone'], name='whatsapp_wh_company_06d2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['company', 'provider', 'status'], name='whatsapp_wh_company_147e34_idx'),
        ),
    ]
