# Generated by Django 6.0.6 on 2026-06-26 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemWhatsAppConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, default='WEB_SESSION', max_length=50, verbose_name='Provider')),
                ('is_enabled', models.BooleanField(db_index=True, default=False, verbose_name='Enabled')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Active')),
                ('business_name', models.CharField(blank=True, max_length=150, verbose_name='Business name')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='WhatsApp phone number')),
                ('phone_number_id', models.CharField(blank=True, max_length=150, verbose_name='Phone number ID')),
                ('business_account_id', models.CharField(blank=True, max_length=150, verbose_name='Business account ID')),
                ('app_id', models.CharField(blank=True, max_length=150, verbose_name='App ID')),
                ('access_token', models.TextField(blank=True, verbose_name='Access token')),
                ('webhook_verify_token', models.CharField(blank=True, max_length=255, verbose_name='Webhook verify token')),
                ('webhook_callback_url', models.URLField(blank=True, verbose_name='Webhook callback URL')),
                ('webhook_verified', models.BooleanField(default=False, verbose_name='Webhook verified')),
                ('api_version', models.CharField(default='v22.0', max_length=50, verbose_name='API version')),
                ('default_language_code', models.CharField(default='ar', max_length=20, verbose_name='Default language code')),
                ('default_country_code', models.CharField(default='+966', max_length=10, verbose_name='Default country code')),
                ('allow_broadcasts', models.BooleanField(default=True, verbose_name='Allow broadcasts')),
                ('send_test_enabled', models.BooleanField(default=True, verbose_name='Send test enabled')),
                ('default_test_recipient', models.CharField(blank=True, max_length=50, verbose_name='Default test recipient')),
                ('session_name', models.CharField(db_index=True, default='primeyacc-system-session', max_length=150, verbose_name='Session name')),
                ('session_mode', models.CharField(choices=[('qr', 'QR'), ('pairing_code', 'Pairing Code')], default='qr', max_length=30, verbose_name='Session mode')),
                ('session_status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('qr_pending', 'QR Pending'), ('pair_pending', 'Pair Pending'), ('connected', 'Connected'), ('reconnecting', 'Reconnecting'), ('failed', 'Failed')], db_index=True, default='disconnected', max_length=30, verbose_name='Session status')),
                ('session_connected_phone', models.CharField(blank=True, max_length=50, verbose_name='Connected phone')),
                ('session_device_label', models.CharField(blank=True, max_length=150, verbose_name='Device label')),
                ('session_last_connected_at', models.DateTimeField(blank=True, null=True, verbose_name='Last connected at')),
                ('session_qr_code', models.TextField(blank=True, verbose_name='QR code')),
                ('session_pairing_code', models.CharField(blank=True, max_length=100, verbose_name='Pairing code')),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True, verbose_name='Last health check at')),
                ('last_error_message', models.TextField(blank=True, verbose_name='Last error message')),
                ('provider_config', models.JSONField(blank=True, default=dict, verbose_name='Provider config')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_system_whatsapp_connections', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_system_whatsapp_connections', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'System WhatsApp connection',
                'verbose_name_plural': 'System WhatsApp connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_enabled', 'is_active'], name='whatsapp_sy_is_enab_edbb31_idx'), models.Index(fields=['session_status'], name='whatsapp_sy_session_417984_idx'), models.Index(fields=['session_name'], name='whatsapp_sy_session_6490db_idx')],
            },
        ),
    ]
