# Generated by Django 6.0.6 on 2026-06-27 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('whatsapp', '0002_system_whatsapp_connection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SYSTEM', 'System'), ('COMPANY', 'Company')], db_index=True, default='SYSTEM', max_length=30, verbose_name='Inbox scope')),
                ('session_name', models.CharField(db_index=True, default='primeyacc-system-session', max_length=120, verbose_name='Session name')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Phone number')),
                ('normalized_phone', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Normalized phone')),
                ('whatsapp_jid', models.CharField(blank=True, db_index=True, max_length=180, verbose_name='WhatsApp JID')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Display name')),
                ('push_name', models.CharField(blank=True, max_length=255, verbose_name='WhatsApp push name')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Last seen at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_inbox_contacts', to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'WhatsApp contact',
                'verbose_name_plural': 'WhatsApp contacts',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SYSTEM', 'System'), ('COMPANY', 'Company')], db_index=True, default='SYSTEM', max_length=30, verbose_name='Inbox scope')),
                ('session_name', models.CharField(db_index=True, default='primeyacc-system-session', max_length=120, verbose_name='Session name')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived'), ('SPAM', 'Spam')], db_index=True, default='OPEN', max_length=30, verbose_name='Status')),
                ('is_pinned', models.BooleanField(db_index=True, default=False, verbose_name='Pinned')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='Resolved')),
                ('last_message_preview', models.CharField(blank=True, max_length=500, verbose_name='Last message preview')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last message at')),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name='Unread count')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_whatsapp_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_inbox_conversations', to='companies.company', verbose_name='Company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='whatsapp.whatsappcontact', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'WhatsApp conversation',
                'verbose_name_plural': 'WhatsApp conversations',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SYSTEM', 'System'), ('COMPANY', 'Company')], db_index=True, default='SYSTEM', max_length=30, verbose_name='Inbox scope')),
                ('session_name', models.CharField(db_index=True, default='primeyacc-system-session', max_length=120, verbose_name='Session name')),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('INBOUND', 'Inbound')], db_index=True, default='INBOUND', max_length=30, verbose_name='Direction')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], db_index=True, default='RECEIVED', max_length=30, verbose_name='Status')),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('STICKER', 'Sticker'), ('LOCATION', 'Location'), ('CONTACT', 'Contact'), ('UNKNOWN', 'Unknown')], db_index=True, default='TEXT', max_length=30, verbose_name='Message type')),
                ('body', models.TextField(blank=True, verbose_name='Body')),
                ('external_message_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='External message ID')),
                ('provider', models.CharField(default='WHATSAPP_GATEWAY', max_length=80, verbose_name='Provider')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='Provider response')),
                ('received_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Received at')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Sent at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_inbox_messages', to='companies.company', verbose_name='Company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappcontact', verbose_name='Contact')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappconversation', verbose_name='Conversation')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_whatsapp_inbox_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sent by')),
            ],
            options={
                'verbose_name': 'WhatsApp conversation message',
                'verbose_name_plural': 'WhatsApp conversation messages',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uid', models.CharField(max_length=255, unique=True, verbose_name='Event UID')),
                ('session_name', models.CharField(db_index=True, default='primeyacc-system-session', max_length=120, verbose_name='Session name')),
                ('event_type', models.CharField(db_index=True, default='message.incoming', max_length=80, verbose_name='Event type')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('IGNORED', 'Ignored')], db_index=True, default='RECEIVED', max_length=30, verbose_name='Status')),
                ('external_message_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='External message ID')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('error_message', models.TextField(blank=True, verbose_name='Error message')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Received at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'WhatsApp webhook event',
                'verbose_name_plural': 'WhatsApp webhook events',
                'indexes': [models.Index(fields=['session_name', 'status', 'created_at'], name='whatsapp_wh_session_d9cee1_idx'), models.Index(fields=['external_message_id'], name='whatsapp_wh_externa_746d1b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['scope', 'session_name', 'normalized_phone'], name='whatsapp_wh_scope_85e169_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['scope', 'company', 'updated_at'], name='whatsapp_wh_scope_7e44eb_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['scope', 'session_name', 'status', 'last_message_at'], name='whatsapp_wh_scope_e8d062_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['scope', 'is_pinned', 'last_message_at'], name='whatsapp_wh_scope_5c480d_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['scope', 'is_resolved', 'last_message_at'], name='whatsapp_wh_scope_e705f7_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversationmessage',
            index=models.Index(fields=['scope', 'session_name', 'direction', 'created_at'], name='whatsapp_wh_scope_bda254_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversationmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='whatsapp_wh_convers_4653f4_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversationmessage',
            index=models.Index(fields=['external_message_id'], name='whatsapp_wh_externa_73e818_idx'),
        ),
    ]
