# Generated by Django 6.0.6 on 2026-06-19 20:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_number', models.CharField(db_index=True, max_length=80)),
                ('full_name', models.CharField(db_index=True, max_length=220)),
                ('mobile', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('national_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_patients', to='companies.company')),
            ],
            options={
                'ordering': ['company_id', 'full_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_item_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=80)),
                ('name', models.CharField(db_index=True, max_length=220)),
                ('department', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('taxable', models.BooleanField(default=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_services', to='companies.company')),
            ],
            options={
                'ordering': ['company_id', 'department', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_number', models.CharField(db_index=True, max_length=80)),
                ('appointment_at', models.DateTimeField(db_index=True)),
                ('practitioner_name', models.CharField(blank=True, db_index=True, default='', max_length=180)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECKED_IN', 'Checked in'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], db_index=True, default='SCHEDULED', max_length=20)),
                ('price_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_appointments', to='companies.company')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='activity_backends.clinicpatient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='activity_backends.clinicservice')),
            ],
            options={
                'ordering': ['company_id', '-appointment_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(db_index=True, max_length=80)),
                ('name', models.CharField(db_index=True, max_length=220)),
                ('customer_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('start_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('budget_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('actual_cost_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_projects', to='companies.company')),
            ],
            options={
                'ordering': ['company_id', '-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(db_index=True, max_length=80)),
                ('title', models.CharField(db_index=True, max_length=220)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('scheduled_start', models.DateField(blank=True, db_index=True, null=True)),
                ('scheduled_end', models.DateField(blank=True, db_index=True, null=True)),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_project_work_orders', to='companies.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='activity_backends.project')),
            ],
            options={
                'ordering': ['company_id', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCostLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(db_index=True, default='MATERIAL', max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('cost_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_project_cost_lines', to='companies.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_lines', to='activity_backends.project')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_lines', to='activity_backends.projectworkorder')),
            ],
            options={
                'ordering': ['company_id', '-cost_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantKitchenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=80)),
                ('order_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to kitchen'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('SERVED', 'Served'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_kitchen_orders', to='companies.company')),
            ],
            options={
                'ordering': ['company_id', '-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantMenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=160)),
                ('name_ar', models.CharField(blank=True, default='', max_length=160)),
                ('name_en', models.CharField(blank=True, default='', max_length=160)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menu_categories', to='companies.company')),
            ],
            options={
                'ordering': ['company_id', 'sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_item_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=220)),
                ('name_ar', models.CharField(blank=True, default='', max_length=220)),
                ('name_en', models.CharField(blank=True, default='', max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('taxable', models.BooleanField(default=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('kitchen_station', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='activity_backends.restaurantmenucategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menu_items', to='companies.company')),
            ],
            options={
                'ordering': ['company_id', 'sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantKitchenOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(db_index=True, default=1)),
                ('item_name_snapshot', models.CharField(max_length=220)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_kitchen_order_items', to='companies.company')),
                ('kitchen_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='activity_backends.restaurantkitchenorder')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_order_items', to='activity_backends.restaurantmenuitem')),
            ],
            options={
                'ordering': ['kitchen_order_id', 'line_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('area', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('INACTIVE', 'Inactive')], db_index=True, default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_tables', to='companies.company')),
            ],
            options={
                'ordering': ['company_id', 'area', 'code', 'id'],
            },
        ),
        migrations.AddField(
            model_name='restaurantkitchenorder',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_orders', to='activity_backends.restauranttable'),
        ),
        migrations.AddIndex(
            model_name='clinicpatient',
            index=models.Index(fields=['company', 'mobile'], name='activity_ba_company_72a3b0_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicpatient',
            index=models.Index(fields=['company', 'full_name'], name='activity_ba_company_cb187f_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicpatient',
            index=models.Index(fields=['company', 'created_at'], name='activity_ba_company_b95ef5_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicpatient',
            constraint=models.UniqueConstraint(fields=('company', 'patient_number'), name='unique_clinic_patient_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='clinicpatient',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id', ''), _negated=True), fields=('company', 'national_id'), name='unique_clinic_patient_national_id_per_company'),
        ),
        migrations.AddIndex(
            model_name='clinicservice',
            index=models.Index(fields=['company', 'department'], name='activity_ba_company_57b313_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicservice',
            index=models.Index(fields=['company', 'is_active'], name='activity_ba_company_81e1da_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicservice',
            index=models.Index(fields=['company', 'catalog_item_id'], name='activity_ba_company_cd07f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicservice',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_clinic_service_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='clinicappointment',
            index=models.Index(fields=['company', 'patient'], name='activity_ba_company_ec4cda_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicappointment',
            index=models.Index(fields=['company', 'service'], name='activity_ba_company_4cce58_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicappointment',
            index=models.Index(fields=['company', 'status'], name='activity_ba_company_56fd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicappointment',
            index=models.Index(fields=['company', 'appointment_at'], name='activity_ba_company_9052f6_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicappointment',
            index=models.Index(fields=['company', 'practitioner_name'], name='activity_ba_company_eaaff1_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicappointment',
            constraint=models.UniqueConstraint(fields=('company', 'appointment_number'), name='unique_clinic_appointment_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'status'], name='activity_ba_company_701a04_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'start_date'], name='activity_ba_company_39d89c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'customer_id'], name='activity_ba_company_61a073_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('company', 'project_number'), name='unique_activity_project_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='projectworkorder',
            index=models.Index(fields=['company', 'project'], name='activity_ba_company_704b71_idx'),
        ),
        migrations.AddIndex(
            model_name='projectworkorder',
            index=models.Index(fields=['company', 'status'], name='activity_ba_company_152011_idx'),
        ),
        migrations.AddIndex(
            model_name='projectworkorder',
            index=models.Index(fields=['company', 'scheduled_start'], name='activity_ba_company_25229d_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectworkorder',
            constraint=models.UniqueConstraint(fields=('company', 'work_order_number'), name='unique_activity_work_order_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='projectcostline',
            index=models.Index(fields=['company', 'project'], name='activity_ba_company_993cad_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcostline',
            index=models.Index(fields=['company', 'work_order'], name='activity_ba_company_4245bd_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcostline',
            index=models.Index(fields=['company', 'cost_type'], name='activity_ba_company_a44be1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcostline',
            index=models.Index(fields=['company', 'cost_date'], name='activity_ba_company_b71ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantmenucategory',
            index=models.Index(fields=['company', 'is_active'], name='activity_ba_company_94f941_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantmenucategory',
            index=models.Index(fields=['company', 'sort_order'], name='activity_ba_company_efda34_idx'),
        ),
        migrations.AddConstraint(
            model_name='restaurantmenucategory',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_restaurant_menu_category_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='restaurantmenucategory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_restaurant_menu_category_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='restaurantmenuitem',
            index=models.Index(fields=['company', 'category'], name='activity_ba_company_478e16_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantmenuitem',
            index=models.Index(fields=['company', 'is_available'], name='activity_ba_company_a56fee_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantmenuitem',
            index=models.Index(fields=['company', 'kitchen_station'], name='activity_ba_company_384f94_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantmenuitem',
            index=models.Index(fields=['company', 'catalog_item_id'], name='activity_ba_company_00ff31_idx'),
        ),
        migrations.AddConstraint(
            model_name='restaurantmenuitem',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_restaurant_menu_item_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='restaurantkitchenorderitem',
            index=models.Index(fields=['company', 'menu_item'], name='activity_ba_company_a10dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantkitchenorderitem',
            index=models.Index(fields=['company', 'created_at'], name='activity_ba_company_11c7b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='restaurantkitchenorderitem',
            constraint=models.UniqueConstraint(fields=('kitchen_order', 'line_number'), name='unique_restaurant_kitchen_order_item_line'),
        ),
        migrations.AddIndex(
            model_name='restauranttable',
            index=models.Index(fields=['company', 'status'], name='activity_ba_company_14f2fe_idx'),
        ),
        migrations.AddIndex(
            model_name='restauranttable',
            index=models.Index(fields=['company', 'area'], name='activity_ba_company_f983a9_idx'),
        ),
        migrations.AddIndex(
            model_name='restauranttable',
            index=models.Index(fields=['company', 'is_active'], name='activity_ba_company_521111_idx'),
        ),
        migrations.AddConstraint(
            model_name='restauranttable',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_restaurant_table_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='restaurantkitchenorder',
            index=models.Index(fields=['company', 'status'], name='activity_ba_company_f4eac1_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantkitchenorder',
            index=models.Index(fields=['company', 'order_date'], name='activity_ba_company_6987b8_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantkitchenorder',
            index=models.Index(fields=['company', 'table'], name='activity_ba_company_a79dbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='restaurantkitchenorder',
            constraint=models.UniqueConstraint(fields=('company', 'order_number'), name='unique_restaurant_kitchen_order_number_per_company'),
        ),
    ]
