# Generated by Django 6.0.6 on 2026-09-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_backends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clinicappointment',
            name='activity_ba_company_ec4cda_idx',
        ),
        migrations.RemoveIndex(
            model_name='clinicappointment',
            name='activity_ba_company_4cce58_idx',
        ),
        migrations.RemoveIndex(
            model_name='clinicappointment',
            name='activity_ba_company_56fd7d_idx',
        ),
        migrations.RemoveIndex(
            model_name='clinicappointment',
            name='activity_ba_company_9052f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='clinicappointment',
            name='activity_ba_company_eaaff1_idx',
        ),
        migrations.RemoveConstraint(
            model_name='clinicappointment',
            name='unique_clinic_appointment_number_per_company',
        ),
        migrations.RemoveIndex(
            model_name='clinicpatient',
            name='activity_ba_company_72a3b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='clinicpatient',
            name='activity_ba_company_cb187f_idx',
        ),
        migrations.RemoveIndex(
            model_name='clinicpatient',
            name='activity_ba_company_b95ef5_idx',
        ),
        migrations.RemoveConstraint(
            model_name='clinicpatient',
            name='unique_clinic_patient_number_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='clinicpatient',
            name='unique_clinic_patient_national_id_per_company',
        ),
        migrations.RemoveIndex(
            model_name='clinicservice',
            name='activity_ba_company_57b313_idx',
        ),
        migrations.RemoveIndex(
            model_name='clinicservice',
            name='activity_ba_company_81e1da_idx',
        ),
        migrations.RemoveIndex(
            model_name='clinicservice',
            name='activity_ba_company_cd07f1_idx',
        ),
        migrations.RemoveConstraint(
            model_name='clinicservice',
            name='unique_clinic_service_code_per_company',
        ),
        migrations.RemoveField(
            model_name='clinicpatient',
            name='company',
        ),
        migrations.RemoveField(
            model_name='clinicservice',
            name='company',
        ),
        migrations.DeleteModel(
            name='ClinicAppointment',
        ),
        migrations.DeleteModel(
            name='ClinicPatient',
        ),
        migrations.DeleteModel(
            name='ClinicService',
        ),
    ]
