# Generated by Django 6.0.6 on 2026-06-08 09:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_branch_companysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحساب')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='اسم الحساب بالإنجليزية')),
                ('code', models.CharField(max_length=50, verbose_name='كود الحساب')),
                ('account_type', models.CharField(choices=[('ASSET', 'أصل'), ('LIABILITY', 'التزام'), ('EQUITY', 'حقوق ملكية'), ('REVENUE', 'إيراد'), ('EXPENSE', 'مصروف')], max_length=20, verbose_name='نوع الحساب')),
                ('nature', models.CharField(choices=[('DEBIT', 'مدين'), ('CREDIT', 'دائن')], max_length=10, verbose_name='طبيعة الحساب')),
                ('purpose', models.CharField(choices=[('ACCOUNTS_RECEIVABLE', 'ذمم العملاء'), ('ACCOUNTS_PAYABLE', 'ذمم الموردين'), ('CASH', 'الصندوق'), ('BANK', 'البنك'), ('INVENTORY', 'المخزون'), ('SALES_REVENUE', 'إيرادات المبيعات'), ('SERVICE_REVENUE', 'إيرادات الخدمات'), ('OTHER_REVENUE', 'إيرادات أخرى'), ('OUTPUT_VAT', 'ضريبة مخرجات'), ('INPUT_VAT', 'ضريبة مدخلات'), ('VAT_PAYABLE', 'ضريبة مستحقة'), ('DISCOUNT_ALLOWED', 'خصم مسموح'), ('DISCOUNT_EARNED', 'خصم مكتسب'), ('COST_OF_SALES', 'تكلفة المبيعات'), ('INVENTORY_ADJUSTMENT', 'تسوية مخزون'), ('EXPENSE', 'مصروف'), ('GATEWAY_FEES', 'رسوم بوابة دفع'), ('ROUNDING', 'فروقات تقريب'), ('OPENING_EQUITY', 'حقوق أرصدة افتتاحية'), ('SUSPENSE', 'حساب معلق'), ('OTHER', 'أخرى')], db_index=True, default='OTHER', max_length=80, verbose_name='الغرض المحاسبي')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='المستوى')),
                ('is_group', models.BooleanField(default=False, verbose_name='حساب تجميعي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_system', models.BooleanField(default=False, verbose_name='حساب نظامي')),
                ('allow_manual_posting', models.BooleanField(default=True, verbose_name='السماح بالترحيل اليدوي')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الرصيد الافتتاحي')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_accounts', to='companies.company', verbose_name='الشركة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account', verbose_name='الحساب الأب')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'دليل الحسابات',
                'db_table': 'accounting_accounts',
                'ordering': ['company_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم مركز التكلفة')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='اسم مركز التكلفة بالإنجليزية')),
                ('code', models.CharField(max_length=50, verbose_name='كود مركز التكلفة')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='المستوى')),
                ('is_group', models.BooleanField(default=False, verbose_name='مركز تكلفة تجميعي')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('INACTIVE', 'غير نشط')], default='ACTIVE', max_length=20, verbose_name='الحالة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='companies.company', verbose_name='الشركة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.costcenter', verbose_name='مركز التكلفة الأب')),
            ],
            options={
                'verbose_name': 'مركز تكلفة',
                'verbose_name_plural': 'مراكز التكلفة',
                'db_table': 'accounting_cost_centers',
                'ordering': ['company_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم السنة المالية')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('CLOSED', 'مغلقة'), ('ARCHIVED', 'مؤرشفة')], default='OPEN', max_length=20, verbose_name='الحالة')),
                ('is_current', models.BooleanField(default=False, verbose_name='السنة الحالية')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='companies.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'سنة مالية',
                'verbose_name_plural': 'السنوات المالية',
                'db_table': 'accounting_fiscal_years',
                'ordering': ['company_id', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفترة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('CLOSED', 'مغلقة'), ('LOCKED', 'مقفلة')], default='OPEN', max_length=20, verbose_name='الحالة')),
                ('is_adjustment_period', models.BooleanField(default=False, verbose_name='فترة تسويات')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_periods', to='companies.company', verbose_name='الشركة')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='accounting.fiscalyear', verbose_name='السنة المالية')),
            ],
            options={
                'verbose_name': 'فترة محاسبية',
                'verbose_name_plural': 'الفترات المحاسبية',
                'db_table': 'accounting_periods',
                'ordering': ['company_id', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=100, verbose_name='رقم القيد')),
                ('entry_date', models.DateField(verbose_name='تاريخ القيد')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحل'), ('CANCELLED', 'ملغي'), ('REVERSED', 'معكوس')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('posting_source', models.CharField(choices=[('MANUAL', 'يدوي'), ('OPENING_BALANCE', 'رصيد افتتاحي'), ('SALES_INVOICE', 'فاتورة مبيعات'), ('SALES_PAYMENT', 'تحصيل مبيعات'), ('PURCHASE_BILL', 'فاتورة مشتريات'), ('SUPPLIER_PAYMENT', 'سداد مورد'), ('INVENTORY_RECEIPT', 'استلام مخزون'), ('INVENTORY_ISSUE', 'صرف مخزون'), ('INVENTORY_ADJUSTMENT', 'تسوية مخزون'), ('INVENTORY_TRANSFER', 'تحويل مخزون'), ('TREASURY', 'خزينة'), ('TREASURY_RECEIPT', 'سند قبض'), ('TREASURY_PAYMENT', 'سند صرف'), ('TREASURY_TRANSFER', 'تحويل خزينة'), ('TAX', 'ضريبة'), ('ADJUSTMENT', 'تسوية'), ('SYSTEM', 'نظام'), ('OTHER', 'أخرى')], default='MANUAL', max_length=40, verbose_name='مصدر القيد')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='مرجع')),
                ('external_reference', models.CharField(blank=True, max_length=255, verbose_name='مرجع خارجي')),
                ('source_type', models.CharField(blank=True, max_length=80, verbose_name='نوع المصدر')),
                ('source_id', models.CharField(blank=True, max_length=80, verbose_name='معرف المصدر')),
                ('source_number', models.CharField(blank=True, max_length=120, verbose_name='رقم المصدر')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('is_auto_posted', models.BooleanField(default=False, verbose_name='قيد آلي')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الترحيل')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ العكس')),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='إجمالي المدين')),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='إجمالي الدائن')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_Mhamcloud_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='ألغي بواسطة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_Mhamcloud_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.accountingperiod', verbose_name='الفترة المحاسبية')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_Mhamcloud_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='رحل بواسطة')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_entries', to='accounting.journalentry', verbose_name='عكس القيد')),
                ('reversed_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_reversed_entries', to='accounting.journalentry', verbose_name='القيد العكسي')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_Mhamcloud_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'قيود اليومية',
                'db_table': 'accounting_journal_entries',
                'ordering': ['company_id', '-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='كود الضريبة')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الضريبة')),
                ('tax_type', models.CharField(choices=[('VAT', 'ضريبة القيمة المضافة'), ('WITHHOLDING', 'ضريبة استقطاع'), ('ZAKAT', 'زكاة'), ('OTHER', 'أخرى')], default='VAT', max_length=20, verbose_name='نوع الضريبة')),
                ('direction', models.CharField(choices=[('OUTPUT', 'ضريبة مبيعات'), ('INPUT', 'ضريبة مشتريات'), ('SETTLEMENT', 'تسوية ضريبية')], default='OUTPUT', max_length=20, verbose_name='اتجاه الضريبة')),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('15.0000'), max_digits=7, verbose_name='النسبة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='companies.company', verbose_name='الشركة')),
                ('purchase_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_purchase_rates', to='accounting.account', verbose_name='حساب ضريبة المشتريات')),
                ('sales_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_sales_rates', to='accounting.account', verbose_name='حساب ضريبة المبيعات')),
            ],
            options={
                'verbose_name': 'ضريبة',
                'verbose_name_plural': 'الضرائب',
                'db_table': 'accounting_tax_rates',
                'ordering': ['company_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='مدين')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='دائن')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='مبلغ الضريبة')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('party_type', models.CharField(blank=True, max_length=80, verbose_name='نوع الطرف')),
                ('party_id', models.CharField(blank=True, max_length=80, verbose_name='معرف الطرف')),
                ('source_line_id', models.CharField(blank=True, max_length=120, verbose_name='معرف السطر من المصدر')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب السطر')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry_lines', to='companies.company', verbose_name='الشركة')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='accounting.costcenter', verbose_name='مركز التكلفة')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='القيد')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='accounting.taxrate', verbose_name='الضريبة')),
            ],
            options={
                'verbose_name': 'سطر قيد',
                'verbose_name_plural': 'أسطر القيود',
                'db_table': 'accounting_journal_entry_lines',
                'ordering': ['company_id', 'journal_entry', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة الافتراضية')),
                ('auto_post_sales', models.BooleanField(default=True, verbose_name='ترحيل المبيعات تلقائيًا')),
                ('auto_post_purchases', models.BooleanField(default=True, verbose_name='ترحيل المشتريات تلقائيًا')),
                ('auto_post_inventory', models.BooleanField(default=False, verbose_name='ترحيل المخزون تلقائيًا')),
                ('auto_post_treasury', models.BooleanField(default=False, verbose_name='ترحيل الخزينة تلقائيًا')),
                ('require_period_for_posting', models.BooleanField(default=False, verbose_name='إلزام الفترة عند الترحيل')),
                ('allow_posting_without_cost_center', models.BooleanField(default=True, verbose_name='السماح بالترحيل بدون مركز تكلفة')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_settings', to='companies.company', verbose_name='الشركة')),
                ('default_tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_in_settings', to='accounting.taxrate', verbose_name='الضريبة الافتراضية')),
            ],
            options={
                'verbose_name': 'إعدادات المحاسبة',
                'verbose_name_plural': 'إعدادات المحاسبة',
                'db_table': 'accounting_settings',
            },
        ),
        migrations.CreateModel(
            name='AccountingRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('SALES_INVOICE', 'فاتورة مبيعات'), ('SALES_PAYMENT', 'تحصيل مبيعات'), ('PURCHASE_BILL', 'فاتورة مشتريات'), ('SUPPLIER_PAYMENT', 'سداد مورد'), ('INVENTORY_RECEIPT', 'استلام مخزون'), ('INVENTORY_ISSUE', 'صرف مخزون'), ('INVENTORY_ADJUSTMENT', 'تسوية مخزون'), ('INVENTORY_TRANSFER', 'تحويل مخزون'), ('TREASURY_INCOME', 'قبض خزينة'), ('TREASURY_EXPENSE', 'صرف خزينة'), ('TREASURY_TRANSFER', 'تحويل خزينة'), ('TAX_SETTLEMENT', 'تسوية ضريبية'), ('OPENING_BALANCE', 'رصيد افتتاحي'), ('OTHER', 'أخرى')], max_length=50, verbose_name='مصدر العملية')),
                ('purpose', models.CharField(choices=[('ACCOUNTS_RECEIVABLE', 'ذمم العملاء'), ('ACCOUNTS_PAYABLE', 'ذمم الموردين'), ('CASH', 'الصندوق'), ('BANK', 'البنك'), ('INVENTORY', 'المخزون'), ('SALES_REVENUE', 'إيرادات المبيعات'), ('SERVICE_REVENUE', 'إيرادات الخدمات'), ('OTHER_REVENUE', 'إيرادات أخرى'), ('OUTPUT_VAT', 'ضريبة مخرجات'), ('INPUT_VAT', 'ضريبة مدخلات'), ('VAT_PAYABLE', 'ضريبة مستحقة'), ('DISCOUNT_ALLOWED', 'خصم مسموح'), ('DISCOUNT_EARNED', 'خصم مكتسب'), ('COST_OF_SALES', 'تكلفة المبيعات'), ('INVENTORY_ADJUSTMENT', 'تسوية مخزون'), ('EXPENSE', 'مصروف'), ('GATEWAY_FEES', 'رسوم بوابة دفع'), ('ROUNDING', 'فروقات تقريب'), ('OPENING_EQUITY', 'حقوق أرصدة افتتاحية'), ('SUSPENSE', 'حساب معلق'), ('OTHER', 'أخرى')], max_length=80, verbose_name='الغرض المحاسبي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='الأولوية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_rules', to='accounting.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_routing_rules', to='companies.company', verbose_name='الشركة')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules', to='accounting.costcenter', verbose_name='مركز التكلفة')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules', to='accounting.taxrate', verbose_name='الضريبة')),
            ],
            options={
                'verbose_name': 'قاعدة توجيه محاسبي',
                'verbose_name_plural': 'قواعد التوجيه المحاسبي',
                'db_table': 'accounting_routing_rules',
                'ordering': ['company_id', 'source', 'purpose', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('OUTPUT', 'ضريبة مبيعات'), ('INPUT', 'ضريبة مشتريات'), ('SETTLEMENT', 'تسوية ضريبية')], max_length=20, verbose_name='اتجاه الضريبة')),
                ('transaction_date', models.DateField(verbose_name='تاريخ الحركة')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='المبلغ الخاضع للضريبة')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='مبلغ الضريبة')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('source_type', models.CharField(blank=True, max_length=80, verbose_name='نوع المصدر')),
                ('source_id', models.CharField(blank=True, max_length=80, verbose_name='معرف المصدر')),
                ('source_number', models.CharField(blank=True, max_length=120, verbose_name='رقم المصدر')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_transactions', to='companies.company', verbose_name='الشركة')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_transactions', to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('journal_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_transactions', to='accounting.journalentryline', verbose_name='سطر القيد')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_transactions', to='accounting.taxrate', verbose_name='الضريبة')),
            ],
            options={
                'verbose_name': 'حركة ضريبية',
                'verbose_name_plural': 'الحركات الضريبية',
                'db_table': 'accounting_tax_transactions',
                'ordering': ['company_id', '-transaction_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'code'], name='accounting__company_3fd3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'account_type'], name='accounting__company_95bc80_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'nature'], name='accounting__company_1a8b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'purpose'], name='accounting__company_a59fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'parent'], name='accounting__company_d0fbc3_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'level'], name='accounting__company_8a0ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'is_group'], name='accounting__company_21c630_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'is_active'], name='accounting__company_054bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'is_system'], name='accounting__company_4efbf1_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_account_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['company', 'code'], name='accounting__company_a9f6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['company', 'parent'], name='accounting__company_c1d06d_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['company', 'level'], name='accounting__company_458d47_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['company', 'is_group'], name='accounting__company_f459f3_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['company', 'status'], name='accounting__company_6779c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_cost_center_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='fiscalyear',
            index=models.Index(fields=['company', 'start_date'], name='accounting__company_763e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalyear',
            index=models.Index(fields=['company', 'end_date'], name='accounting__company_7eb6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalyear',
            index=models.Index(fields=['company', 'status'], name='accounting__company_a6f5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalyear',
            index=models.Index(fields=['company', 'is_current'], name='accounting__company_e050b9_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalyear',
            index=models.Index(fields=['company', 'is_default'], name='accounting__company_eeaebb_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalyear',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_fiscal_year_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='fiscalyear',
            constraint=models.UniqueConstraint(fields=('company', 'start_date', 'end_date'), name='unique_fiscal_year_range_per_company'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['company', 'fiscal_year'], name='accounting__company_641d33_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['company', 'start_date'], name='accounting__company_f87923_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['company', 'end_date'], name='accounting__company_cf359a_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['company', 'status'], name='accounting__company_925a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['company', 'is_adjustment_period'], name='accounting__company_385106_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.UniqueConstraint(fields=('company', 'fiscal_year', 'name'), name='unique_accounting_period_name_per_year_company'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.UniqueConstraint(fields=('company', 'fiscal_year', 'start_date', 'end_date'), name='unique_accounting_period_range_per_year_company'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'entry_number'], name='accounting__company_ebb16a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'entry_date'], name='accounting__company_534f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'period'], name='accounting__company_7fbaa4_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'status'], name='accounting__company_29aea2_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'posting_source'], name='accounting__company_304c53_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'reference'], name='accounting__company_733c76_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'external_reference'], name='accounting__company_e66ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'source_type'], name='accounting__company_779713_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'source_id'], name='accounting__company_96585a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'source_number'], name='accounting__company_af2055_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'currency'], name='accounting__company_317240_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'is_auto_posted'], name='accounting__company_e41cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'reversal_of'], name='accounting__company_356a65_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'status', 'entry_date'], name='accounting__company_00e37a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'source_type', 'source_id'], name='accounting__company_e3d1e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('company', 'entry_number'), name='unique_journal_entry_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['company', 'code'], name='accounting__company_4df7ee_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['company', 'tax_type'], name='accounting__company_0dbc29_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['company', 'direction'], name='accounting__company_dabd2a_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['company', 'is_active'], name='accounting__company_16e09e_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['company', 'is_default'], name='accounting__company_94256a_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxrate',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_tax_rate_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['company', 'journal_entry'], name='accounting__company_16b38e_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['company', 'account'], name='accounting__company_e4f32d_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['company', 'cost_center'], name='accounting__company_5565f6_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['company', 'tax_rate'], name='accounting__company_4b2864_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['company', 'party_type'], name='accounting__company_ba4310_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['company', 'party_id'], name='accounting__company_cb5691_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['company', 'source_line_id'], name='accounting__company_afa3f5_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['company', 'sort_order'], name='accounting__company_1323ea_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingroutingrule',
            index=models.Index(fields=['company', 'source'], name='accounting__company_11e932_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingroutingrule',
            index=models.Index(fields=['company', 'purpose'], name='accounting__company_f66866_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingroutingrule',
            index=models.Index(fields=['company', 'is_active'], name='accounting__company_b06773_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingroutingrule',
            index=models.Index(fields=['company', 'priority'], name='accounting__company_972d79_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingroutingrule',
            index=models.Index(fields=['company', 'source', 'purpose', 'is_active'], name='accounting__company_85dfa3_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountingroutingrule',
            constraint=models.UniqueConstraint(fields=('company', 'source', 'purpose', 'account', 'tax_rate', 'cost_center'), name='unique_accounting_routing_rule_per_company'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['company', 'tax_rate'], name='accounting__company_e491b0_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['company', 'direction'], name='accounting__company_b4cf96_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['company', 'transaction_date'], name='accounting__company_90ecf0_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['company', 'currency'], name='accounting__company_9a504a_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['company', 'source_type'], name='accounting__company_da4455_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['company', 'source_id'], name='accounting__company_19e5ba_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['company', 'source_number'], name='accounting__company_258faf_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['company', 'journal_entry'], name='accounting__company_91b560_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['company', 'journal_line'], name='accounting__company_809274_idx'),
        ),
    ]
