# Generated by Django 6.0.6 on 2026-06-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_accountingroutingrule_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingroutingrule',
            name='source',
            field=models.CharField(choices=[('SALES_INVOICE', 'فاتورة مبيعات'), ('SALES_CREDIT_NOTE', '????? ???? ??????'), ('SALES_PAYMENT', 'تحصيل مبيعات'), ('PURCHASE_BILL', 'فاتورة مشتريات'), ('SUPPLIER_DEBIT_NOTE', '????? ??? ????'), ('SUPPLIER_PAYMENT', 'سداد مورد'), ('INVENTORY_RECEIPT', 'استلام مخزون'), ('INVENTORY_ISSUE', 'صرف مخزون'), ('INVENTORY_ADJUSTMENT', 'تسوية مخزون'), ('INVENTORY_TRANSFER', 'تحويل مخزون'), ('TREASURY_INCOME', 'قبض خزينة'), ('TREASURY_EXPENSE', 'صرف خزينة'), ('TREASURY_TRANSFER', 'تحويل خزينة'), ('TAX_SETTLEMENT', 'تسوية ضريبية'), ('OPENING_BALANCE', 'رصيد افتتاحي'), ('OTHER', 'أخرى')], max_length=50, verbose_name='مصدر العملية'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='posting_source',
            field=models.CharField(choices=[('MANUAL', 'يدوي'), ('OPENING_BALANCE', 'رصيد افتتاحي'), ('SALES_INVOICE', 'فاتورة مبيعات'), ('SALES_CREDIT_NOTE', '????? ???? ??????'), ('SALES_PAYMENT', 'تحصيل مبيعات'), ('PURCHASE_BILL', 'فاتورة مشتريات'), ('SUPPLIER_DEBIT_NOTE', '????? ??? ????'), ('SUPPLIER_PAYMENT', 'سداد مورد'), ('INVENTORY_RECEIPT', 'استلام مخزون'), ('INVENTORY_ISSUE', 'صرف مخزون'), ('INVENTORY_ADJUSTMENT', 'تسوية مخزون'), ('INVENTORY_TRANSFER', 'تحويل مخزون'), ('TREASURY', 'خزينة'), ('TREASURY_RECEIPT', 'سند قبض'), ('TREASURY_PAYMENT', 'سند صرف'), ('TREASURY_TRANSFER', 'تحويل خزينة'), ('TAX', 'ضريبة'), ('ADJUSTMENT', 'تسوية'), ('SYSTEM', 'نظام'), ('OTHER', 'أخرى')], default='MANUAL', max_length=40, verbose_name='مصدر القيد'),
        ),
    ]
