# Generated by Django 6.0.6 on 2026-07-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_accountingroutingrule_source_and_more'),
        ('companies', '0005_seed_activity_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='calculation_base',
            field=models.CharField(choices=[('NET', 'صافي السطر'), ('GROSS', 'السعر شامل الضريبة'), ('AFTER_PREVIOUS_TAX', 'بعد الضرائب السابقة'), ('RETAIL_PRICE', 'سعر البيع')], db_index=True, default='NET', max_length=30, verbose_name='أساس احتساب الضريبة'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='is_system',
            field=models.BooleanField(db_index=True, default=False, verbose_name='ضريبة نظامية'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='اسم الضريبة بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='صالحة من'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='valid_to',
            field=models.DateField(blank=True, null=True, verbose_name='صالحة إلى'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='zatca_category_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Examples: S, Z, E, O for VAT categories. Leave blank for non-VAT taxes.', max_length=10, verbose_name='كود تصنيف VAT في زاتكا'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='zatca_exemption_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='سبب الإعفاء'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='zatca_exemption_reason_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='كود سبب الإعفاء في زاتكا'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='tax_type',
            field=models.CharField(choices=[('VAT', 'ضريبة القيمة المضافة'), ('WITHHOLDING', 'ضريبة استقطاع'), ('EXCISE', 'ضريبة انتقائية'), ('ZAKAT', 'زكاة'), ('CUSTOM', 'ضريبة مخصصة'), ('OTHER', 'أخرى')], default='VAT', max_length=20, verbose_name='نوع الضريبة'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['company', 'calculation_base'], name='accounting__company_9d4d85_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['company', 'zatca_category_code'], name='accounting__company_a2a9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['company', 'is_system'], name='accounting__company_938b1e_idx'),
        ),
    ]
