# Generated by Django 6.0.6 on 2026-09-18 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_taxrate_calculation_base_taxrate_is_system_and_more'),
        ('companies', '0006_company_onboarding_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers', to='companies.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='companies.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry_lines', to='companies.branch', verbose_name='الفرع'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['company', 'branch'], name='accounting__company_3330da_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'branch'], name='accounting__company_007cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'branch', 'entry_date'], name='accounting__company_d268fc_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['company', 'branch'], name='accounting__company_bc188e_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['company', 'branch', 'account'], name='accounting__company_a12b07_idx'),
        ),
    ]
