# Generated by Django 6.0.6 on 2026-06-10 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_branch_companysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error')], db_index=True, default='INFO', max_length=30, verbose_name='Notification type')),
                ('channel', models.CharField(choices=[('IN_APP', 'In App'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SYSTEM', 'System')], db_index=True, default='IN_APP', max_length=30, verbose_name='Channel')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=30, verbose_name='Priority')),
                ('source_type', models.CharField(blank=True, db_index=True, help_text='Examples: sales_invoice, purchase_bill, pos_order, treasury_transaction.', max_length=100, verbose_name='Source type')),
                ('source_id', models.CharField(blank=True, db_index=True, help_text='Stores source object ID as string to avoid hard coupling with modules.', max_length=100, verbose_name='Source ID')),
                ('action_url', models.CharField(blank=True, help_text='Optional frontend URL related to this notification.', max_length=500, verbose_name='Action URL')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('recipient', models.ForeignKey(blank=True, help_text='Optional. Empty means company-wide notification.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Company notification',
                'verbose_name_plural': 'Company notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'recipient', 'is_read'], name='notificatio_company_6e42dd_idx'), models.Index(fields=['company', 'channel', 'created_at'], name='notificatio_company_bb3135_idx'), models.Index(fields=['company', 'notification_type', 'created_at'], name='notificatio_company_6a28df_idx'), models.Index(fields=['company', 'priority', 'created_at'], name='notificatio_company_6b42e7_idx'), models.Index(fields=['company', 'source_type', 'source_id'], name='notificatio_company_a225c7_idx')],
            },
        ),
    ]
