# Generated by Django 6.0.6 on 2026-06-07 10:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('companies', '0003_branch_companysettings'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, help_text='Unique inside the same company when provided.', max_length=60, verbose_name='Invoice number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially paid'), ('PAID', 'Paid')], db_index=True, default='UNPAID', max_length=20, verbose_name='Payment status')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('POS', 'POS'), ('ONLINE', 'Online'), ('IMPORT', 'Import'), ('API', 'API')], db_index=True, default='MANUAL', max_length=20, verbose_name='Source')),
                ('invoice_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Invoice date')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Due date')),
                ('issued_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Issued at')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cancelled at')),
                ('cancelled_reason', models.TextField(blank=True, default='', verbose_name='Cancelled reason')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount amount')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxable amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Payment allocation will be handled in a later phase.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Paid amount')),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Balance due')),
                ('currency_code', models.CharField(default='SAR', max_length=10, verbose_name='Currency code')),
                ('customer_snapshot', models.JSONField(blank=True, default=dict, help_text='Customer data snapshot at invoice time.', verbose_name='Customer snapshot')),
                ('billing_address_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Billing address snapshot')),
                ('tax_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Tax snapshot')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('public_notes', models.TextField(blank=True, default='', help_text='Notes visible to customer on invoice.', verbose_name='Public notes')),
                ('internal_notes', models.TextField(blank=True, default='', verbose_name='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('branch', models.ForeignKey(blank=True, help_text='Optional branch. Must belong to the same company.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='companies.branch', verbose_name='Branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sales_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('customer', models.ForeignKey(blank=True, help_text='Optional customer. Must be an active customer inside the same company.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='parties.businessparty', verbose_name='Customer')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_sales_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Issued by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sales_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Sales Invoice',
                'verbose_name_plural': 'Sales Invoices',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Line number')),
                ('item_code_snapshot', models.CharField(blank=True, default='', max_length=80, verbose_name='Item code snapshot')),
                ('item_name_snapshot', models.CharField(max_length=255, verbose_name='Item name snapshot')),
                ('item_description_snapshot', models.TextField(blank=True, default='', verbose_name='Item description snapshot')),
                ('unit_name_snapshot', models.CharField(blank=True, default='', max_length=120, verbose_name='Unit name snapshot')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit price')),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Line subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount amount')),
                ('taxable', models.BooleanField(db_index=True, default=True, verbose_name='Taxable')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax rate')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxable amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax amount')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Line total')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('catalog_item', models.ForeignKey(blank=True, help_text='Optional catalog item. Snapshot fields preserve historical data.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoice_items', to='catalog.catalogitem', verbose_name='Catalog item')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoice_items', to='companies.company', verbose_name='Company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesinvoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Sales Invoice Item',
                'verbose_name_plural': 'Sales Invoice Items',
                'ordering': ['invoice_id', 'line_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['company', 'status'], name='sales_sales_company_6012fa_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['company', 'payment_status'], name='sales_sales_company_4cc207_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['company', 'source'], name='sales_sales_company_f6bab6_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['company', 'invoice_date'], name='sales_sales_company_0a60a9_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['company', 'due_date'], name='sales_sales_company_c579ba_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['company', 'created_at'], name='sales_sales_company_4aea00_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['company', 'customer'], name='sales_sales_company_593a97_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['company', 'branch'], name='sales_sales_company_dfcd22_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['branch', 'status'], name='sales_sales_branch__55e5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['customer', 'status'], name='sales_sales_custome_920c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['invoice_number'], name='sales_sales_invoice_b577c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number', ''), _negated=True), fields=('company', 'invoice_number'), name='unique_sales_invoice_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceitem',
            index=models.Index(fields=['company', 'invoice'], name='sales_sales_company_4efb58_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceitem',
            index=models.Index(fields=['company', 'catalog_item'], name='sales_sales_company_0c8b82_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceitem',
            index=models.Index(fields=['invoice', 'line_number'], name='sales_sales_invoice_b6bd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceitem',
            index=models.Index(fields=['company', 'created_at'], name='sales_sales_company_232fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceitem',
            index=models.Index(fields=['company', 'taxable'], name='sales_sales_company_6b19fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoiceitem',
            constraint=models.UniqueConstraint(fields=('invoice', 'line_number'), name='unique_sales_invoice_line_number_per_invoice'),
        ),
    ]
