# Generated by Django 6.0.6 on 2026-06-12 22:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('parties', '0001_initial'),
        ('sales', '0002_alter_salesinvoice_paid_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(db_index=True, help_text='Unique inside the same company when provided.', max_length=60, verbose_name='Quotation number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('ONLINE', 'Online'), ('IMPORT', 'Import'), ('API', 'API')], db_index=True, default='MANUAL', max_length=20, verbose_name='Source')),
                ('quotation_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Quotation date')),
                ('valid_until', models.DateField(blank=True, db_index=True, null=True, verbose_name='Valid until')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Sent at')),
                ('accepted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Accepted at')),
                ('rejected_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Rejected at')),
                ('expired_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Expired at')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cancelled at')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Rejection reason')),
                ('cancelled_reason', models.TextField(blank=True, default='', verbose_name='Cancelled reason')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount amount')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxable amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total amount')),
                ('currency_code', models.CharField(default='SAR', max_length=10, verbose_name='Currency code')),
                ('customer_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Customer snapshot')),
                ('billing_address_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Billing address snapshot')),
                ('tax_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Tax snapshot')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('terms_and_conditions', models.TextField(blank=True, default='', verbose_name='Terms and conditions')),
                ('public_notes', models.TextField(blank=True, default='', verbose_name='Public notes')),
                ('internal_notes', models.TextField(blank=True, default='', verbose_name='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_sales_quotations', to=settings.AUTH_USER_MODEL, verbose_name='Accepted by')),
                ('branch', models.ForeignKey(blank=True, help_text='Optional branch. Must belong to the same company.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quotations', to='companies.branch', verbose_name='Branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sales_quotations', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_quotations', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_quotations', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('customer', models.ForeignKey(blank=True, help_text='Optional in draft. Required before sending.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quotations', to='parties.businessparty', verbose_name='Customer')),
                ('expired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expired_sales_quotations', to=settings.AUTH_USER_MODEL, verbose_name='Expired by')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_sales_quotations', to=settings.AUTH_USER_MODEL, verbose_name='Rejected by')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_sales_quotations', to=settings.AUTH_USER_MODEL, verbose_name='Sent by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sales_quotations', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Sales Quotation',
                'verbose_name_plural': 'Sales Quotations',
                'ordering': ['-quotation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Line number')),
                ('item_code_snapshot', models.CharField(blank=True, default='', max_length=80, verbose_name='Item code snapshot')),
                ('item_name_snapshot', models.CharField(max_length=255, verbose_name='Item name snapshot')),
                ('item_description_snapshot', models.TextField(blank=True, default='', verbose_name='Item description snapshot')),
                ('unit_name_snapshot', models.CharField(blank=True, default='', max_length=120, verbose_name='Unit name snapshot')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit price')),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Line subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount amount')),
                ('taxable', models.BooleanField(db_index=True, default=True, verbose_name='Taxable')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax rate')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxable amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax amount')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Line total')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quotation_items', to='catalog.catalogitem', verbose_name='Catalog item')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_quotation_items', to='companies.company', verbose_name='Company')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesquotation', verbose_name='Quotation')),
            ],
            options={
                'verbose_name': 'Sales Quotation Item',
                'verbose_name_plural': 'Sales Quotation Items',
                'ordering': ['quotation_id', 'line_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='salesquotation',
            index=models.Index(fields=['company', 'status'], name='sales_sales_company_1a6836_idx'),
        ),
        migrations.AddIndex(
            model_name='salesquotation',
            index=models.Index(fields=['company', 'source'], name='sales_sales_company_ae7085_idx'),
        ),
        migrations.AddIndex(
            model_name='salesquotation',
            index=models.Index(fields=['company', 'quotation_date'], name='sales_sales_company_c4ab6e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesquotation',
            index=models.Index(fields=['company', 'valid_until'], name='sales_sales_company_57102e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesquotation',
            index=models.Index(fields=['company', 'customer'], name='sales_sales_company_254633_idx'),
        ),
        migrations.AddIndex(
            model_name='salesquotation',
            index=models.Index(fields=['company', 'branch'], name='sales_sales_company_408d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesquotation',
            index=models.Index(fields=['company', 'created_at'], name='sales_sales_company_7a8a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesquotation',
            index=models.Index(fields=['branch', 'status'], name='sales_sales_branch__b0f25a_idx'),
        ),
        migrations.AddIndex(
            model_name='salesquotation',
            index=models.Index(fields=['customer', 'status'], name='sales_sales_custome_58d890_idx'),
        ),
        migrations.AddIndex(
            model_name='salesquotation',
            index=models.Index(fields=['quotation_number'], name='sales_sales_quotati_fb04d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesquotation',
            constraint=models.UniqueConstraint(condition=models.Q(('quotation_number', ''), _negated=True), fields=('company', 'quotation_number'), name='unique_sales_quotation_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='salesquotationitem',
            index=models.Index(fields=['company', 'quotation'], name='sales_sales_company_35e7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='salesquotationitem',
            index=models.Index(fields=['company', 'catalog_item'], name='sales_sales_company_95b1b5_idx'),
        ),
        migrations.AddIndex(
            model_name='salesquotationitem',
            index=models.Index(fields=['quotation', 'line_number'], name='sales_sales_quotati_3815f8_idx'),
        ),
        migrations.AddIndex(
            model_name='salesquotationitem',
            index=models.Index(fields=['company', 'created_at'], name='sales_sales_company_6192fc_idx'),
        ),
        migrations.AddIndex(
            model_name='salesquotationitem',
            index=models.Index(fields=['company', 'taxable'], name='sales_sales_company_2852ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesquotationitem',
            constraint=models.UniqueConstraint(fields=('quotation', 'line_number'), name='unique_sales_quotation_line_number_per_quotation'),
        ),
    ]
