# Generated by Django 6.0.6 on 2026-06-13 11:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('parties', '0001_initial'),
        ('sales', '0004_salesorder_salesorderitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='source_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to='sales.salesorder', verbose_name='Source sales order'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='source_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='sales.salesorderitem', verbose_name='Source sales order item'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='billing_status',
            field=models.CharField(choices=[('NOT_INVOICED', 'Not invoiced'), ('PARTIAL', 'Partially invoiced'), ('FULL', 'Fully invoiced')], db_index=True, default='NOT_INVOICED', max_length=20, verbose_name='Billing status'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invoiced_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Invoiced amount'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='invoiced_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Invoiced quantity'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Remaining quantity'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SALES_ORDER', 'Sales order'), ('POS', 'POS'), ('ONLINE', 'Online'), ('IMPORT', 'Import'), ('API', 'API')], db_index=True, default='MANUAL', max_length=20, verbose_name='Source'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['company', 'billing_status'], name='sales_sales_company_69c4c6_idx'),
        ),
    ]
