# Generated by Django 6.0.6 on 2026-06-13 12:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('inventory', '0001_initial'),
        ('parties', '0001_initial'),
        ('sales', '0005_salesinvoice_source_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(db_index=True, help_text='Unique inside the same company.', max_length=60, verbose_name='Return number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('reason', models.CharField(choices=[('CUSTOMER_REQUEST', 'Customer request'), ('DAMAGED', 'Damaged item'), ('DEFECTIVE', 'Defective item'), ('WRONG_ITEM', 'Wrong item'), ('WRONG_QUANTITY', 'Wrong quantity'), ('EXPIRED', 'Expired item'), ('QUALITY_ISSUE', 'Quality issue'), ('OTHER', 'Other')], db_index=True, default='CUSTOMER_REQUEST', max_length=40, verbose_name='Return reason')),
                ('reason_details', models.TextField(blank=True, default='', verbose_name='Reason details')),
                ('return_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Return date')),
                ('confirmed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Confirmed at')),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Posted at')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cancelled at')),
                ('cancelled_reason', models.TextField(blank=True, default='', verbose_name='Cancelled reason')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount amount')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxable amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total amount')),
                ('currency_code', models.CharField(default='SAR', max_length=10, verbose_name='Currency code')),
                ('customer_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Customer snapshot')),
                ('invoice_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Invoice snapshot')),
                ('tax_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Tax snapshot')),
                ('public_notes', models.TextField(blank=True, default='', verbose_name='Public notes')),
                ('internal_notes', models.TextField(blank=True, default='', verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_returns', to='companies.branch', verbose_name='Branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sales_returns', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='companies.company', verbose_name='Company')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_sales_returns', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_returns', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_returns', to='parties.businessparty', verbose_name='Customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='sales.salesinvoice', verbose_name='Sales invoice')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_sales_returns', to=settings.AUTH_USER_MODEL, verbose_name='Posted by')),
                ('return_warehouse', models.ForeignKey(blank=True, help_text='Optional in draft. Used later for physical inventory return processing.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='inventory.warehouse', verbose_name='Return warehouse')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sales_returns', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Sales Return',
                'verbose_name_plural': 'Sales Returns',
                'ordering': ['-return_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Line number')),
                ('item_code_snapshot', models.CharField(blank=True, default='', max_length=80, verbose_name='Item code snapshot')),
                ('item_name_snapshot', models.CharField(max_length=255, verbose_name='Item name snapshot')),
                ('item_description_snapshot', models.TextField(blank=True, default='', verbose_name='Item description snapshot')),
                ('unit_name_snapshot', models.CharField(blank=True, default='', max_length=120, verbose_name='Unit name snapshot')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Returned quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit price')),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Line subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount amount')),
                ('taxable', models.BooleanField(db_index=True, default=True, verbose_name='Taxable')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax rate')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxable amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax amount')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Line total')),
                ('restock', models.BooleanField(db_index=True, default=True, help_text='Inventory services ignore service or non-inventory catalog items.', verbose_name='Restock item')),
                ('condition_notes', models.TextField(blank=True, default='', verbose_name='Condition notes')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_return_items', to='catalog.catalogitem', verbose_name='Catalog item')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_return_items', to='companies.company', verbose_name='Company')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_items', to='sales.salesinvoiceitem', verbose_name='Source invoice item')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesreturn', verbose_name='Sales return')),
            ],
            options={
                'verbose_name': 'Sales Return Item',
                'verbose_name_plural': 'Sales Return Items',
                'ordering': ['sales_return_id', 'line_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['company', 'status'], name='sales_sales_company_0752c1_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['company', 'reason'], name='sales_sales_company_4fdecf_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['company', 'return_date'], name='sales_sales_company_09c313_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['company', 'invoice'], name='sales_sales_company_8b2624_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['company', 'customer'], name='sales_sales_company_84ffb8_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['company', 'branch'], name='sales_sales_company_54ba87_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['company', 'return_warehouse'], name='sales_sales_company_4f578c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['company', 'created_at'], name='sales_sales_company_70ec2c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['return_number'], name='sales_sales_return__ed5929_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.UniqueConstraint(condition=models.Q(('return_number', ''), _negated=True), fields=('company', 'return_number'), name='unique_sales_return_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['company', 'sales_return'], name='sales_sales_company_2a7fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['company', 'invoice_item'], name='sales_sales_company_5d6b10_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['company', 'catalog_item'], name='sales_sales_company_8a3518_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['sales_return', 'line_number'], name='sales_sales_sales_r_7b1e26_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['company', 'restock'], name='sales_sales_company_d90469_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['company', 'created_at'], name='sales_sales_company_47ca41_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesreturnitem',
            constraint=models.UniqueConstraint(fields=('sales_return', 'line_number'), name='unique_sales_return_line_number_per_return'),
        ),
        migrations.AddConstraint(
            model_name='salesreturnitem',
            constraint=models.UniqueConstraint(fields=('sales_return', 'invoice_item'), name='unique_invoice_item_per_sales_return'),
        ),
    ]
