# Generated by Django 6.0.6 on 2026-06-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salesreturn_salesreturnitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturnitem',
            name='item_name_snapshot',
            field=models.CharField(blank=True, default='', help_text='Automatically copied from the source sales invoice item.', max_length=255, verbose_name='Item name snapshot'),
        ),
    ]
