# Generated by Django 6.0.6 on 2026-06-13 13:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('parties', '0001_initial'),
        ('sales', '0007_alter_salesreturnitem_item_name_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(db_index=True, help_text='Unique inside the same company.', max_length=60, verbose_name='Credit note number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('credit_note_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Credit note date')),
                ('issued_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Issued at')),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Posted at')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cancelled at')),
                ('cancelled_reason', models.TextField(blank=True, default='', verbose_name='Cancelled reason')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount amount')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxable amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total amount')),
                ('currency_code', models.CharField(default='SAR', max_length=10, verbose_name='Currency code')),
                ('customer_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Customer snapshot')),
                ('invoice_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Invoice snapshot')),
                ('return_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Sales return snapshot')),
                ('tax_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Tax snapshot')),
                ('public_notes', models.TextField(blank=True, default='', verbose_name='Public notes')),
                ('internal_notes', models.TextField(blank=True, default='', verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_credit_notes', to='companies.branch', verbose_name='Branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sales_credit_notes', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_credit_notes', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_credit_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_credit_notes', to='parties.businessparty', verbose_name='Customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='sales.salesinvoice', verbose_name='Sales invoice')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_sales_credit_notes', to=settings.AUTH_USER_MODEL, verbose_name='Issued by')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_sales_credit_notes', to=settings.AUTH_USER_MODEL, verbose_name='Posted by')),
                ('sales_return', models.OneToOneField(blank=True, help_text='Optional in draft. A sales return can create only one credit note.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_note', to='sales.salesreturn', verbose_name='Sales return')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sales_credit_notes', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Sales Credit Note',
                'verbose_name_plural': 'Sales Credit Notes',
                'ordering': ['-credit_note_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesCreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Line number')),
                ('item_code_snapshot', models.CharField(blank=True, default='', max_length=80, verbose_name='Item code snapshot')),
                ('item_name_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Item name snapshot')),
                ('item_description_snapshot', models.TextField(blank=True, default='', verbose_name='Item description snapshot')),
                ('unit_name_snapshot', models.CharField(blank=True, default='', max_length=120, verbose_name='Unit name snapshot')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit price')),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Line subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount amount')),
                ('taxable', models.BooleanField(db_index=True, default=True, verbose_name='Taxable')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax rate')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxable amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax amount')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Line total')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Internal notes')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_credit_note_items', to='catalog.catalogitem', verbose_name='Catalog item')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_credit_note_items', to='companies.company', verbose_name='Company')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salescreditnote', verbose_name='Credit note')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_items', to='sales.salesinvoiceitem', verbose_name='Invoice item')),
                ('sales_return_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_item', to='sales.salesreturnitem', verbose_name='Sales return item')),
            ],
            options={
                'verbose_name': 'Sales Credit Note Item',
                'verbose_name_plural': 'Sales Credit Note Items',
                'ordering': ['credit_note_id', 'line_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='salescreditnote',
            index=models.Index(fields=['company', 'status'], name='sales_sales_company_332321_idx'),
        ),
        migrations.AddIndex(
            model_name='salescreditnote',
            index=models.Index(fields=['company', 'credit_note_date'], name='sales_sales_company_1d2754_idx'),
        ),
        migrations.AddIndex(
            model_name='salescreditnote',
            index=models.Index(fields=['company', 'invoice'], name='sales_sales_company_71b2f9_idx'),
        ),
        migrations.AddIndex(
            model_name='salescreditnote',
            index=models.Index(fields=['company', 'customer'], name='sales_sales_company_36d6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='salescreditnote',
            index=models.Index(fields=['company', 'branch'], name='sales_sales_company_406df5_idx'),
        ),
        migrations.AddIndex(
            model_name='salescreditnote',
            index=models.Index(fields=['company', 'created_at'], name='sales_sales_company_cefe14_idx'),
        ),
        migrations.AddIndex(
            model_name='salescreditnote',
            index=models.Index(fields=['credit_note_number'], name='sales_sales_credit__8c3b52_idx'),
        ),
        migrations.AddConstraint(
            model_name='salescreditnote',
            constraint=models.UniqueConstraint(condition=models.Q(('credit_note_number', ''), _negated=True), fields=('company', 'credit_note_number'), name='unique_sales_credit_note_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='salescreditnoteitem',
            index=models.Index(fields=['company', 'credit_note'], name='sales_sales_company_d68824_idx'),
        ),
        migrations.AddIndex(
            model_name='salescreditnoteitem',
            index=models.Index(fields=['company', 'invoice_item'], name='sales_sales_company_91a3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='salescreditnoteitem',
            index=models.Index(fields=['company', 'catalog_item'], name='sales_sales_company_e2d22a_idx'),
        ),
        migrations.AddIndex(
            model_name='salescreditnoteitem',
            index=models.Index(fields=['credit_note', 'line_number'], name='sales_sales_credit__5a7329_idx'),
        ),
        migrations.AddIndex(
            model_name='salescreditnoteitem',
            index=models.Index(fields=['company', 'created_at'], name='sales_sales_company_7701c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='salescreditnoteitem',
            constraint=models.UniqueConstraint(fields=('credit_note', 'line_number'), name='unique_sales_credit_note_line_number'),
        ),
    ]
