# Generated by Django 6.0.6 on 2026-06-13 20:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_activityprofile_company_activity_profile_ref_and_more'),
        ('parties', '0001_initial'),
        ('sales', '0008_salescreditnote_salescreditnoteitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salescreditnote',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount already allocated from this posted credit note to sales invoices.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Allocated amount'),
        ),
        migrations.CreateModel(
            name='CustomerCreditAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Allocated amount')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVERSED', 'Reversed')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Status')),
                ('allocated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Allocated at')),
                ('reversed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Reversed at')),
                ('reversal_reason', models.TextField(blank=True, default='', verbose_name='Reversal reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_credit_allocations', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_credit_allocations', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='sales.salescreditnote', verbose_name='Sales credit note')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_allocations', to='parties.businessparty', verbose_name='Customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_allocations', to='sales.salesinvoice', verbose_name='Sales invoice')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_customer_credit_allocations', to=settings.AUTH_USER_MODEL, verbose_name='Reversed by')),
            ],
            options={
                'verbose_name': 'Customer Credit Allocation',
                'verbose_name_plural': 'Customer Credit Allocations',
                'ordering': ['-allocated_at', '-id'],
                'indexes': [models.Index(fields=['company', 'customer'], name='sales_custo_company_7d45a3_idx'), models.Index(fields=['company', 'status'], name='sales_custo_company_3d898d_idx'), models.Index(fields=['company', 'credit_note'], name='sales_custo_company_db4927_idx'), models.Index(fields=['company', 'invoice'], name='sales_custo_company_c46272_idx'), models.Index(fields=['company', 'allocated_at'], name='sales_custo_company_cf4b12_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('credit_note', 'invoice'), name='unique_active_credit_allocation_per_invoice')],
            },
        ),
        migrations.CreateModel(
            name='CustomerCreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(db_index=True, default='SAR', max_length=10, verbose_name='Currency code')),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total posted credit')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Allocated amount')),
                ('available_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Available amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_credit_balances', to='companies.company', verbose_name='Company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_balances', to='parties.businessparty', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Customer Credit Balance',
                'verbose_name_plural': 'Customer Credit Balances',
                'ordering': ['customer_id', 'currency_code'],
                'indexes': [models.Index(fields=['company', 'customer'], name='sales_custo_company_ecf31d_idx'), models.Index(fields=['company', 'currency_code'], name='sales_custo_company_cb77f0_idx'), models.Index(fields=['company', 'available_amount'], name='sales_custo_company_3e5d32_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'customer', 'currency_code'), name='unique_customer_credit_balance_per_currency')],
            },
        ),
    ]
